Repository ReliefApplications/ems-frontend, pull requests merged in 2022-10, with the labels that each got.

#957 Hotfix 1.2.0/AB#41554 allow to send exported records by email
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/ui/core-grid/export/export.component.html
  projects/safe/src/lib/components/ui/core-grid/export/export.component.scss
  projects/safe/src/lib/components/ui/core-grid/export/export.component.ts
  projects/safe/src/lib/components/ui/core-grid/export/export.module.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.constants.ts
  projects/safe/src/lib/const/notifications.ts
  projects/safe/src/lib/services/application.service.ts
  projects/safe/src/lib/services/download.service.ts
Labels: enhancement, hotfix

#956 feat-1.4.0/AB#41411_derived-fields-ui
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab-routing.module.ts
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.html
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.scss
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.spec.ts
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.module.ts
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/graphql/mutations.ts
  projects/back-office/src/app/dashboard/pages/resource/resource-routing.module.ts
  projects/back-office/src/app/dashboard/pages/resource/resource.component.html
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.html
  projects/safe/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.scss
  projects/safe/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.spec.ts
  projects/safe/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.ts
  projects/safe/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.module.ts
  projects/safe/src/lib/components/edit-calculated-field-modal/public-api.ts
  projects/safe/src/lib/components/edit-calculated-field-modal/utils/keys.ts
  projects/safe/src/public-api.ts
Labels: enhancement

#958 feat-1.4.0/AB#41414_date-operations
  projects/safe/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.ts
  projects/safe/src/lib/components/edit-calculated-field-modal/utils/keys.ts
Labels: enhancement

#961 Feat-1.4.0/AB#42000 Download files in summary cards
  projects/safe/src/lib/components/widgets/summary-card/parser/utils.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.html
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.ts
Labels: enhancement

#953 Feat 1.4.0/AB#41723 summary cards correct layout use + Reproduce AB#34848
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.scss
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source.module.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/preview-tab/preview-tab.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/preview-tab/preview-tab.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  projects/safe/src/lib/components/widgets/summary-card/graphql/queries.ts
  projects/safe/src/lib/components/widgets/summary-card/parser/utils.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.html
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: bug, enhancement, refactor

#968 Feat 1.2.0/ab#35306 add limit in sort
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/query-builder/query-builder-forms.ts
  projects/safe/src/lib/components/query-builder/query-builder.component.html
  projects/safe/src/lib/components/query-builder/query-builder.component.ts
  projects/safe/src/lib/components/query-builder/tab-fields/tab-fields.component.ts
  projects/safe/src/lib/components/query-builder/tab-sort/tab-sort.component.html
  projects/safe/src/lib/components/query-builder/tab-sort/tab-sort.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/floating-button-settings/floating-button-settings.component.html
  projects/safe/src/lib/services/query-builder.service.ts
  projects/safe/src/lib/survey/widgets/text-widget.ts
Labels: enhancement

#971 Feat 1.4.0/oort 476 add summary card icon
  projects/back-office/src/assets/summary-card.svg
  projects/front-office/src/assets/summary-card.svg
  projects/safe/src/lib/models/dashboard.model.ts
  stories/assets/summary-card.svg
Labels: enhancement

#972 Refactor 1.3.0/oort 477 replace small mat form field
  projects/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.html
  projects/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.scss
  projects/back-office/src/app/dashboard/pages/applications/components/filter/filter.component.html
  projects/back-office/src/app/dashboard/pages/applications/components/filter/filter.component.scss
  projects/back-office/src/app/dashboard/pages/forms/components/filter/filter.component.html
  projects/back-office/src/app/dashboard/pages/forms/components/filter/filter.component.scss
  projects/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.html
  projects/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.scss
  projects/back-office/src/app/dashboard/pages/resources/filter/filter.component.html
  projects/back-office/src/app/dashboard/pages/resources/filter/filter.component.scss
  projects/safe/src/lib/components/role-summary/role-features/role-features.component.html
  projects/safe/src/lib/components/role-summary/role-features/role-features.component.scss
  projects/safe/src/lib/components/role-summary/role-resources-filter/role-resources-filter.component.html
  projects/safe/src/lib/components/role-summary/role-resources-filter/role-resources-filter.component.scss
  projects/safe/src/lib/components/roles/components/group-list/group-list.component.html
  projects/safe/src/lib/components/roles/components/group-list/group-list.component.scss
  projects/safe/src/lib/components/roles/components/role-list/role-list.component.html
  projects/safe/src/lib/components/roles/components/role-list/role-list.component.scss
  projects/safe/src/lib/components/users/users.component.html
  projects/safe/src/lib/components/users/users.component.scss
  projects/safe/src/lib/style/styles.scss
Labels: refactor

#975 Refactor display for edition of page name field with outline and matS…
  projects/back-office/src/app/application/pages/form/form.component.html
  projects/back-office/src/app/application/pages/workflow/workflow.component.html
  projects/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  projects/back-office/src/app/dashboard/pages/form-builder/form-builder.component.html
Labels: refactor

#974 Refactor 1.3.0/oort 478 create confirmation service
  projects/back-office/src/app/application/application.component.ts
  projects/back-office/src/app/application/application.module.ts
  projects/back-office/src/app/application/components/application-toolbar/application-toolbar.component.ts
  projects/back-office/src/app/application/components/application-toolbar/application-toolbar.module.ts
  projects/back-office/src/app/application/pages/channels/channels.component.ts
  projects/back-office/src/app/application/pages/channels/channels.module.ts
  projects/back-office/src/app/application/pages/position/position.component.ts
  projects/back-office/src/app/application/pages/position/position.module.ts
  projects/back-office/src/app/application/pages/settings/settings.component.ts
  projects/back-office/src/app/application/pages/subscriptions/subscriptions.module.ts
  projects/back-office/src/app/application/pages/workflow/workflow.component.ts
  projects/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.ts
  projects/back-office/src/app/dashboard/pages/applications/applications.component.ts
  projects/back-office/src/app/dashboard/pages/applications/applications.module.ts
  projects/back-office/src/app/dashboard/pages/form-builder/form-builder.component.ts
  projects/back-office/src/app/dashboard/pages/form-records/form-records.component.ts
  projects/back-office/src/app/dashboard/pages/forms/forms.component.ts
  projects/back-office/src/app/dashboard/pages/forms/forms.module.ts
  projects/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.ts
  projects/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.module.ts
  projects/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.ts
  projects/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/forms-tab/forms-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/forms-tab/forms-tab.module.ts
  projects/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.module.ts
  projects/back-office/src/app/dashboard/pages/resource/resource.module.ts
  projects/back-office/src/app/dashboard/pages/resources/resources.component.ts
  projects/safe/src/lib/components/confirm-modal/confirm-modal.component.ts
  projects/safe/src/lib/components/form-modal/form-modal.component.ts
  projects/safe/src/lib/components/form/form.component.ts
  projects/safe/src/lib/components/layout/layout.component.ts
  projects/safe/src/lib/components/layout/layout.module.ts
  projects/safe/src/lib/components/record-modal/record-modal.component.ts
  projects/safe/src/lib/components/roles/components/group-list/group-list.component.ts
  projects/safe/src/lib/components/roles/components/role-list/role-list.component.ts
  projects/safe/src/lib/components/roles/components/role-list/role-list.module.ts
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/users/users.component.ts
  projects/safe/src/lib/components/widget-grid/floating-options/floating-options.component.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
  projects/safe/src/lib/safe.module.ts
  projects/safe/src/lib/services/confirm/confirm.service.spec.ts
  projects/safe/src/lib/services/confirm/confirm.service.ts
  projects/safe/src/public-api.ts
Labels: refactor

#963 Feat-1.3.0/OORT-470 App page redesign
  projects/back-office/src/app/app-preview/components/preview-toolbar/preview-toolbar.component.html
  projects/back-office/src/app/app-preview/components/preview-toolbar/preview-toolbar.component.scss
  projects/back-office/src/app/app-preview/components/preview-toolbar/preview-toolbar.module.ts
  projects/back-office/src/app/application/application.component.html
  projects/back-office/src/app/application/application.component.ts
  projects/back-office/src/app/application/application.module.ts
  projects/back-office/src/app/application/components/application-toolbar/application-toolbar.component.html
  projects/back-office/src/app/application/components/application-toolbar/application-toolbar.module.ts
  projects/back-office/src/app/application/pages/settings/settings.component.html
  projects/back-office/src/app/application/pages/settings/settings.component.ts
  projects/back-office/src/app/application/pages/settings/settings.module.ts
  projects/front-office/src/app/dashboard/dashboard.component.html
  projects/front-office/src/app/dashboard/dashboard.component.ts
  projects/front-office/src/app/dashboard/dashboard.module.ts
  projects/safe/src/lib/components/application-toolbar/application-toolbar.component.html
  projects/safe/src/lib/components/application-toolbar/application-toolbar.component.scss
  projects/safe/src/lib/components/application-toolbar/application-toolbar.component.spec.ts
  projects/safe/src/lib/components/application-toolbar/application-toolbar.component.ts
  projects/safe/src/lib/components/application-toolbar/application-toolbar.module.ts
  projects/safe/src/lib/components/application-toolbar/public-api.ts
  projects/safe/src/lib/components/layout/layout.component.html
  projects/safe/src/lib/components/layout/layout.component.scss
  projects/safe/src/lib/components/layout/layout.component.ts
  projects/safe/src/lib/components/layout/layout.module.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-marker-rule/map-marker-rule.component.ts
  projects/safe/src/lib/style/styles.scss
  projects/safe/src/public-api.ts
Labels: refactor

#965 Refactor-1.3.0/AB#42125 remove advanced settings, keep mapping components
  projects/back-office/src/app/dashboard/pages/advanced-settings/advanced-settings-routing.module.ts
  projects/back-office/src/app/dashboard/pages/advanced-settings/advanced-settings.component.html
  projects/back-office/src/app/dashboard/pages/advanced-settings/advanced-settings.component.scss
  projects/back-office/src/app/dashboard/pages/advanced-settings/advanced-settings.component.spec.ts
  projects/back-office/src/app/dashboard/pages/advanced-settings/advanced-settings.component.ts
  projects/back-office/src/app/dashboard/pages/advanced-settings/advanced-settings.module.ts
  projects/back-office/src/app/dashboard/pages/advanced-settings/graphql/mutations.ts
  projects/back-office/src/app/dashboard/pages/advanced-settings/graphql/queries.ts
  projects/back-office/src/app/dashboard/pages/users/users-routing.module.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/mapping/mapping-forms.ts
  projects/safe/src/lib/components/mapping/mapping-modal/mapping-modal.component.ts
  projects/safe/src/lib/components/mapping/mapping.component.ts
  projects/safe/src/lib/components/user-summary/user-details/user-details.component.ts
  projects/safe/src/lib/components/users/users.component.html
  projects/safe/src/lib/components/users/users.component.ts
  projects/safe/src/lib/models/setting.model.ts
  projects/safe/src/public-api.ts
Labels: refactor

#980 Feat 1.3.0/oort 482 separate left sidenav
  projects/back-office/src/app/app-preview/app-preview.component.html
  projects/back-office/src/app/app-preview/app-preview.module.ts
  projects/back-office/src/app/application/application.component.html
  projects/back-office/src/app/application/application.module.ts
  projects/back-office/src/app/dashboard/dashboard.component.html
  projects/back-office/src/app/dashboard/dashboard.module.ts
  projects/front-office/src/app/dashboard/dashboard.component.html
  projects/front-office/src/app/dashboard/dashboard.module.ts
  projects/safe/src/lib/components/layout/layout.component.html
  projects/safe/src/lib/components/layout/layout.component.scss
  projects/safe/src/lib/components/layout/layout.component.ts
  projects/safe/src/lib/components/left-sidenav/left-sidenav.component.html
  projects/safe/src/lib/components/left-sidenav/left-sidenav.component.scss
  projects/safe/src/lib/components/left-sidenav/left-sidenav.component.spec.ts
  projects/safe/src/lib/components/left-sidenav/left-sidenav.component.ts
  projects/safe/src/lib/components/left-sidenav/left-sidenav.module.ts
  projects/safe/src/lib/components/left-sidenav/public-api.ts
  projects/safe/src/lib/components/role-summary/role-details/role-details.component.ts
  projects/safe/src/lib/safe.module.ts
  projects/safe/src/public-api.ts
Labels: enhancement, refactor

#977 feat-1.2.1/AB#42577_email-templates-def
  TODO.md
  projects/back-office/src/app/app-preview/app-preview-routing.module.ts
  projects/back-office/src/app/app-preview/app-preview.component.ts
  projects/back-office/src/app/application/application-routing.module.ts
  projects/back-office/src/app/application/application.component.ts
  projects/front-office/src/app/dashboard/dashboard-routing.module.ts
  projects/front-office/src/app/dashboard/dashboard.component.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/templates/components/edit-template/edit-template.component.html
  projects/safe/src/lib/components/templates/components/edit-template/edit-template.component.scss
  projects/safe/src/lib/components/templates/components/edit-template/edit-template.component.spec.ts
  projects/safe/src/lib/components/templates/components/edit-template/edit-template.component.ts
  projects/safe/src/lib/components/templates/public-api.ts
  projects/safe/src/lib/components/templates/templates.component.html
  projects/safe/src/lib/components/templates/templates.component.scss
  projects/safe/src/lib/components/templates/templates.component.spec.ts
  projects/safe/src/lib/components/templates/templates.component.ts
  projects/safe/src/lib/components/templates/templates.module.ts
  projects/safe/src/lib/components/widgets/grid-settings/floating-button-settings/floating-button-settings.component.html
  projects/safe/src/lib/components/widgets/grid-settings/floating-button-settings/floating-button-settings.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/grid-settings.component.html
  projects/safe/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  projects/safe/src/lib/components/widgets/grid/email-template-modal/email-template-modal.component.html
  projects/safe/src/lib/components/widgets/grid/email-template-modal/email-template-modal.component.scss
  projects/safe/src/lib/components/widgets/grid/email-template-modal/email-template-modal.component.spec.ts
  projects/safe/src/lib/components/widgets/grid/email-template-modal/email-template-modal.component.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
  projects/safe/src/lib/components/widgets/grid/grid.module.ts
  projects/safe/src/lib/graphql/mutations.ts
  projects/safe/src/lib/graphql/queries.ts
  projects/safe/src/lib/models/application.model.ts
  projects/safe/src/lib/models/template.model.ts
  projects/safe/src/lib/models/user.model.ts
  projects/safe/src/lib/pages/application-templates/application-templates-routing.module.ts
  projects/safe/src/lib/pages/application-templates/application-templates.component.html
  projects/safe/src/lib/pages/application-templates/application-templates.component.scss
  projects/safe/src/lib/pages/application-templates/application-templates.component.spec.ts
  projects/safe/src/lib/pages/application-templates/application-templates.component.ts
  projects/safe/src/lib/pages/application-templates/application-templates.module.ts
  projects/safe/src/lib/pages/application-templates/public-api.ts
  projects/safe/src/lib/safe.module.ts
  projects/safe/src/lib/services/application.service.ts
  projects/safe/src/public-api.ts
Labels: enhancement

#982 Fix 1.3.0/oort 485 prevent form being saved
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/application-dropdown/application-dropdown.component.ts
  projects/safe/src/lib/components/application-dropdown/graphql/queries.ts
  projects/safe/src/lib/components/form-builder/form-builder.component.ts
Labels: enhancement

#984 fix form records, has the same display than for resource records tab.
  projects/back-office/src/app/dashboard/pages/form-records/form-records.component.html
  projects/back-office/src/app/dashboard/pages/form-records/form-records.component.scss
  projects/back-office/src/app/dashboard/pages/form-records/form-records.component.ts
  projects/back-office/src/app/dashboard/pages/form-records/form-records.module.ts
  projects/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.html
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
Labels: enhancement

#985 Feat 1.3.0/oort 473 enhance dataset selection
  projects/back-office/src/app/components/add-form-modal/add-form-modal.component.ts
  projects/back-office/src/app/components/add-form-modal/graphql/queries.ts
  projects/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/grid-layout/edit-layout-modal/edit-layout-modal.component.html
  projects/safe/src/lib/components/grid-layout/layout-table/layout-table.component.ts
  projects/safe/src/lib/components/query-builder/tab-sort/tab-sort.component.html
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/ui/core-grid/export/export.component.html
  projects/safe/src/lib/components/widgets/grid-settings/graphql/queries.ts
  projects/safe/src/lib/components/widgets/grid-settings/grid-settings.component.html
  projects/safe/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
  projects/safe/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.html
  projects/safe/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.module.ts
  projects/safe/src/lib/components/widgets/grid-settings/tab-main/tab-main.component.html
  projects/safe/src/lib/components/widgets/grid-settings/tab-main/tab-main.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/tab-main/tab-main.module.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.html
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
Labels: enhancement

#986 Feat 1.3.0/oort 489 create rest service
  projects/safe/src/lib/components/form-modal/form-modal.component.ts
  projects/safe/src/lib/components/form/form.component.ts
  projects/safe/src/lib/components/layout/layout.component.scss
  projects/safe/src/lib/components/record-modal/record-modal.component.ts
  projects/safe/src/lib/components/role-summary/role-details/role-details.component.ts
  projects/safe/src/lib/components/roles/components/group-list/group-list.component.ts
  projects/safe/src/lib/components/ui/breadcrumb/breadcrumb.component.scss
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/user-summary/user-details/user-details.component.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
  projects/safe/src/lib/services/api-proxy/api-proxy.service.ts
  projects/safe/src/lib/services/auth-interceptor/auth-interceptor.service.ts
  projects/safe/src/lib/services/download/download.service.ts
  projects/safe/src/lib/services/email/email.service.ts
  projects/safe/src/lib/services/rest/rest.service.spec.ts
  projects/safe/src/lib/services/rest/rest.service.ts
Labels: enhancement, refactor

#990 fix-1.3.0/OORT-492_load-aggregations-bug
  projects/safe/src/lib/components/aggregation/aggregation-table/aggregation-table.component.ts
  projects/safe/src/lib/components/widgets/chart-settings/graphql/queries.ts
  projects/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.ts
Labels: bug

#989 fix-1.3.0/OORT-493_table-overflow
  projects/back-office/src/app/application/pages/channels/channels.component.html
  projects/back-office/src/app/application/pages/position-attributes/position-attributes.component.html
  projects/back-office/src/app/application/pages/position/position.component.html
  projects/back-office/src/app/application/pages/subscriptions/subscriptions.component.html
  projects/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.html
  projects/back-office/src/app/dashboard/pages/applications/applications.component.html
  projects/back-office/src/app/dashboard/pages/form-builder/components/history/history.component.html
  projects/back-office/src/app/dashboard/pages/form-records/form-records.component.html
  projects/back-office/src/app/dashboard/pages/forms/components/filter/filter.component.html
  projects/back-office/src/app/dashboard/pages/forms/components/filter/filter.component.ts
  projects/back-office/src/app/dashboard/pages/forms/forms.component.html
  projects/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.html
  projects/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.html
  projects/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.html
  projects/back-office/src/app/dashboard/pages/resource/forms-tab/forms-tab.component.html
  projects/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.html
  projects/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.html
  projects/back-office/src/app/dashboard/pages/resources/resources.component.html
  projects/safe/src/lib/components/aggregation/aggregation-table/aggregation-table.component.html
  projects/safe/src/lib/components/grid-layout/layout-table/layout-table.component.html
  projects/safe/src/lib/components/mapping/mapping.component.html
  projects/safe/src/lib/components/query-builder/tab-style/query-style-list/query-style-list.component.html
  projects/safe/src/lib/components/role-summary/role-auto-assignment/role-auto-assignment.component.html
  projects/safe/src/lib/components/role-summary/role-features/role-dashboards/role-dashboards.component.html
  projects/safe/src/lib/components/role-summary/role-features/role-forms/role-forms.component.html
  projects/safe/src/lib/components/role-summary/role-resources/resource-access-filters/resource-access-filters.component.html
  projects/safe/src/lib/components/role-summary/role-resources/resource-fields/resource-fields.component.html
  projects/safe/src/lib/components/role-summary/role-resources/role-resources.component.html
  projects/safe/src/lib/components/role-summary/role-users/role-users.component.html
  projects/safe/src/lib/components/roles/components/group-list/group-list.component.html
  projects/safe/src/lib/components/roles/components/role-list/role-list.component.html
  projects/safe/src/lib/components/ui/core-grid/errors-modal/errors-modal.component.html
  projects/safe/src/lib/components/users/users.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlet/map-clorophlet.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlets/map-clorophlets.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-markers/map-markers.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-online-layers/map-online-layers.component.html
  projects/safe/src/lib/pages/profile/profile.component.html
  projects/safe/src/lib/style/styles.scss
Labels: bug

#991 can now select resource + form to attach records from grid
  projects/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  projects/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/graphql/queries.ts
  projects/safe/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
  projects/safe/src/lib/components/widgets/grid/graphql/queries.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
Labels: enhancement
