Repository ReliefApplications/ems-frontend, pull requests merged in 2022-11, with the labels that each got.

#992 feat-1.3.0/OORT-491_attributes-in-permissions-module
  projects/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/filter/filter-row/filter-row.component.html
  projects/safe/src/lib/components/filter/filter-row/filter-row.component.ts
  projects/safe/src/lib/components/filter/filter.const.ts
  projects/safe/src/lib/components/role-summary/role-auto-assignment/role-auto-assignment.component.ts
  projects/safe/src/lib/components/role-summary/role-resources/resource-access-filters/resource-access-filters.component.ts
  projects/safe/src/lib/services/reference-data/reference-data.service.ts
  projects/safe/src/lib/style/styles.scss
Labels: enhancement

#995 Refactor 1.3.0/oort 490 remove form group css
  projects/back-office/src/app/application/pages/add-page/add-page.component.html
  projects/back-office/src/app/application/pages/add-page/add-page.component.scss
  projects/back-office/src/app/application/pages/channels/components/add-channel-modal/add-channel-modal.component.html
  projects/back-office/src/app/application/pages/channels/components/edit-channel-modal/edit-channel-modal.component.html
  projects/back-office/src/app/application/pages/position/components/position-modal/position-modal.component.html
  projects/back-office/src/app/application/pages/settings/settings.component.html
  projects/back-office/src/app/application/pages/settings/settings.component.scss
  projects/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.html
  projects/back-office/src/app/application/pages/workflow/components/add-step/add-step.component.html
  projects/back-office/src/app/application/pages/workflow/components/add-step/add-step.component.scss
  projects/back-office/src/app/components/add-form-modal/add-form-modal.component.html
  projects/back-office/src/app/components/add-resource-modal/add-resource-modal.component.html
  projects/back-office/src/app/components/duplicate-application-modal/duplicate-application-modal.component.html
  projects/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.html
  projects/back-office/src/app/dashboard/pages/api-configurations/components/add-api-configuration/add-api-configuration.component.html
  projects/back-office/src/app/dashboard/pages/applications/components/chose-role/chose-role.component.html
  projects/back-office/src/app/dashboard/pages/pull-jobs/components/pull-job-modal/pull-job-modal.component.html
  projects/back-office/src/app/dashboard/pages/pull-jobs/components/pull-job-modal/pull-job-modal.component.scss
  projects/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  projects/back-office/src/app/dashboard/pages/reference-datas/add-reference-data/add-reference-data.component.html
  projects/safe/src/lib/components/access/edit-access/edit-access.component.html
  projects/safe/src/lib/components/aggregation/edit-aggregation-modal/edit-aggregation-modal.component.html
  projects/safe/src/lib/components/choose-record-modal/choose-record-modal.component.html
  projects/safe/src/lib/components/config-display-grid-fields-modal/config-display-grid-fields-modal.component.html
  projects/safe/src/lib/components/convert-modal/convert-modal.component.html
  projects/safe/src/lib/components/preferences-modal/preferences-modal.component.html
  projects/safe/src/lib/components/query-builder/query-builder.component.html
  projects/safe/src/lib/components/query-builder/tab-fields/tab-fields.component.html
  projects/safe/src/lib/components/query-builder/tab-layout-preview/tab-layout-preview.component.html
  projects/safe/src/lib/components/role-summary/role-channels/role-channels.component.html
  projects/safe/src/lib/components/role-summary/role-details/role-details.component.html
  projects/safe/src/lib/components/roles/components/add-role/add-role.component.html
  projects/safe/src/lib/components/ui/core-grid/export/export.component.html
  projects/safe/src/lib/components/ui/core-grid/export/export.module.ts
  projects/safe/src/lib/components/user-summary/user-details/user-details.component.html
  projects/safe/src/lib/components/user-summary/user-roles/user-app-roles/user-app-roles.component.html
  projects/safe/src/lib/components/user-summary/user-roles/user-back-roles/user-back-roles.component.html
  projects/safe/src/lib/components/user-summary/user-roles/user-groups/user-groups.component.html
  projects/safe/src/lib/components/users/components/add-user/add-user.component.html
  projects/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.html
  projects/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.html
  projects/safe/src/lib/components/widgets/chart-settings/tab-preview/tab-preview.component.html
  projects/safe/src/lib/components/widgets/editor-settings/editor-settings.component.html
  projects/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  projects/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.scss
  projects/safe/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.component.html
  projects/safe/src/lib/components/widgets/grid-settings/tab-main/tab-main.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlet-division/map-clorophlet-division.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlet/map-clorophlet.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-marker-rule/map-marker-rule.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-markers/map-markers.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-markers/map-markers.component.scss
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.scss
  projects/safe/src/lib/pages/profile/profile.component.html
  projects/safe/src/lib/style/styles.scss
Labels: refactor

#987 fix: sort items by display name on RefDataService
  projects/safe/src/lib/services/reference-data/reference-data.service.ts
Labels: bug

#998 Feat 1.3.0/oort 498 reorganize add page and add step
  projects/back-office/src/app/application/pages/add-page/add-page.component.html
  projects/back-office/src/app/application/pages/add-page/add-page.module.ts
  projects/back-office/src/app/application/pages/workflow/components/add-step/add-step.component.html
  projects/back-office/src/app/application/pages/workflow/components/add-step/add-step.module.ts
Labels: enhancement

#999 replace class="info-text" by safe-alerte
  projects/safe/src/lib/components/query-builder/query-builder.module.ts
  projects/safe/src/lib/components/query-builder/tab-fields/tab-fields.component.html
  projects/safe/src/lib/components/query-builder/tab-layout-preview/tab-layout-preview.component.html
  projects/safe/src/lib/components/query-builder/tab-style/tab-style.component.html
  projects/safe/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.component.html
  projects/safe/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.module.ts
  projects/safe/src/lib/style/styles.scss
Labels: refactor

#1010 Feat 1.3.0/ab#47339 readable cron front end
  package-lock.json
  package.json
  projects/back-office/src/app/dashboard/pages/pull-jobs/components/pull-job-modal/pull-job-modal.component.html
  projects/back-office/src/app/dashboard/pages/pull-jobs/components/pull-job-modal/pull-job-modal.component.ts
  projects/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.module.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/pipes/readable-cron/public-api.ts
  projects/safe/src/lib/pipes/readable-cron/readable-cron.module.ts
  projects/safe/src/lib/pipes/readable-cron/readable-cron.pipe.spec.ts
  projects/safe/src/lib/pipes/readable-cron/readable-cron.pipe.ts
  projects/safe/src/lib/safe.module.ts
  projects/safe/src/lib/utils/validators/cron.validator.ts
  projects/safe/src/public-api.ts
Labels: enhancement

#1011 OORT-527
  projects/safe/src/lib/components/filter/filter-row/filter-row.component.ts
  projects/safe/src/lib/components/query-builder/tab-filter/tab-filter.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlet/map-clorophlet.component.scss
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-markers/map-markers.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
  projects/safe/src/lib/services/query-builder/query-builder.service.ts
Labels: bug, refactor
