Repository ReliefApplications/ems-frontend, pull requests merged in 2022-12, with the labels that each got.

#1014 feat-1.3.0/OORT-513_rotate_long_labels
  projects/safe/src/lib/components/ui/bar-chart/bar-chart.component.ts
  projects/safe/src/lib/components/ui/line-chart/line-chart.component.ts
Labels: enhancement

#1018 refactor: better indicate status of grid widget
  package-lock.json
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.html
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.html
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
  projects/safe/src/lib/services/application/application.service.ts
Labels: enhancement

#1023 fix/OORT-525_add-list-and-template-from-settings
  projects/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  projects/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
  projects/safe/src/lib/services/application/application.service.ts
Labels: enhancement

#1022 fix/OORT-494_vertical-mat-tab-responsiveness
  projects/safe/src/lib/components/preferences-modal/preferences-modal.component.html
  projects/safe/src/lib/components/widgets/chart-settings/chart-settings.component.html
  projects/safe/src/lib/components/widgets/chart-settings/chart-settings.module.ts
  projects/safe/src/lib/components/widgets/grid-settings/grid-settings.component.html
  projects/safe/src/lib/components/widgets/grid-settings/grid-settings.module.ts
  projects/safe/src/lib/components/widgets/map-settings/map-settings.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-settings.module.ts
  projects/safe/src/lib/style/styles.scss
Labels: enhancement

#1032 fix/OORT-539_icon-margin-bug
  projects/safe/src/lib/components/ui/icon/icon.component.html
  projects/safe/src/lib/components/ui/icon/icon.component.scss
Labels: bug

#1028 refactor/OORT-540_replace-inline-styles
  projects/back-office/src/app/application/pages/channels/channels.component.html
  projects/back-office/src/app/application/pages/subscriptions/subscriptions.component.html
  projects/back-office/src/app/components/duplicate-application-modal/duplicate-application-modal.component.html
  projects/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.html
  projects/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.scss
  projects/back-office/src/app/dashboard/pages/applications/applications.component.html
  projects/back-office/src/app/dashboard/pages/form-records/form-records.component.html
  projects/back-office/src/app/dashboard/pages/forms/forms.component.html
  projects/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.html
  projects/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  projects/back-office/src/app/dashboard/pages/reference-data/reference-data.component.scss
  projects/safe/src/lib/components/applications-summary/components/application-summary/application-summary.component.html
  projects/safe/src/lib/components/choose-record-modal/choose-record-modal.component.html
  projects/safe/src/lib/components/convert-modal/convert-modal.component.html
  projects/safe/src/lib/components/layout/layout.component.html
  projects/safe/src/lib/components/left-sidenav/left-sidenav.component.html
  projects/safe/src/lib/components/query-builder/tab-fields/tab-fields.component.html
  projects/safe/src/lib/components/query-builder/tab-layout-preview/tab-layout-preview.component.html
  projects/safe/src/lib/components/record-history/record-history.component.html
  projects/safe/src/lib/components/role-summary/role-auto-assignment/role-auto-assignment.component.html
  projects/safe/src/lib/components/role-summary/role-features/role-workflows/role-workflows.component.html
  projects/safe/src/lib/components/role-summary/role-resources/resource-access-filters/resource-access-filters.component.html
  projects/safe/src/lib/components/role-summary/role-resources/resource-fields/resource-fields.component.html
  projects/safe/src/lib/components/role-summary/role-resources/role-resources.component.html
  projects/safe/src/lib/components/roles/components/group-list/group-list.component.html
  projects/safe/src/lib/components/roles/components/role-list/role-list.component.html
  projects/safe/src/lib/components/search-menu/search-menu.component.html
  projects/safe/src/lib/components/search-resource-grid-modal/search-resource-grid-modal.component.html
  projects/safe/src/lib/components/skeleton/skeleton-table/skeleton-table.component.html
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  projects/safe/src/lib/components/ui/core-grid/row-actions/row-actions.component.html
  projects/safe/src/lib/components/user-summary/user-details/user-details.component.html
  projects/safe/src/lib/components/users/components/invite-users/invite-users.component.html
  projects/safe/src/lib/components/widget-grid/floating-options/floating-options.component.html
  projects/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlet/map-clorophlet.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-markers/map-markers.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-online-layers/map-online-layers.component.html
  projects/safe/src/lib/components/workflow-stepper/workflow-stepper.component.html
  projects/web-widgets/src/app/widgets/application-widget/application-widget.component.html
  projects/web-widgets/src/index.html
  tailwind.config.js
Labels: refactor

#1037 fix/OORT-546_map-legend-overflow
  projects/safe/src/lib/components/widgets/map/map.component.ts
  projects/safe/src/lib/style/styles.scss
Labels: bug

#1030 fix/OORT-531_linked-fileds-as-coords
  projects/safe/src/lib/components/choose-record-modal/choose-record-modal.component.ts
  projects/safe/src/lib/components/query-builder/query-builder.component.ts
  projects/safe/src/lib/components/query-builder/tab-fields/tab-fields.component.html
  projects/safe/src/lib/components/query-builder/tab-filter/tab-filter.component.ts
  projects/safe/src/lib/components/query-builder/tab-style/query-style/query-style.component.html
  projects/safe/src/lib/components/query-builder/tab-style/query-style/query-style.component.ts
  projects/safe/src/lib/components/role-summary/role-resources/role-resources.component.ts
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.ts
  projects/safe/src/lib/components/widgets/map-settings/graphql/queries.ts
  projects/safe/src/lib/components/widgets/map-settings/map-forms.ts
  projects/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-general/map-general.module.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlet/map-clorophlet.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlets/map-clorophlets.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-markers/map-markers.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-settings.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
  projects/safe/src/lib/components/widgets/map/map.component.ts
  projects/safe/src/lib/services/query-builder/query-builder.service.ts
Labels: enhancement

#1040 refactor/OORT-553_search-on-graphql-select
  package.json
  projects/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.html
  projects/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.ts
  projects/back-office/src/app/application/pages/subscriptions/graphql/queries.ts
  projects/back-office/src/app/components/add-form-modal/add-form-modal.component.html
  projects/back-office/src/app/components/add-form-modal/add-form-modal.component.ts
  projects/back-office/src/app/components/add-form-modal/graphql/queries.ts
  projects/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  projects/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.ts
  projects/back-office/src/app/dashboard/pages/pull-jobs/graphql/queries.ts
  projects/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  projects/safe/src/lib/components/graphql-select/graphql-select.component.html
  projects/safe/src/lib/components/graphql-select/graphql-select.component.ts
  projects/safe/src/lib/components/graphql-select/graphql-select.module.ts
  projects/safe/src/lib/components/resource-dropdown/graphql/queries.ts
  projects/safe/src/lib/components/resource-dropdown/resource-dropdown.component.html
  projects/safe/src/lib/components/resource-dropdown/resource-dropdown.component.ts
  projects/safe/src/lib/components/user-summary/graphql/queries.ts
  projects/safe/src/lib/components/user-summary/user-roles/user-app-roles/user-app-roles.component.html
  projects/safe/src/lib/components/user-summary/user-roles/user-app-roles/user-app-roles.component.ts
  projects/safe/src/lib/components/widgets/chart-settings/graphql/queries.ts
  projects/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.html
  projects/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/graphql/queries.ts
  projects/safe/src/lib/components/widgets/grid-settings/tab-main/tab-main.component.html
  projects/safe/src/lib/components/widgets/grid-settings/tab-main/tab-main.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/graphql/queries.ts
Labels: enhancement, refactor

#1041 Fix 1.3.x/AB#22069 multilevel dropdown on tagbox
  projects/safe/src/lib/components/reference-data-dropdown/reference-data-dropdown.component.html
  projects/safe/src/lib/services/reference-data/reference-data.service.ts
  projects/safe/src/lib/survey/global-properties/reference-data.ts
Labels: bug, enhancement

#1044 Fix/oort 557 metadata infinite loop
  projects/safe/src/lib/components/query-builder/query-builder-forms.ts
  projects/safe/src/lib/components/query-builder/query-builder.component.ts
  projects/safe/src/lib/components/resource-dropdown/resource-dropdown.component.html
  projects/safe/src/lib/components/resource-dropdown/resource-dropdown.component.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
  projects/safe/src/lib/components/widgets/map-settings/graphql/queries.ts
  projects/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-settings.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
Labels: bug

#1045 style: use display with button, to fix some ui issues + simplify form…
  projects/back-office/src/app/application/pages/form/form.component.html
  projects/back-office/src/app/dashboard/pages/form-answer/form-answer.component.html
  projects/safe/src/lib/components/form/form.component.html
  projects/safe/src/lib/components/form/form.component.scss
  projects/safe/src/lib/components/ui/button/button.component.scss
Labels: bug

#1047 fix/OORT-555_remove-irrelevant-elements-graphqlselect
  projects/safe/src/lib/components/graphql-select/graphql-select.component.html
  projects/safe/src/lib/components/graphql-select/graphql-select.component.ts
Labels: bug
