Repository ReliefApplications/ems-frontend, pull requests merged in 2022-09, with the labels that each got.

#920 feat-1.3.0/AB#39347: Allow to filter multiselect refData
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.html
Labels: enhancement

#921 OORT-432 Default language selection fix for surveys
  package-lock.json
  projects/safe/src/lib/components/form-builder/form-builder.component.ts
Labels: hotfix

#927 add searchbar and autoscroll to summary card settings
  projects/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/add-card/add-card.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/add-card/add-card.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/add-card/add-card.module.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.ts
Labels: enhancement

#930 feat-1.3.0/OORT-437_empty-state-component
  projects/safe/src/lib/components/record-history/record-history.component.html
  projects/safe/src/lib/components/record-history/record-history.component.scss
  projects/safe/src/lib/components/record-history/record-history.module.ts
  projects/safe/src/lib/components/role-summary/role-features/role-features.component.html
  projects/safe/src/lib/components/role-summary/role-features/role-features.component.scss
  projects/safe/src/lib/components/role-summary/role-features/role-features.module.ts
  projects/safe/src/lib/components/role-summary/role-features/role-workflows/role-workflows.component.html
  projects/safe/src/lib/components/role-summary/role-features/role-workflows/role-workflows.component.scss
  projects/safe/src/lib/components/role-summary/role-resources/role-resources.component.scss
  projects/safe/src/lib/components/ui/aggregation-builder/series-mapping/series-mapping.stories.ts
  projects/safe/src/lib/components/ui/empty/empty.component.html
  projects/safe/src/lib/components/ui/empty/empty.component.scss
  projects/safe/src/lib/components/ui/empty/empty.component.spec.ts
  projects/safe/src/lib/components/ui/empty/empty.component.ts
  projects/safe/src/lib/components/ui/empty/empty.module.ts
  projects/safe/src/lib/components/ui/empty/empty.stories.ts
  projects/safe/src/lib/components/ui/empty/public-api.ts
  projects/safe/src/lib/safe.module.ts
  projects/safe/src/public-api.ts
Labels: enhancement

#931 Fix 1.3.0/oort 440 auto modify action not working
  projects/safe/src/lib/components/ui/aggregation-builder/series-mapping/series-mapping.stories.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
Labels: bug

#928 merge of dynamic cards code
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card.component.html
  projects/safe/src/lib/components/widgets/summary-card/summary-card.component.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card.module.ts
Labels: enhancement, refactor

#934 Feat 1.3.0/oort 446 hide some parts of help of tinymce
  projects/safe/src/lib/const/tinymce.const.ts
Labels: enhancement

#940 OORT-449 Vertical tabs for summary card settings
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.html
Labels: enhancement

#937 feat-1.4.0/AB#34852_aggregations-in-summary-cards
  projects/safe/src/lib/components/aggregation/add-aggregation-modal/add-aggregation-modal.component.html
  projects/safe/src/lib/components/aggregation/add-aggregation-modal/add-aggregation-modal.component.ts
  projects/safe/src/lib/components/aggregation/aggregation-table/aggregation-table.component.ts
  projects/safe/src/lib/components/grid-layout/layout-table/layout-table.component.ts
  projects/safe/src/lib/components/ui/aggregation-builder/aggregation-builder-forms.ts
  projects/safe/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  projects/safe/src/lib/components/ui/aggregation-builder/pipeline/field-dropdown/field-dropdown.component.html
  projects/safe/src/lib/components/widgets/chart-settings/graphql/queries.ts
  projects/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.ts
  projects/safe/src/lib/components/widgets/chart/chart.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/graphql/queries.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  projects/safe/src/lib/components/widgets/summary-card/parser/utils.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.html
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card.component.ts
  projects/safe/src/lib/services/aggregation-builder.service.ts
  projects/safe/src/lib/services/query-builder.service.ts
Labels: enhancement, refactor

#941 Feat 1.3.0/oort 393 allow customization of chart title
  projects/back-office/src/environments/environment.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/ui/bar-chart/bar-chart.component.html
  projects/safe/src/lib/components/ui/bar-chart/bar-chart.component.ts
  projects/safe/src/lib/components/ui/column-chart/column-chart.component.html
  projects/safe/src/lib/components/ui/column-chart/column-chart.component.ts
  projects/safe/src/lib/components/ui/donut-chart/donut-chart.component.html
  projects/safe/src/lib/components/ui/donut-chart/donut-chart.component.ts
  projects/safe/src/lib/components/ui/line-chart/line-chart.component.html
  projects/safe/src/lib/components/ui/line-chart/line-chart.component.ts
  projects/safe/src/lib/components/ui/pie-chart/pie-chart.component.html
  projects/safe/src/lib/components/ui/pie-chart/pie-chart.component.ts
  projects/safe/src/lib/components/widgets/chart-settings/charts/chart.ts
  projects/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.html
  projects/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.scss
  projects/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.ts
  projects/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.module.ts
Labels: enhancement

#944 Feat 1.3.0/AB#41343 File names in grid
  projects/safe/src/lib/components/filter/filter-row/filter-row.component.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.scss
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.constants.ts
Labels: enhancement

#945 Fix 1.3.0/oort 455 page permissions view not updated
  projects/back-office/src/app/application/pages/form/form.component.ts
Labels: enhancement

#946 AB#29362 Remove default style rule
  projects/safe/src/lib/components/query-builder/query-builder-forms.ts
Labels: enhancement, hotfix

#949 AB#41417 Format layout field display is now possible
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/query-builder/query-builder-forms.ts
  projects/safe/src/lib/components/query-builder/query-builder.module.ts
  projects/safe/src/lib/components/query-builder/tab-fields/tab-fields.component.html
  projects/safe/src/lib/components/query-builder/tab-fields/tab-fields.component.ts
  projects/safe/src/lib/components/role-summary/role-details/role-details.component.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
  projects/safe/src/lib/components/widgets/summary-card/parser/utils.ts
  projects/safe/src/lib/const/tinymce.const.ts
  projects/safe/src/lib/services/form-builder.service.ts
  projects/safe/src/lib/services/grid.service.ts
Labels: enhancement

#947 fix: correct error message when the choosen record doesn't exist and …
  projects/front-office/src/app/app.module.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.html
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.scss
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.module.ts
  projects/safe/src/lib/components/widget-grid/widget-grid.component.html
  projects/safe/src/lib/components/widget/widget.component.html
  projects/safe/src/lib/components/widget/widget.component.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.html
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
  projects/web-widgets/src/app/app.module.ts
Labels: enhancement

#952 Refactor 1.3.0/ab#41791 add editor service
  projects/safe/src/lib/components/email-preview/email-preview.component.ts
  projects/safe/src/lib/components/widgets/editor-settings/editor-settings.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
  projects/safe/src/lib/const/tinymce.const.ts
  projects/safe/src/lib/services/editor/editor.service.spec.ts
  projects/safe/src/lib/services/editor/editor.service.ts
Labels: refactor
