Repository ReliefApplications/ems-frontend, pull requests merged in 2023-05, with the labels that each got.

#1295 feat/AB#61955_ABC-implement-flyout-menu-component
  libs/ui/src/index.ts
  libs/ui/src/lib/flyout-menu/flyout-menu.component.html
  libs/ui/src/lib/flyout-menu/flyout-menu.component.scss
  libs/ui/src/lib/flyout-menu/flyout-menu.component.stories.ts
  libs/ui/src/lib/flyout-menu/flyout-menu.component.ts
  libs/ui/src/lib/flyout-menu/flyout-menu.module.ts
  libs/ui/src/lib/flyout-menu/interfaces/flyout-menu.interfaces.ts
  libs/ui/src/lib/menu/menu.component.html
  libs/ui/src/lib/menu/menu.component.spec.ts
  libs/ui/src/lib/menu/menu.component.stories.ts
  libs/ui/src/lib/menu/menu.component.ts
  libs/ui/src/lib/menu/menu.directive.ts
  libs/ui/src/lib/menu/menu.module.ts
  libs/ui/src/style/styles.scss
Labels: enhancement, tailwind

#1289 feat/AB#55629_popup
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/geofields-listbox/geofields-listbox.component.ts
  libs/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  libs/safe/src/lib/components/geospatial-map/geospatial-map.interface.ts
  libs/safe/src/lib/components/ui/core-grid/map-modal/map-modal.component.ts
  libs/safe/src/lib/components/ui/map/layer.ts
  libs/safe/src/lib/components/ui/map/map-popup/map-popup.component.html
  libs/safe/src/lib/components/ui/map/map-popup/map-popup.component.scss
  libs/safe/src/lib/components/ui/map/map-popup/map-popup.component.spec.ts
  libs/safe/src/lib/components/ui/map/map-popup/map-popup.component.ts
  libs/safe/src/lib/components/ui/map/map-popup/map-popup.service.ts
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/components/ui/map/map.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-forms.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/fields-element/fields-element.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/fields-element/fields-element.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/layer-popup.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/text-element/text-element.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.ts
  libs/safe/src/lib/services/map/graphql/queries.ts
  libs/safe/src/lib/services/map/map-layers.service.ts
  libs/safe/src/lib/style/map.scss
Labels: enhancement

#1269 Feat/ab#61946 implement button component
  libs/ui/src/index.ts
  libs/ui/src/lib/avatar-group/avatar-group.component.stories.ts
  libs/ui/src/lib/avatar-group/avatar-group.component.ts
  libs/ui/src/lib/avatar/avatar.component.stories.ts
  libs/ui/src/lib/avatar/avatar.component.ts
  libs/ui/src/lib/avatar/enums/avatar-size.enum.ts
  libs/ui/src/lib/button/button.component.html
  libs/ui/src/lib/button/button.component.scss
  libs/ui/src/lib/button/button.component.stories.ts
  libs/ui/src/lib/button/button.component.ts
  libs/ui/src/lib/button/button.module.ts
  libs/ui/src/lib/icon/enums/icon-variant.enum.ts
  libs/ui/src/lib/spinner/spinner.component.html
  libs/ui/src/lib/spinner/spinner.component.scss
  libs/ui/src/lib/spinner/spinner.component.spec.ts
  libs/ui/src/lib/spinner/spinner.component.stories.ts
  libs/ui/src/lib/spinner/spinner.component.ts
  libs/ui/src/lib/spinner/spinner.module.ts
  libs/ui/src/lib/ui.module.ts
  libs/ui/src/style/styles.scss
Labels: enhancement, tailwind

#1281 feat/AB#62224-implement-checkbox
  libs/ui/src/lib/checkbox/checkbox.component.html
  libs/ui/src/lib/checkbox/checkbox.component.scss
  libs/ui/src/lib/checkbox/checkbox.component.spec.ts
  libs/ui/src/lib/checkbox/checkbox.component.stories.ts
  libs/ui/src/lib/checkbox/checkbox.component.ts
  libs/ui/src/lib/checkbox/checkbox.module.ts
  libs/ui/src/lib/icon/icon.component.html
  libs/ui/src/lib/icon/icon.component.stories.ts
  package-lock.json
  package.json
  tailwind.config.js
Labels: enhancement, tailwind

#1283 feat/AB#62233_implement_radio_component
  libs/ui/src/index.ts
  libs/ui/src/lib/radio/radio-group.directive.ts
  libs/ui/src/lib/radio/radio.component.html
  libs/ui/src/lib/radio/radio.component.scss
  libs/ui/src/lib/radio/radio.component.spec.ts
  libs/ui/src/lib/radio/radio.component.stories.ts
  libs/ui/src/lib/radio/radio.component.ts
  libs/ui/src/lib/radio/radio.module.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind

#1282 feat/AB#62239_implement_textarea_component
  libs/ui/src/index.ts
  libs/ui/src/lib/textarea/textarea.component.html
  libs/ui/src/lib/textarea/textarea.component.scss
  libs/ui/src/lib/textarea/textarea.component.spec.ts
  libs/ui/src/lib/textarea/textarea.component.stories.ts
  libs/ui/src/lib/textarea/textarea.component.ts
  libs/ui/src/lib/textarea/textarea.module.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind

#1279 Feat/ab#62196 abc implement tooltip component
  libs/ui/src/index.ts
  libs/ui/src/lib/tooltip/enums/tooltip-example-positions.enum.ts
  libs/ui/src/lib/tooltip/tooltip.component.html
  libs/ui/src/lib/tooltip/tooltip.component.stories.ts
  libs/ui/src/lib/tooltip/tooltip.component.ts
  libs/ui/src/lib/tooltip/tooltip.directive.ts
  libs/ui/src/lib/tooltip/tooltip.module.ts
  libs/ui/src/lib/ui.module.ts
  package-lock.json
  package.json
Labels: enhancement, tailwind

#1300 fix/removing-unnecessary-span
  libs/safe/src/lib/components/widgets/summary-card/parser/utils.ts
Labels: enhancement

#1299 feat/AB#59610_borderless-widget
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.scss
  libs/safe/src/lib/components/widget-grid/widget-grid.component.html
  libs/safe/src/lib/components/widget-grid/widget-grid.component.ts
  libs/safe/src/lib/components/widgets/chart-settings/chart-settings.component.html
  libs/safe/src/lib/components/widgets/chart-settings/chart-settings.component.ts
  libs/safe/src/lib/components/widgets/chart-settings/chart-settings.module.ts
  libs/safe/src/lib/components/widgets/common/display-settings/display-settings.component.html
  libs/safe/src/lib/components/widgets/common/display-settings/display-settings.component.scss
  libs/safe/src/lib/components/widgets/common/display-settings/display-settings.component.spec.ts
  libs/safe/src/lib/components/widgets/common/display-settings/display-settings.component.ts
  libs/safe/src/lib/components/widgets/common/display-settings/extendWidgetForm.ts
  libs/safe/src/lib/components/widgets/editor-settings/editor-settings.component.html
  libs/safe/src/lib/components/widgets/editor-settings/editor-settings.component.ts
  libs/safe/src/lib/components/widgets/editor-settings/editor-settings.module.ts
  libs/safe/src/lib/components/widgets/grid-settings/grid-settings.component.html
  libs/safe/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  libs/safe/src/lib/components/widgets/grid-settings/grid-settings.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-settings.module.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.scss
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.spec.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.scss
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.module.ts
  libs/safe/src/lib/style/styles.scss
  libs/ui/src/style/styles.scss
Labels: enhancement

#1297 feat/AB#62237_implement_expansion_panel
  libs/ui/src/index.ts
  libs/ui/src/lib/expansion-panel/expansion-panel.component.html
  libs/ui/src/lib/expansion-panel/expansion-panel.component.scss
  libs/ui/src/lib/expansion-panel/expansion-panel.component.spec.ts
  libs/ui/src/lib/expansion-panel/expansion-panel.component.stories.ts
  libs/ui/src/lib/expansion-panel/expansion-panel.component.ts
  libs/ui/src/lib/expansion-panel/expansion-panel.module.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind

#1316 feat/add-substr-calculation
  libs/safe/src/lib/components/edit-calculated-field-modal/utils/keys.ts
Labels: enhancement

#1325 GIS map: layers fixes
  libs/safe/src/lib/components/widgets/map-settings/map-forms.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-styling/simple-renderer/simple-renderer.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-styling/simple-renderer/simple-renderer.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.html
Labels: bug

#1330 GIS map: set datasource as required
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-datasource/layer-datasource.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.ts
Labels: enhancement

#1336 Feat/ab#63661_abc-implement-form-wrapper-directive
  libs/ui/src/index.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.component.stories.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.module.ts
  libs/ui/src/lib/form-wrapper/prefix.directive.ts
  libs/ui/src/lib/form-wrapper/suffix.directive.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind

#1347 feat/add-listRowsWithColValue-custom-function
  libs/safe/src/lib/survey/global-properties/others.ts
  libs/safe/src/lib/survey/widgets/text-widget.ts
  libs/safe/src/lib/utils/custom-functions.ts
Labels: enhancement

#1323 feat/AB#63181-replace-toggle
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.html
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.ts
  libs/safe/src/lib/components/ui/core-grid/export/export.component.html
  libs/safe/src/lib/components/ui/core-grid/export/export.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/chart-settings.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/categories-settings/categories-settings.component.html
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/categories-settings/categories-settings.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/series-settings.component.html
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/series-settings.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.html
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.scss
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.module.ts
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.module.ts
  libs/safe/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.html
  libs/safe/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.module.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/card-modal/display-tab/display-tab.component.html
  libs/safe/src/lib/components/widgets/summary-card-settings/card-modal/display-tab/display.module.ts
  libs/safe/src/lib/style/styles.scss
  libs/ui/src/index.ts
  libs/ui/src/lib/toggle/interfaces/toggle-label.interface.ts
  libs/ui/src/lib/toggle/toggle.component.html
  libs/ui/src/lib/toggle/toggle.component.stories.ts
  libs/ui/src/lib/toggle/toggle.component.ts
Labels: enhancement, tailwind

#1322 feat/AB#63173-replace-checkbox
  libs/safe/src/lib/components/checkbox-tree/checkbox-tree.component.html
  libs/safe/src/lib/components/checkbox-tree/checkbox-tree.module.ts
  libs/safe/src/lib/components/skeleton/skeleton-table/skeleton-table.component.html
  libs/safe/src/lib/components/skeleton/skeleton-table/skeleton-table.module.ts
  libs/safe/src/lib/components/users/users.component.html
  libs/safe/src/lib/components/users/users.module.ts
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.scss
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.module.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.html
  libs/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source.module.ts
  libs/safe/src/lib/style/styles.scss
  libs/safe/src/lib/views/application-users/components/user-list/user-list.component.html
  libs/safe/src/lib/views/application-users/components/user-list/user-list.module.ts
  libs/ui/src/lib/checkbox/checkbox.component.html
  libs/ui/src/lib/checkbox/checkbox.component.ts
Labels: enhancement, tailwind

#1318 feat/AB#63177_replace_radio
  apps/back-office/src/app/application/pages/add-page/add-page.module.ts
  apps/back-office/src/app/application/pages/workflow/components/add-step/add-step.module.ts
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.html
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.ts
  libs/safe/src/lib/components/convert-modal/convert-modal.component.html
  libs/safe/src/lib/components/convert-modal/convert-modal.component.ts
  libs/safe/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.html
  libs/safe/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.ts
  libs/safe/src/lib/components/query-builder/query-builder.module.ts
  libs/safe/src/lib/components/query-builder/tab-style/query-style/query-style.component.html
  libs/safe/src/lib/components/query-builder/tab-style/query-style/query-style.component.scss
  libs/safe/src/lib/components/ui/core-grid/export/export.component.html
  libs/safe/src/lib/components/ui/core-grid/export/export.component.scss
  libs/safe/src/lib/components/ui/core-grid/export/export.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/chart-settings.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.module.ts
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.scss
  libs/safe/src/lib/components/widgets/scheduler-settings/scheduler-settings.component.html
  libs/safe/src/lib/components/widgets/scheduler-settings/scheduler-settings.module.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/add-card/add-card.component.html
  libs/safe/src/lib/components/widgets/summary-card-settings/add-card/add-card.component.scss
  libs/safe/src/lib/components/widgets/summary-card-settings/add-card/add-card.module.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.html
  libs/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.scss
  libs/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source.module.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.scss
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.module.ts
  libs/ui/src/lib/radio/radio-group.directive.ts
  libs/ui/src/lib/radio/radio.component.html
  libs/ui/src/lib/radio/radio.component.ts
  libs/ui/src/lib/tooltip/tooltip.component.ts
Labels: enhancement, tailwind

#1321 refactor/AB#63178_ABC-Implement-UI-Avatar-Component
  libs/safe/src/lib/components/ui/avatar/avatar-size.enum.ts
  libs/safe/src/lib/components/ui/avatar/avatar-variant.enum.ts
  libs/safe/src/lib/components/ui/avatar/avatar.component.html
  libs/safe/src/lib/components/ui/avatar/avatar.component.scss
  libs/safe/src/lib/components/ui/avatar/avatar.component.spec.ts
  libs/safe/src/lib/components/ui/avatar/avatar.component.ts
  libs/safe/src/lib/components/ui/avatar/avatar.module.ts
  libs/safe/src/lib/components/ui/avatar/avatar.stories.ts
Labels: enhancement, tailwind

#1303 feat/AB#62739_implement_dialog_component
  libs/ui/src/index.ts
  libs/ui/src/lib/dialog/dialog-close.directive.ts
  libs/ui/src/lib/dialog/dialog.component.html
  libs/ui/src/lib/dialog/dialog.component.scss
  libs/ui/src/lib/dialog/dialog.component.spec.ts
  libs/ui/src/lib/dialog/dialog.component.stories.ts
  libs/ui/src/lib/dialog/dialog.component.ts
  libs/ui/src/lib/dialog/dialog.module.ts
  libs/ui/src/lib/dialog/enums/dialog-size.enum.ts
  libs/ui/src/lib/menu/menu.component.stories.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind

#1342 refactor/AB#63565_ABC-replace-mat-list-tags
  libs/safe/src/lib/components/application-toolbar/application-toolbar.module.ts
  libs/safe/src/lib/components/convert-modal/convert-modal.component.ts
  libs/safe/src/lib/components/layout/layout.module.ts
  libs/safe/src/lib/components/left-sidenav/left-sidenav.component.html
  libs/safe/src/lib/components/left-sidenav/left-sidenav.component.scss
  libs/safe/src/lib/components/left-sidenav/left-sidenav.module.ts
  libs/safe/src/lib/style/styles.scss
Labels: enhancement, tailwind

#1360 AB#57973 : Fix placement of tooltips
  projects/safe/src/lib/survey/global-properties/tooltip.ts
Labels: bug

#1361 feat: add snackbar when CUD for distribution lists, notification temp…
  libs/safe/src/lib/components/distribution-lists/distribution-lists.component.ts
  libs/safe/src/lib/components/notifications/notifications.component.ts
  libs/safe/src/lib/components/templates/templates.component.ts
Labels: enhancement

#1356 Refactor/abc-improve-form-wrapper-directive
  libs/ui/src/lib/form-wrapper/form-wrapper.component.stories.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/lib/select-menu/select-menu.component.html
Labels: enhancement, tailwind

#1317 feat/AB#63158-replace-breadcrumb
  libs/safe/src/lib/components/layout/layout.component.html
  libs/safe/src/lib/components/layout/layout.component.ts
  libs/safe/src/lib/components/layout/layout.module.ts
  libs/safe/src/lib/components/ui/breadcrumb/breadcrumb.component.html
  libs/safe/src/lib/components/ui/breadcrumb/breadcrumb.component.scss
  libs/safe/src/lib/components/ui/breadcrumb/breadcrumb.component.spec.ts
  libs/safe/src/lib/components/ui/breadcrumb/breadcrumb.component.ts
  libs/safe/src/lib/components/ui/breadcrumb/breadcrumb.module.ts
  libs/safe/src/lib/components/ui/breadcrumb/breadcrumb.stories.ts
  libs/safe/src/lib/services/breadcrumb/breadcrumb.service.ts
  libs/ui/src/lib/breadcrumbs/breadcrumbs.component.html
  libs/ui/src/lib/breadcrumbs/breadcrumbs.component.ts
  libs/ui/src/lib/breadcrumbs/breadcrumbs.module.ts
Labels: enhancement, tailwind

#1357 feat/AB#64087-replace-expansion-panel
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.ts
  libs/safe/src/lib/components/record-history/record-history.component.html
  libs/safe/src/lib/components/record-history/record-history.component.scss
  libs/safe/src/lib/components/record-history/record-history.module.ts
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.html
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.scss
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/pipeline.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/chart-settings.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.html
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.module.ts
  libs/safe/src/lib/style/styles.scss
  libs/ui/src/lib/expansion-panel/expansion-panel.component.html
  libs/ui/src/lib/expansion-panel/expansion-panel.component.stories.ts
  libs/ui/src/lib/expansion-panel/expansion-panel.component.ts
  libs/ui/src/lib/expansion-panel/expansion-panel.module.ts
Labels: enhancement, tailwind

#1364 feat/AB#64180-replace-tab-navigation
  apps/back-office/src/app/app.module.ts
  apps/back-office/src/app/dashboard/pages/resource/resource.component.html
  apps/back-office/src/app/dashboard/pages/resource/resource.module.ts
  libs/safe/src/lib/components/form-modal/form-modal.component.html
  libs/safe/src/lib/components/form-modal/form-modal.component.ts
  libs/safe/src/lib/components/form/form.component.html
  libs/safe/src/lib/components/form/form.module.ts
  libs/safe/src/lib/components/preferences-modal/preferences-modal.component.html
  libs/safe/src/lib/components/preferences-modal/preferences-modal.component.ts
  libs/safe/src/lib/components/query-builder/query-builder.component.html
  libs/safe/src/lib/components/query-builder/query-builder.module.ts
  libs/safe/src/lib/components/record-modal/record-modal.component.html
  libs/safe/src/lib/components/record-modal/record-modal.component.ts
  libs/safe/src/lib/components/role-summary/role-details/role-details.component.html
  libs/safe/src/lib/components/role-summary/role-details/role-details.module.ts
  libs/safe/src/lib/components/role-summary/role-summary.component.html
  libs/safe/src/lib/components/role-summary/role-summary.module.ts
  libs/safe/src/lib/components/roles/roles.component.html
  libs/safe/src/lib/components/roles/roles.module.ts
  libs/safe/src/lib/components/user-summary/user-summary.component.html
  libs/safe/src/lib/components/user-summary/user-summary.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/chart-settings.component.html
  libs/safe/src/lib/components/widgets/chart-settings/chart-settings.component.ts
  libs/safe/src/lib/components/widgets/chart-settings/chart-settings.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.module.ts
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.module.ts
  libs/safe/src/lib/components/widgets/grid-settings/grid-settings.component.html
  libs/safe/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  libs/safe/src/lib/components/widgets/grid-settings/grid-settings.module.ts
  libs/safe/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.component.html
  libs/safe/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-settings.module.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.html
  libs/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.ts
  libs/safe/src/lib/style/styles.scss
  libs/safe/src/lib/views/application-users/application-users.component.html
  libs/safe/src/lib/views/application-users/application-users.module.ts
  libs/ui/src/lib/tabs/components/tab/tab.component.html
  libs/ui/src/lib/tabs/components/tab/tab.component.scss
  libs/ui/src/lib/tabs/components/tab/tab.component.ts
  libs/ui/src/lib/tabs/tabs.component.stories.ts
  libs/ui/src/lib/tabs/tabs.component.ts
Labels: enhancement, tailwind

#1362 feat/AB#64088-replace-slider
  libs/safe/src/lib/components/query-builder/query-builder.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlet/map-clorophlet.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlet/map-clorophlet.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.module.ts
Labels: enhancement, tailwind

#1354 refactor/AB#63566_ABC-Replace-Mat-Toolbar-Component
  apps/back-office/src/themes/default/default.dev.ts
  apps/back-office/src/themes/default/default.local.ts
  apps/back-office/src/themes/default/default.prod.ts
  apps/back-office/src/themes/default/default.uat.ts
  apps/back-office/src/themes/oort/oort.dev.ts
  apps/back-office/src/themes/oort/oort.prod.ts
  apps/back-office/src/themes/oort/oort.uat.ts
  apps/front-office/src/themes/default/default.dev.ts
  apps/front-office/src/themes/default/default.local.ts
  apps/front-office/src/themes/default/default.prod.ts
  apps/front-office/src/themes/default/default.uat.ts
  apps/front-office/src/themes/oort/oort.dev.ts
  apps/front-office/src/themes/oort/oort.prod.ts
  apps/front-office/src/themes/oort/oort.uat.ts
  libs/safe/src/lib/components/layout/layout.component.html
  libs/safe/src/lib/components/layout/layout.component.ts
  libs/safe/src/lib/components/layout/layout.module.ts
Labels: enhancement, tailwind

#1308 feat/AB#63055-implement-chips
  libs/ui/src/index.ts
  libs/ui/src/lib/chip/chip-input.directive.ts
  libs/ui/src/lib/chip/chip-list.directive.ts
  libs/ui/src/lib/chip/chip.component.html
  libs/ui/src/lib/chip/chip.component.scss
  libs/ui/src/lib/chip/chip.component.spec.ts
  libs/ui/src/lib/chip/chip.component.stories.ts
  libs/ui/src/lib/chip/chip.component.ts
  libs/ui/src/lib/chip/chip.module.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind

#1294 feat/AB#62227 Implement Select Component
  .vscode/settings.json
  libs/ui/src/index.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.component.stories.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/lib/select-menu/components/select-option.component.html
  libs/ui/src/lib/select-menu/components/select-option.component.scss
  libs/ui/src/lib/select-menu/components/select-option.component.spec.ts
  libs/ui/src/lib/select-menu/components/select-option.component.ts
  libs/ui/src/lib/select-menu/components/select-option.module.ts
  libs/ui/src/lib/select-menu/select-menu.component.html
  libs/ui/src/lib/select-menu/select-menu.component.scss
  libs/ui/src/lib/select-menu/select-menu.component.spec.ts
  libs/ui/src/lib/select-menu/select-menu.component.stories.ts
  libs/ui/src/lib/select-menu/select-menu.component.ts
  libs/ui/src/lib/select-menu/select-menu.module.ts
  libs/ui/src/lib/select/select.component.html
  libs/ui/src/lib/select/select.component.stories.ts
  libs/ui/src/lib/select/select.component.ts
  libs/ui/src/lib/select/select.module.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind

#1365 feat/AB#64238_ABC-implement-snackbar-component
  libs/ui/src/index.ts
  libs/ui/src/lib/snackbar/interfaces/snackbar.interfaces.ts
  libs/ui/src/lib/snackbar/snackbar.component.html
  libs/ui/src/lib/snackbar/snackbar.component.scss
  libs/ui/src/lib/snackbar/snackbar.component.stories.ts
  libs/ui/src/lib/snackbar/snackbar.component.ts
  libs/ui/src/lib/snackbar/snackbar.module.ts
  libs/ui/src/lib/snackbar/snackbar.service.ts
  libs/ui/src/lib/snackbar/snackbar.token.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind

#1301 feat/AB#62737-implement-sidenav
  libs/safe/src/lib/components/widgets/chart/chart.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlet/map-clorophlet.component.ts
  libs/ui/src/index.ts
  libs/ui/src/lib/sidenav/sidenav-container.component.html
  libs/ui/src/lib/sidenav/sidenav-container.component.scss
  libs/ui/src/lib/sidenav/sidenav-container.component.spec.ts
  libs/ui/src/lib/sidenav/sidenav-container.component.ts
  libs/ui/src/lib/sidenav/sidenav-container.module.ts
  libs/ui/src/lib/sidenav/sidenav.component.stories.ts
  libs/ui/src/lib/sidenav/sidenav.directive.ts
  libs/ui/src/lib/sidenav/types/sidenavs.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind

#1371 Added navigation button for collapsing the left sidenav in fullscreen mode
  libs/safe/src/lib/components/layout/layout.component.html
Labels: fix

#1331 Feat/ab#63180 replace textarea
  apps/back-office/src/app/application/pages/settings/settings.component.html
  apps/back-office/src/app/application/pages/settings/settings.module.ts
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.module.ts
  libs/safe/src/lib/components/role-summary/role-details/role-details.component.html
  libs/safe/src/lib/components/role-summary/role-details/role-details.module.ts
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.html
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/pipeline.module.ts
  libs/safe/src/lib/components/ui/core-grid/expanded-comment/expanded-comment.component.html
  libs/safe/src/lib/components/ui/core-grid/expanded-comment/expanded-comment.module.ts
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.scss
  libs/safe/src/lib/components/ui/core-grid/grid/grid.module.ts
  libs/safe/src/lib/components/users/components/invite-users/invite-users.component.html
  libs/safe/src/lib/components/users/components/invite-users/invite-users.module.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/lib/textarea/textarea.component.html
  libs/ui/src/lib/textarea/textarea.component.stories.ts
  libs/ui/src/lib/textarea/textarea.component.ts
  libs/ui/src/lib/textarea/textarea.module.ts
Labels: enhancement, tailwind

#1324 fix/AB#63467_refData-from-graphql
  apps/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/graphql/queries.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.module.ts
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/services/api-proxy/api-proxy.service.ts
  libs/safe/src/lib/services/reference-data/reference-data.service.ts
  package-lock.json
  package.json
Labels: enhancement, fix

#1370 refactor/AB#64178_ABC-Replace-Sidenav-Component
  libs/safe/src/lib/components/layout/layout.component.html
  libs/safe/src/lib/components/layout/layout.component.scss
  libs/safe/src/lib/components/layout/layout.module.ts
  libs/safe/src/lib/components/left-sidenav/left-sidenav.component.html
  libs/safe/src/lib/components/left-sidenav/left-sidenav.module.ts
  libs/ui/src/lib/sidenav/sidenav-container.component.html
  libs/ui/src/lib/sidenav/sidenav-container.component.ts
  libs/ui/src/lib/sidenav/sidenav.component.stories.ts
  libs/ui/src/lib/sidenav/sidenav.directive.ts
  libs/ui/src/lib/sidenav/types/sidenavs.ts
Labels: enhancement, tailwind

#1383 refactor/AB#64948-refactor-safe-alert-component
  apps/back-office/src/app/application/pages/workflow/workflow.component.html
  apps/back-office/src/app/application/pages/workflow/workflow.module.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-datasource/context-datasource.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-datasource/context-datasource.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.module.ts
  libs/safe/src/index.ts
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.html
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.ts
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control.module.ts
  libs/safe/src/lib/components/query-builder/query-builder.module.ts
  libs/safe/src/lib/components/query-builder/tab-fields/tab-fields.component.html
  libs/safe/src/lib/components/query-builder/tab-layout-preview/tab-layout-preview.component.html
  libs/safe/src/lib/components/query-builder/tab-style/tab-style.component.html
  libs/safe/src/lib/components/ui/alert/alert-variant.enum.ts
  libs/safe/src/lib/components/ui/alert/alert.component.html
  libs/safe/src/lib/components/ui/alert/alert.component.scss
  libs/safe/src/lib/components/ui/alert/alert.component.ts
  libs/safe/src/lib/components/ui/alert/alert.module.ts
  libs/safe/src/lib/components/ui/alert/alert.stories.ts
  libs/safe/src/lib/components/ui/alert/public-api.ts
  libs/safe/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.component.html
  libs/safe/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-general/map-general.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlets/map-clorophlets.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlets/map-clorophlets.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-markers/map-markers.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-markers/map-markers.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-online-layers/map-online-layers.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-online-layers/map-online-layers.module.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/add-card/add-card.component.html
  libs/safe/src/lib/components/widgets/summary-card-settings/add-card/add-card.module.ts
  libs/safe/src/lib/style/styles.scss
  libs/ui/src/index.ts
  libs/ui/src/lib/alert/alert.component.html
  libs/ui/src/lib/alert/alert.component.scss
  libs/ui/src/lib/alert/alert.component.spec.ts
  libs/ui/src/lib/alert/alert.component.ts
  libs/ui/src/lib/alert/alert.module.ts
  libs/ui/src/lib/alert/alert.stories.ts
  libs/ui/src/lib/alert/types/alert-variant.ts
  libs/ui/src/lib/button/button.component.scss
  libs/ui/src/lib/dialog/dialog.component.html
  libs/ui/src/lib/icon/icon.component.scss
  libs/ui/src/lib/icon/icon.component.ts
  libs/ui/src/lib/ui.module.ts
  libs/ui/src/style/styles.scss
Labels: refactor, tailwind

#1388 feat/AB#64177-replace-mat-paginator
  apps/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.html
  apps/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.ts
  apps/back-office/src/app/dashboard/pages/api-configurations/api-configurations.module.ts
  apps/back-office/src/app/dashboard/pages/applications/applications.component.html
  apps/back-office/src/app/dashboard/pages/applications/applications.component.ts
  apps/back-office/src/app/dashboard/pages/applications/applications.module.ts
  apps/back-office/src/app/dashboard/pages/form-records/form-records.component.html
  apps/back-office/src/app/dashboard/pages/form-records/form-records.component.ts
  apps/back-office/src/app/dashboard/pages/form-records/form-records.module.ts
  apps/back-office/src/app/dashboard/pages/forms/forms.component.html
  apps/back-office/src/app/dashboard/pages/forms/forms.component.ts
  apps/back-office/src/app/dashboard/pages/forms/forms.module.ts
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.ts
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.module.ts
  apps/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.html
  apps/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.ts
  apps/back-office/src/app/dashboard/pages/reference-datas/reference-datas.module.ts
  apps/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.ts
  apps/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.module.ts
  apps/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.ts
  apps/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.module.ts
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.ts
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.module.ts
  apps/back-office/src/app/dashboard/pages/resource/resource.module.ts
  apps/back-office/src/app/dashboard/pages/resources/resources.component.html
  apps/back-office/src/app/dashboard/pages/resources/resources.component.ts
  apps/back-office/src/app/dashboard/pages/resources/resources.module.ts
  libs/safe/src/i18n/fr.json
  libs/safe/src/lib/components/notifications/notifications.component.html
  libs/safe/src/lib/components/notifications/notifications.component.ts
  libs/safe/src/lib/components/notifications/notifications.module.ts
  libs/safe/src/lib/components/role-summary/role-resources/role-resources.component.html
  libs/safe/src/lib/components/role-summary/role-resources/role-resources.component.ts
  libs/safe/src/lib/components/role-summary/role-resources/role-resources.module.ts
  libs/safe/src/lib/components/role-summary/role-users/role-users.component.html
  libs/safe/src/lib/components/role-summary/role-users/role-users.component.ts
  libs/safe/src/lib/components/role-summary/role-users/role-users.module.ts
  libs/safe/src/lib/components/skeleton/skeleton-table/skeleton-table.module.ts
  libs/safe/src/lib/services/paginator-translate.ts
  libs/safe/src/lib/views/application-users/components/user-list/user-list.component.html
  libs/safe/src/lib/views/application-users/components/user-list/user-list.component.ts
  libs/safe/src/lib/views/application-users/components/user-list/user-list.module.ts
  libs/ui/src/lib/paginator/paginator.component.html
  libs/ui/src/lib/paginator/paginator.component.scss
Labels: enhancement, tailwind

#1384 fix/AB#64928-fix-text-editor-available-resource-fields
  libs/safe/src/lib/components/widgets/editor-settings/graphql/queries.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/graphql/queries.ts
Labels: bug

#1391 refactor/AB#65073_ABC-Replace-Sidenav-Nav-Items
  libs/safe/src/lib/components/left-sidenav/left-sidenav.component.html
  libs/safe/src/lib/components/left-sidenav/left-sidenav.component.scss
  libs/safe/src/lib/components/left-sidenav/left-sidenav.module.ts
  libs/safe/src/lib/style/styles.scss
Labels: enhancement, tailwind

#1399 Fix 2.1.x/ab#64915 map settings layer control duplicating
  libs/safe/src/lib/components/ui/map/map-layers/map-layers.component.html
  libs/safe/src/lib/components/ui/map/map.component.ts
Labels: fix

#1378 refactor/63564_ABC-replace-mat-error-tags
  apps/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.html
  apps/back-office/src/app/dashboard/pages/api-configuration/api-configuration.module.ts
  apps/back-office/src/app/dashboard/pages/api-configurations/api-configurations.module.ts
  apps/back-office/src/app/dashboard/pages/api-configurations/components/add-api-configuration/add-api-configuration.component.html
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control.component.html
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control.module.ts
  libs/safe/src/lib/components/distribution-lists/components/edit-distribution-list-modal/edit-distribution-list-modal.component.html
  libs/safe/src/lib/components/distribution-lists/components/edit-distribution-list-modal/edit-distribution-list-modal.component.ts
  libs/safe/src/lib/components/layout/layout.component.html
  libs/safe/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.html
  libs/safe/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.ts
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.module.ts
  libs/ui/src/index.ts
  libs/ui/src/lib/chip/chip-input.directive.ts
  libs/ui/src/lib/error-message/error-message.directive.ts
  libs/ui/src/lib/error-message/error-message.module.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind
