Repository ReliefApplications/ems-frontend, pull requests merged in 2023-10, with the labels that each got.

#1912 fix/dashboard-filters-display quick-fix delete min-width of question …
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/shared/src/lib/style/survey.scss
Labels: bug

#1908 Fix/ab# dashboard filter not working in summary cards dashboard
  libs/shared/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder-modal.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: bug

#1890 fix/AB#75146_ABC-path-is-sometimes-lost-after-authentication
  libs/safe/src/lib/services/auth/auth.service.ts
Labels: bug

#1913 fix/AB#76111_block_buttons_not_taking_all_width
  libs/ui/src/lib/button/button.component.scss
  libs/ui/src/lib/button/button.component.ts
Labels: bug

#1916 feat/AB#76147_change_all_cancel_close_buttons_modals_to_new_default_style
  apps/back-office/src/app/application/pages/channels/components/channel-modal/channel-modal.component.html
  apps/back-office/src/app/application/pages/position/components/position-modal/position-modal.component.html
  apps/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.html
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.html
  apps/back-office/src/app/components/add-resource-modal/add-resource-modal.component.html
  apps/back-office/src/app/components/duplicate-application-modal/duplicate-application-modal.component.html
  apps/back-office/src/app/dashboard/pages/api-configurations/components/add-api-configuration/add-api-configuration.component.html
  apps/back-office/src/app/dashboard/pages/applications/components/chose-role/chose-role.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  apps/back-office/src/app/dashboard/pages/reference-datas/add-reference-data/add-reference-data.component.html
  libs/shared/src/lib/components/access/edit-access/edit-access.component.html
  libs/shared/src/lib/components/aggregation/add-aggregation-modal/add-aggregation-modal.component.html
  libs/shared/src/lib/components/aggregation/edit-aggregation-modal/edit-aggregation-modal.component.html
  libs/shared/src/lib/components/choose-record-modal/choose-record-modal.component.html
  libs/shared/src/lib/components/config-display-grid-fields-modal/config-display-grid-fields-modal.component.html
  libs/shared/src/lib/components/confirm-modal/confirm-modal.component.html
  libs/shared/src/lib/components/convert-modal/convert-modal.component.html
  libs/shared/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.html
  libs/shared/src/lib/components/distribution-lists/components/edit-distribution-list-modal/edit-distribution-list-modal.component.html
  libs/shared/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.html
  libs/shared/src/lib/components/email-preview/email-preview.component.html
  libs/shared/src/lib/components/email-template-modal/email-template-modal.component.html
  libs/shared/src/lib/components/grid-layout/add-layout-modal/add-layout-modal.component.html
  libs/shared/src/lib/components/grid-layout/edit-layout-modal/edit-layout-modal.component.html
  libs/shared/src/lib/components/mapping/mapping-modal/mapping-modal.component.html
  libs/shared/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.html
  libs/shared/src/lib/components/preferences-modal/preferences-modal.component.html
  libs/shared/src/lib/components/record-modal/record-modal.component.html
  libs/shared/src/lib/components/role-summary/role-auto-assignment/edit-role-auto-assignment-modal/edit-role-auto-assignment-modal.component.html
  libs/shared/src/lib/components/roles/components/add-role/add-role.component.html
  libs/shared/src/lib/components/search-resource-grid-modal/search-resource-grid-modal.component.html
  libs/shared/src/lib/components/templates/components/edit-template-modal/edit-template-modal.component.html
  libs/shared/src/lib/components/ui/core-grid/errors-modal/errors-modal.component.html
  libs/shared/src/lib/components/ui/core-grid/expanded-comment/expanded-comment.component.html
  libs/shared/src/lib/components/ui/core-grid/export/export.component.html
  libs/shared/src/lib/components/ui/core-grid/popup-editor/popup-editor.component.html
  libs/shared/src/lib/components/users/components/add-user/add-user.component.html
  libs/shared/src/lib/components/users/components/invite-users/invite-users.component.html
  libs/shared/src/lib/components/widget-grid/floating-options/menu/tile-data/tile-data.component.html
  libs/shared/src/lib/components/widgets/map-settings/add-layer-modal/add-layer-modal.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.html
  libs/shared/src/lib/survey/components/geofields-listbox/edit-geofield/edit-geofield.component.html
  libs/ui/src/lib/button/button.component.ts
Labels: enhancement

#1906 Ab#75458 db cluster layer improvements
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/ui/map/layer.ts
  libs/shared/src/lib/components/ui/map/utils/create-div-icon.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-cluster/layer-cluster.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-cluster/layer-cluster.module.ts
  libs/shared/src/lib/components/widgets/map-settings/map-forms.ts
  libs/shared/src/lib/models/layer.model.ts
  libs/shared/src/lib/services/map/graphql/queries.ts
  libs/shared/src/lib/style/map.scss
  package.json
Labels: enhancement

#1914 OORT-feat/IM-83_Add-option-to-make-records-unselectable-in-resources-question
  libs/shared/src/lib/survey/components/resources.ts
Labels: enhancement

#1899 OORT-feat/IM-85-ability-to-not-select-any-applications-on-users-questions
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
Labels: enhancement

#1904 OORT-feat/IM-62_make-it-grid-respects-the-chosen-language
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
Labels: bug

#1911 OORT-feat/IM-81_add-ability-to-conditionally-allow-or-not-dynamicpanel-add-new-panel
  libs/shared/src/lib/survey/global-properties/others.ts
Labels: enhancement

#1918 IM-89 - Added the enable actions title functionality
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.html
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.module.ts
Labels: enhancement

#1839 feat/AB#75138-reposition-save-and-cancel-buttons
  apps/back-office/src/app/application/pages/settings/settings.component.html
  apps/back-office/src/app/application/pages/settings/settings.component.ts
  apps/back-office/src/app/application/pages/settings/settings.module.ts
  apps/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.html
  apps/back-office/src/app/dashboard/pages/api-configuration/api-configuration.module.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/form-records/form-records.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.module.ts
  apps/web-widgets/src/app/widgets/form-widget/form-widget.component.ts
  libs/safe/src/lib/components/form/form.module.ts
  libs/shared/src/index.ts
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.module.ts
  libs/shared/src/lib/components/dashboard-filter/directives/drawer-positioner/drawer-positioner.module.ts
  libs/shared/src/lib/components/form/form.component.html
  libs/shared/src/lib/components/form/form.component.ts
  libs/shared/src/lib/components/form/form.module.ts
  libs/shared/src/lib/components/layout/layout.component.ts
  libs/shared/src/lib/components/role-summary/role-channels/role-channels.component.html
  libs/shared/src/lib/components/role-summary/role-channels/role-channels.module.ts
  libs/shared/src/lib/components/role-summary/role-details/role-details.component.html
  libs/shared/src/lib/components/role-summary/role-details/role-details.module.ts
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/shared/src/lib/components/ui/map/map-sidenav-controls/map-sidenav-controls.component.ts
  libs/shared/src/lib/components/user-summary/user-details/user-details.component.html
  libs/shared/src/lib/components/user-summary/user-details/user-details.component.ts
  libs/shared/src/lib/components/user-summary/user-details/user-details.module.ts
  libs/shared/src/lib/components/users/users.component.ts
  libs/shared/src/lib/components/users/users.module.ts
  libs/shared/src/lib/components/widgets/map-settings/map-settings.component.ts
  libs/shared/src/lib/services/application/application.service.ts
  libs/shared/src/lib/views/profile/profile.component.html
  libs/shared/src/lib/views/profile/profile.module.ts
  libs/ui/src/index.ts
  libs/ui/src/lib/fixed-wrapper/fixed-wrapper.component.html
  libs/ui/src/lib/fixed-wrapper/fixed-wrapper.component.scss
  libs/ui/src/lib/fixed-wrapper/fixed-wrapper.component.spec.ts
  libs/ui/src/lib/fixed-wrapper/fixed-wrapper.component.ts
  libs/ui/src/lib/fixed-wrapper/fixed-wrapper.module.ts
  libs/ui/src/lib/sidenav/layout/layout.service.spec.ts
  libs/ui/src/lib/sidenav/layout/layout.service.ts
  libs/ui/src/lib/sidenav/sidenav-container.component.html
  libs/ui/src/lib/sidenav/sidenav-container.component.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement

#1932 OORT-feat/IM-95_Ability-to-set-the-'save'-text-when-submitting-a-form
  libs/shared/src/lib/components/form/form.component.html
  libs/shared/src/lib/survey/global-properties/others.ts
Labels: enhancement

#1929 IM-92 option to hide tabs if only one page exists
  libs/shared/src/lib/components/form-modal/form-modal.component.html
  libs/shared/src/lib/components/form/form.component.html
  libs/shared/src/lib/survey/global-properties/others.ts
Labels: enhancement

#1925 feat/AB#76364_improve_dialog_style
  apps/back-office/src/app/application/pages/channels/components/channel-modal/channel-modal.component.html
  apps/back-office/src/app/application/pages/position/components/position-modal/position-modal.component.html
  apps/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.html
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.html
  apps/back-office/src/app/components/add-resource-modal/add-resource-modal.component.html
  apps/back-office/src/app/components/duplicate-application-modal/duplicate-application-modal.component.html
  apps/back-office/src/app/components/icon-modal/icon-modal.component.html
  apps/back-office/src/app/dashboard/pages/api-configurations/components/add-api-configuration/add-api-configuration.component.html
  apps/back-office/src/app/dashboard/pages/applications/components/chose-role/chose-role.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-datasource/context-datasource.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action/edit-button-action.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  apps/back-office/src/app/dashboard/pages/reference-datas/add-reference-data/add-reference-data.component.html
  libs/shared/src/lib/components/access/edit-access/edit-access.component.html
  libs/shared/src/lib/components/aggregation/add-aggregation-modal/add-aggregation-modal.component.html
  libs/shared/src/lib/components/aggregation/edit-aggregation-modal/edit-aggregation-modal.component.html
  libs/shared/src/lib/components/choose-record-modal/choose-record-modal.component.html
  libs/shared/src/lib/components/config-display-grid-fields-modal/config-display-grid-fields-modal.component.html
  libs/shared/src/lib/components/confirm-modal/confirm-modal.component.html
  libs/shared/src/lib/components/convert-modal/convert-modal.component.html
  libs/shared/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder-modal.component.html
  libs/shared/src/lib/components/dashboard-filter/filter-settings-modal/filter-settings-modal.component.html
  libs/shared/src/lib/components/distribution-lists/components/edit-distribution-list-modal/edit-distribution-list-modal.component.html
  libs/shared/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.html
  libs/shared/src/lib/components/email-preview/email-preview.component.html
  libs/shared/src/lib/components/email-template-modal/email-template-modal.component.html
  libs/shared/src/lib/components/grid-layout/add-layout-modal/add-layout-modal.component.html
  libs/shared/src/lib/components/grid-layout/edit-layout-modal/edit-layout-modal.component.html
  libs/shared/src/lib/components/mapping/mapping-modal/mapping-modal.component.html
  libs/shared/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.html
  libs/shared/src/lib/components/preferences-modal/preferences-modal.component.html
  libs/shared/src/lib/components/role-summary/role-auto-assignment/edit-role-auto-assignment-modal/edit-role-auto-assignment-modal.component.html
  libs/shared/src/lib/components/roles/components/add-role/add-role.component.html
  libs/shared/src/lib/components/search-resource-grid-modal/search-resource-grid-modal.component.html
  libs/shared/src/lib/components/status-modal/status-modal.component.html
  libs/shared/src/lib/components/templates/components/edit-template-modal/edit-template-modal.component.html
  libs/shared/src/lib/components/ui/core-grid/errors-modal/errors-modal.component.html
  libs/shared/src/lib/components/ui/core-grid/expanded-comment/expanded-comment.component.html
  libs/shared/src/lib/components/ui/core-grid/map-modal/map-modal.component.html
  libs/shared/src/lib/components/users/components/add-user/add-user.component.html
  libs/shared/src/lib/components/users/components/invite-users/invite-users.component.html
  libs/shared/src/lib/components/widget-grid/floating-options/menu/tile-data/tile-data.component.html
  libs/shared/src/lib/components/widgets/map-settings/add-layer-modal/add-layer-modal.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.html
  libs/shared/src/lib/survey/components/geofields-listbox/edit-geofield/edit-geofield.component.html
Labels: enhancement

#1915 Feat/ab#76072 improve surveyjs style to look like UI library
  libs/shared/src/lib/style/survey.scss
  libs/shared/src/lib/survey/widgets/text-widget.ts
Labels: enhancement

#1935 Fix/ab#76504 aggregation not displaying in grid configurations after be reseted
  libs/shared/src/lib/components/aggregation/aggregation-table/aggregation-table.component.ts
Labels: bug

#1933 AB#76508_fix_grids_loading_multiple_times
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.ts
  libs/shared/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.ts
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/widgets/chart/chart.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/shared/src/lib/services/context/context.service.ts
Labels: bug, help wanted

#1837 feat/AB#75137-use-button-for-close-in-all
  apps/back-office/src/app/application/pages/channels/components/add-channel-modal/add-channel-modal.component.html
  apps/back-office/src/app/application/pages/channels/components/add-channel-modal/add-channel-modal.component.ts
  apps/back-office/src/app/application/pages/channels/components/edit-channel-modal/edit-channel-modal.component.html
  apps/back-office/src/app/application/pages/channels/components/edit-channel-modal/edit-channel-modal.component.ts
  apps/back-office/src/app/application/pages/position/components/position-modal/position-modal.component.html
  apps/back-office/src/app/application/pages/position/components/position-modal/position-modal.component.ts
  apps/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.html
  apps/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.ts
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.html
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.ts
  apps/back-office/src/app/components/add-resource-modal/add-resource-modal.component.html
  apps/back-office/src/app/components/add-resource-modal/add-resource-modal.component.ts
  apps/back-office/src/app/components/duplicate-application-modal/duplicate-application-modal.component.html
  apps/back-office/src/app/components/duplicate-application-modal/duplicate-application-modal.component.ts
  apps/back-office/src/app/dashboard/pages/api-configurations/components/add-api-configuration/add-api-configuration.component.html
  apps/back-office/src/app/dashboard/pages/api-configurations/components/add-api-configuration/add-api-configuration.component.ts
  apps/back-office/src/app/dashboard/pages/applications/components/chose-role/chose-role.component.html
  apps/back-office/src/app/dashboard/pages/applications/components/chose-role/chose-role.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-datasource/context-datasource.component.html
  apps/back-office/src/app/dashboard/pages/reference-datas/add-reference-data/add-reference-data.component.html
  apps/back-office/src/app/dashboard/pages/reference-datas/add-reference-data/add-reference-data.component.ts
  libs/safe/src/lib/components/access/edit-access/edit-access.component.html
  libs/safe/src/lib/components/access/edit-access/edit-access.component.ts
  libs/safe/src/lib/components/aggregation/edit-aggregation-modal/edit-aggregation-modal.component.html
  libs/safe/src/lib/components/choose-record-modal/choose-record-modal.component.html
  libs/safe/src/lib/components/choose-record-modal/choose-record-modal.component.ts
  libs/safe/src/lib/components/config-display-grid-fields-modal/config-display-grid-fields-modal.component.html
  libs/safe/src/lib/components/convert-modal/convert-modal.component.html
  libs/safe/src/lib/components/convert-modal/convert-modal.component.ts
  libs/safe/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder-modal.component.html
  libs/safe/src/lib/components/dashboard-filter/filter-settings-modal/filter-settings-modal.component.html
  libs/safe/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.html
  libs/safe/src/lib/components/email-preview/email-preview.component.html
  libs/safe/src/lib/components/form-modal/form-modal.component.html
  libs/safe/src/lib/components/form-modal/form-modal.component.ts
  libs/safe/src/lib/components/grid-layout/edit-layout-modal/edit-layout-modal.component.html
  libs/safe/src/lib/components/mapping/mapping-modal/mapping-modal.component.html
  libs/safe/src/lib/components/mapping/mapping-modal/mapping-modal.component.ts
  libs/safe/src/lib/components/preferences-modal/preferences-modal.component.html
  libs/safe/src/lib/components/record-history-modal/record-history-modal.component.html
  libs/safe/src/lib/components/record-modal/record-modal.component.html
  libs/safe/src/lib/components/record-modal/record-modal.component.ts
  libs/safe/src/lib/components/role-summary/role-auto-assignment/edit-role-auto-assignment-modal/edit-role-auto-assignment-modal.component.html
  libs/safe/src/lib/components/roles/components/add-role/add-role.component.html
  libs/safe/src/lib/components/roles/components/add-role/add-role.component.ts
  libs/safe/src/lib/components/search-resource-grid-modal/search-resource-grid-modal.component.html
  libs/safe/src/lib/components/status-modal/status-modal.component.html
  libs/safe/src/lib/components/ui/core-grid/expanded-comment/expanded-comment.component.html
  libs/safe/src/lib/components/users/components/add-user/add-user.component.html
  libs/safe/src/lib/components/users/components/add-user/add-user.component.ts
  libs/safe/src/lib/components/users/components/invite-users/invite-users.component.html
  libs/safe/src/lib/components/users/components/invite-users/invite-users.component.ts
  libs/safe/src/lib/components/widget-grid/expanded-widget/expanded-widget.component.html
  libs/safe/src/lib/components/widget-grid/floating-options/menu/tile-data/tile-data.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlet/map-clorophlet.component.html
  libs/ui/src/lib/dialog/dialog.component.html
  libs/ui/src/lib/dialog/dialog.component.ts
Labels: enhancement

#1937 fix/AB#76616_ABC-api-configuration-edition-issues fix: data clear for…
  apps/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.html
  apps/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.ts
Labels: bug

#1924 feat/AB#76296_remove-duplication-of-page-step-actions
  apps/back-office/src/app/application/pages/form/form.component.html
  apps/back-office/src/app/application/pages/form/form.component.ts
  apps/back-office/src/app/application/pages/form/form.module.ts
  apps/back-office/src/app/application/pages/form/graphql/mutations.ts
  apps/back-office/src/app/application/pages/workflow/graphql/mutations.ts
  apps/back-office/src/app/application/pages/workflow/workflow.component.html
  apps/back-office/src/app/application/pages/workflow/workflow.component.ts
  apps/back-office/src/app/application/pages/workflow/workflow.module.ts
  apps/back-office/src/app/components/icon-modal/icon-modal.component.html
  apps/back-office/src/app/components/icon-modal/icon-modal.component.spec.ts
  apps/back-office/src/app/components/icon-modal/icon-modal.component.ts
  apps/back-office/src/app/components/view-icon-selector/view-icon-selector.component.html
  apps/back-office/src/app/components/view-icon-selector/view-icon-selector.component.scss
  apps/back-office/src/app/components/view-icon-selector/view-icon-selector.component.spec.ts
  apps/back-office/src/app/components/view-icon-selector/view-icon-selector.component.ts
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.html
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.scss
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.spec.ts
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
  apps/back-office/src/app/components/view-settings-modal/view-settings.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.module.ts
  apps/back-office/src/app/dashboard/pages/dashboard/graphql/mutations.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/access/access.module.ts
  libs/shared/src/lib/components/access/edit-access/edit-access.component.html
  libs/shared/src/lib/components/access/edit-access/edit-access.component.ts
  libs/shared/src/lib/components/access/public-api.ts
  libs/shared/src/lib/components/preferences-modal/preferences-modal.component.ts
  libs/shared/src/lib/services/application/application.service.ts
  libs/shared/src/lib/services/workflow/workflow.service.ts
Labels: enhancement

#1947 fix/AB#76624_white_notification_when_editing_dashboard
  libs/shared/src/lib/components/roles/components/group-list/group-list.component.ts
  libs/shared/src/lib/components/snackbar-spinner/snackbar-spinner.component.html
  libs/shared/src/lib/components/snackbar-spinner/snackbar-spinner.component.ts
  libs/shared/src/lib/services/download/download.service.ts
  libs/shared/src/lib/services/email/email.service.ts
  libs/ui/src/lib/snackbar/snackbar.component.ts
  libs/ui/src/lib/snackbar/snackbar.service.ts
Labels: bug

#1940 feat/AB#76714_Improve-sort-fields-UI
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widgets/common/sorting-settings/sorting-settings.component.html
  libs/shared/src/lib/components/widgets/common/sorting-settings/sorting-settings.component.ts
  libs/shared/src/lib/components/widgets/common/sorting-settings/sorting-settings.module.ts
  libs/styles/src/lib/shared/shared.scss
Labels: bug, enhancement

#1951 Feat/ab#77104 last elements surveyjs update
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/style/styles.scss
Labels: enhancement

#1952 changed custom inputs size,removed some vertical padding between ques…
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/services/form-builder/form-builder.service.ts
  libs/shared/src/lib/style/styles.scss
  libs/shared/src/lib/style/survey.scss
  libs/shared/src/lib/survey/components/resource.ts
  libs/shared/src/lib/survey/components/resources.ts
  libs/shared/src/lib/survey/components/utils.ts
  libs/shared/src/lib/survey/widgets/comment-widget.ts
  libs/shared/src/lib/survey/widgets/dropdown-widget.ts
  libs/shared/src/lib/survey/widgets/tagbox-widget.ts
  libs/shared/src/lib/survey/widgets/text-widget.ts
Labels: enhancement

#1956 AB#77078 : Some uploads not working on beta branch
  libs/shared/src/lib/services/download/download.service.ts
Labels: bug

#1897 feat/AB#73404_enable_column_record_specific_dashboard_in_grid
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
  libs/shared/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.html
  libs/shared/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.module.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.module.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: enhancement

#1955 AB#75879 - Style update - Workflow stepper
  apps/back-office/src/app/app-preview/pages/workflow/workflow.component.html
  apps/back-office/src/app/application/pages/form/form.component.ts
  apps/back-office/src/app/application/pages/workflow/workflow.component.html
  apps/front-office/src/app/application/pages/workflow/workflow.component.html
  libs/shared/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.component.html
  libs/shared/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.module.ts
  libs/shared/src/lib/components/workflow-stepper/components/add-step/add-step.component.html
  libs/shared/src/lib/components/workflow-stepper/components/step/step.component.html
  libs/shared/src/lib/components/workflow-stepper/components/step/step.component.scss
  libs/shared/src/lib/components/workflow-stepper/components/step/step.component.ts
  libs/shared/src/lib/components/workflow-stepper/workflow-stepper.component.html
  libs/shared/src/lib/components/workflow-stepper/workflow-stepper.component.ts
  libs/shared/src/lib/components/workflow-stepper/workflow-stepper.module.ts
  libs/ui/src/lib/tabs/tabs.component.ts
Labels: enhancement, refactor

#1957 OORT-feat/HIT-107_downloading-from-summary-card-downloads-multiple-files
  libs/shared/src/lib/components/widgets/editor/editor.component.html
Labels: bug

#1926 Oort feat/im 91 add length calculation to calculated fields
  libs/shared/src/lib/components/edit-calculated-field-modal/utils/keys.ts
Labels: enhancement

#1938 Oort feat/HIT-98 add option to request confirm when auto modifying fields in quick action
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.scss
  libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
  libs/shared/src/lib/components/widgets/grid/grid.component.ts
Labels: enhancement

#1884 Oort feat/im 20 find a way to change the rows of multiple matrices at once
  libs/shared/src/lib/survey/components/matrices.ts
  libs/shared/src/lib/survey/global-properties/others.ts
  libs/shared/src/lib/survey/init.ts
Labels: enhancement

#1960 fix/AB#77318_resources-records-pagination
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.html
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.html
Labels: bug

#1930 Feat/ab#69019 allow user with read permission duplicate applications and page
  apps/back-office/src/app/application/pages/form/form.component.ts
  apps/back-office/src/app/application/pages/settings/settings.component.html
  apps/back-office/src/app/application/pages/settings/settings.module.ts
  apps/back-office/src/app/application/pages/workflow/workflow.component.ts
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.html
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.spec.ts
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
  apps/back-office/src/app/components/view-settings-modal/view-settings.component.ts
  apps/back-office/src/app/dashboard/pages/applications/applications.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  libs/shared/src/lib/components/access/access.module.ts
  libs/shared/src/lib/components/applications-summary/applications-summary.module.ts
  libs/shared/src/lib/components/applications-summary/components/application-summary/application-summary.component.html
Labels: enhancement

#1967 Bug/ab#76800 eye icon missing
  libs/shared/src/lib/components/navbar/navbar.component.html
  libs/shared/src/lib/components/navbar/navbar.component.scss
  libs/shared/src/lib/services/application/application.service.ts
  libs/shared/src/lib/services/application/graphql/mutations.ts
Labels: bug

#1970 feat/AB#77560_tooltip-position
  libs/shared/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.html
  libs/ui/src/lib/tooltip/tooltip.directive.ts
  libs/ui/src/lib/tooltip/tooltip.module.ts
Labels: enhancement

#1969 AB#77546_review-tooltips
  apps/back-office/src/app/application/pages/channels/channels.component.html
  apps/back-office/src/app/application/pages/position/position.component.html
  apps/back-office/src/app/application/pages/subscriptions/subscriptions.component.html
  apps/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.html
  apps/back-office/src/app/dashboard/pages/applications/applications.component.html
  apps/back-office/src/app/dashboard/pages/form-records/form-records.component.html
  apps/back-office/src/app/dashboard/pages/forms/forms.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.html
  apps/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.html
  apps/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/components/data-presentation-list/data-presentation-list.component.html
  apps/back-office/src/app/dashboard/pages/resource/forms-tab/forms-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.html
  apps/back-office/src/app/dashboard/pages/resources/resources.component.html
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/aggregation/aggregation-table/aggregation-table.component.html
  libs/shared/src/lib/components/applications-archive/applications-archive.component.html
  libs/shared/src/lib/components/applications-archive/applications-archive.module.ts
  libs/shared/src/lib/components/applications-summary/components/application-summary/application-summary.component.html
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.html
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/shared/src/lib/components/dashboard-filter/filter-settings-modal/filter-settings-modal.component.html
  libs/shared/src/lib/components/dashboard-filter/filter-settings-modal/filter-settings-modal.component.ts
  libs/shared/src/lib/components/distribution-lists/distribution-lists.component.html
  libs/shared/src/lib/components/grid-layout/layout-table/layout-table.component.html
  libs/shared/src/lib/components/layout/layout.component.html
  libs/shared/src/lib/components/mapping/mapping.component.html
  libs/shared/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.html
  libs/shared/src/lib/components/notifications/notifications.component.html
  libs/shared/src/lib/components/query-builder/tab-fields/tab-fields.component.html
  libs/shared/src/lib/components/query-builder/tab-style/query-style-list/query-style-list.component.html
  libs/shared/src/lib/components/role-summary/role-features/role-workflows/role-workflows.component.html
  libs/shared/src/lib/components/roles/components/group-list/group-list.component.html
  libs/shared/src/lib/components/roles/components/role-list/role-list.component.html
  libs/shared/src/lib/components/skeleton/skeleton-table/skeleton-table.component.html
  libs/shared/src/lib/components/templates/templates.component.html
  libs/shared/src/lib/components/ui/map/map-download/map-download.component.html
  libs/shared/src/lib/components/users/users.component.html
  libs/shared/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.html
  libs/shared/src/lib/components/widgets/editor-settings/record-selection-tab/record-selection-tab.component.html
  libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
  libs/shared/src/lib/components/widgets/map-settings/map-layers/map-layers.component.html
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  libs/shared/src/lib/components/widgets/map-settings/map-properties/webmap-select/webmap-select.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
  libs/shared/src/lib/views/application-users/components/user-list/user-list.component.html
  libs/shared/src/lib/views/profile/profile.component.html
Labels: enhancement

#1975 Fix/ab#76713 icon display when variant and category class are empty
  libs/ui/src/lib/icon/icon.component.ts
Labels: bug

#1973 AB#77592 : Incorrect UI for workflow access in roles page of application
  libs/shared/src/lib/components/role-summary/role-features/role-workflows/role-workflows.component.html
Labels: bug

#1976 feat/AB#77664_Reduce-padding-of-form-in-dashboard-filter
  libs/shared/src/lib/style/survey.scss
Labels: enhancement

#1979 bugfix/AB#77713_ABC-missing-loading-indicator-in-dashboard
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.html
  apps/front-office/src/app/application/pages/form/form.component.html
  apps/front-office/src/app/application/pages/form/form.module.ts
  apps/front-office/src/app/application/pages/workflow/workflow.component.html
  apps/front-office/src/app/application/pages/workflow/workflow.module.ts
  libs/shared/src/lib/services/application/application.service.ts
Labels: bug

#1927 fix/infinite-re-render-of-filter-dropdowns-in-filter-stage
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.ts
  libs/ui/src/lib/expansion-panel/expansion-panel.component.ts
  libs/ui/src/lib/select-menu/select-menu.component.ts
Labels: bug

#1888 feat/AB#75646_Allow-to-define-grid-actions-from-summary-card-settings
  libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.html
  libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.scss
  libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.spec.ts
  libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.ts
  libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.module.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.module.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/graphql/queries.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.module.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: enhancement

#1981 feat/AB#77745_Find-out-about-vulnerabilities-in-the-front-and-see-how-to-resolve-them
  package-lock.json
Labels: enhancement

#1988 HIT-feat/HIT-125_Add-ability-to-add-tooltip-to-widget-headers
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widget-grid/floating-options/floating-options.component.html
  libs/shared/src/lib/components/widget-grid/widget-grid.component.html
  libs/shared/src/lib/components/widgets/common/display-settings/display-settings.component.html
  libs/shared/src/lib/components/widgets/common/display-settings/display-settings.component.ts
  libs/shared/src/lib/components/widgets/common/display-settings/extendWidgetForm.ts
Labels: enhancement

#1985 feat/AB#77772_provide_options_min_max_line_charts_1
  libs/safe/src/lib/components/ui/charts/line-chart/line-chart.component.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.html
  libs/ui/documentation.json
Labels: enhancement

#1984 fix/AB#77788_improve_summary_card_while_using_aggregation
  apps/back-office/src/app/components/view-icon-selector/view-icon-selector.stories.ts
  libs/shared/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.scss
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
Labels: bug

#1980 feat/AB#77643_Improve-select-fields-in-aggregation-builder
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.html
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.html
  libs/shared/src/lib/components/ui/core-grid/export/export.component.html
  libs/shared/src/lib/components/ui/empty/empty.component.html
  libs/shared/src/lib/components/ui/tagbox/tagbox.component.html
  libs/shared/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.html
  libs/shared/src/lib/components/widgets/common/contextual-filters-settings/contextual-filters-settings.component.html
  libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.html
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.component.html
  libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-cluster/layer-cluster.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/display-tab/display-tab.component.html
  libs/ui/src/lib/checkbox/checkbox.component.html
  libs/ui/src/lib/expansion-panel/expansion-panel.component.html
  libs/ui/src/lib/icon/icon.component.html
Labels: bug, enhancement

#1982 Bugfix/ab#77743 abc page is taking too much resource when showing a grid with many columns records
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/safe/src/lib/components/ui/core-grid/grid/utils/grid-data-formatter.ts
  libs/ui/src/index.ts
  libs/ui/src/lib/tooltip/tooltip.directive.ts
  libs/ui/src/lib/tooltip/types/tooltip-enable-by-list.ts
Labels: bug, refactor

#1986 feat/AB#77772_provide_options_min_max_line_charts_2
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.ts
  libs/safe/src/lib/components/ui/charts/bar-chart/bar-chart.component.ts
  libs/safe/src/lib/components/ui/charts/line-chart/line-chart.component.ts
  libs/safe/src/lib/components/widgets/chart-settings/chart-forms.ts
  libs/safe/src/lib/components/widgets/chart-settings/chart-settings.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.html
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.scss
  libs/safe/src/lib/components/widgets/chart/chart.component.ts
Labels: enhancement

#1826 feat: add alternate table row colors
  libs/ui/src/lib/table/cell.directive.ts
  libs/ui/src/lib/table/table-wrapper.directive.ts
Labels: enhancement

#1987 AB#77434 - Fix duplication of application problem
  apps/back-office/src/app/dashboard/pages/applications/applications.component.ts
Labels: bug, enhancement

#2001 AB#77901 - Review operators in filter builder
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.html
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.ts
Labels: enhancement

#2008 feat/HIT-118-Ability-to-change-items-label-for-lists-in-grid
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/query-builder/query-builder-forms.ts
  libs/shared/src/lib/components/query-builder/query-builder.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/services/grid/grid.service.ts
Labels: enhancement

#2002 feat/AB#75323_map-last-update-control
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/geospatial-map/geospatial-map.component.ts
  libs/shared/src/lib/components/ui/map/interfaces/map.interface.ts
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/ui/map/utils/create-div-icon.ts
  libs/shared/src/lib/components/widgets/map-settings/map-forms.ts
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.component.html
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.component.ts
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.module.ts
  libs/shared/src/lib/services/map/map-controls.service.ts
  libs/shared/src/lib/style/map.scss
  libs/styles/src/lib/shared/shared.scss
Labels: enhancement

#2004 Ab#77901 - Value field in filter component with wrong behavior
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.ts
Labels: bug

#2018 feat/AB#78157_improve_block_style
  apps/back-office/src/app/application/pages/add-page/add-page.component.html
  libs/shared/src/lib/components/applications-archive/applications-archive.component.html
  libs/ui/src/lib/divider/divider.component.scss
Labels: enhancement

#2013 feat/AB#78061-cdk-portal-for-widgte-widget-in-ExpandedWidgetComponent
  apps/back-office/src/app/app-preview/pages/workflow/workflow.component.html
  apps/back-office/src/app/app-preview/pages/workflow/workflow.component.ts
  apps/back-office/src/app/application/pages/workflow/workflow.component.html
  apps/back-office/src/app/application/pages/workflow/workflow.component.ts
  apps/front-office/src/app/application/pages/workflow/workflow.component.html
  apps/front-office/src/app/application/pages/workflow/workflow.component.ts
  libs/shared/src/lib/components/widget-grid/expanded-widget/expanded-widget.component.html
  libs/shared/src/lib/components/widget-grid/expanded-widget/expanded-widget.component.ts
  libs/shared/src/lib/components/widget-grid/widget-actions/widget-actions.component.ts
  libs/shared/src/lib/components/widget-grid/widget-grid.component.html
  libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
  libs/shared/src/lib/components/widget-grid/widget-grid.module.ts
  libs/shared/src/lib/components/widget/widget.component.html
  libs/shared/src/lib/components/widget/widget.component.ts
  libs/shared/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.html
  libs/shared/src/lib/components/widgets/chart/chart.component.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/components/widgets/grid/grid.component.html
  libs/shared/src/lib/components/widgets/grid/grid.component.ts
  libs/shared/src/lib/components/widgets/map/map.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.html
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/shared/src/lib/components/widgets/tabs/tabs.component.ts
Labels: enhancement, refactor

#2022 feat/AB#72018-search-record-in-context-datasource-resource
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
Labels: enhancement

#2019 feat/AB#75646-grid-actions-from-summary-card
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.html
  libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.html
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.forms.ts
Labels: enhancement

#2024 feat/AB#78322_Change-settings-icon-of-widgets-to-be-similar-to-the-one-we-have-for-applications
  libs/shared/src/lib/components/widget-grid/widget-actions/widget-actions.component.html
Labels: enhancement

#2021 refactor: change'tile' inputs to 'widget'
  apps/back-office/documentation.json
  apps/back-office/src/app/app-preview/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/app-preview/pages/dashboard/dashboard.component.ts
  libs/shared/src/lib/components/aggregation/edit-aggregation-modal/edit-aggregation-modal.component.ts
  libs/shared/src/lib/components/custom-widget-style/custom-widget-style.component.ts
  libs/shared/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.ts
  libs/shared/src/lib/components/grid-layout/edit-layout-modal/edit-layout-modal.component.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/components/widget-grid/edit-widget-modal/edit-widget-modal.component.spec.ts
  libs/shared/src/lib/components/widget-grid/edit-widget-modal/edit-widget-modal.component.ts
  libs/shared/src/lib/components/widget-grid/widget-actions/widget-actions.component.ts
  libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
  libs/shared/src/lib/components/widgets/chart-settings/chart-settings.component.spec.ts
  libs/shared/src/lib/components/widgets/chart-settings/chart-settings.component.ts
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.component.html
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  libs/shared/src/lib/components/widgets/map-settings/map-settings.component.html
  libs/shared/src/lib/components/widgets/map-settings/map-settings.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  libs/shared/src/lib/components/widgets/tabs-settings/tabs-settings.component.ts
  libs/shared/src/lib/components/widgets/tabs/tabs.component.ts
  libs/shared/src/lib/services/dashboard/dashboard.service.ts
  libs/shared/src/lib/services/grid/grid.service.ts
Labels: enhancement
