Repository ReliefApplications/ems-frontend, pull requests merged in 2023-06, with the labels that each got.

#1420 bug: add save method in the column chooser
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
Labels: fix

#1421 fix/OORT-640-send-email-to-recipients-not-in-distribution-list
  libs/safe/src/lib/services/email/email.service.ts
Labels: bug

#1427 feat-2.1.x / #59588 DB - Maps - Zoom in / zoom out styling
  libs/safe/src/lib/components/ui/map/map-zoom/map-zoom.component.html
  libs/safe/src/lib/components/ui/map/map-zoom/map-zoom.component.scss
  libs/safe/src/lib/components/ui/map/map-zoom/map-zoom.component.spec.ts
  libs/safe/src/lib/components/ui/map/map-zoom/map-zoom.component.ts
  libs/safe/src/lib/components/ui/map/map.component.scss
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/services/map/map-controls.service.ts
Labels: enhancement

#1416 feat/AB#54824_grouping-layers
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/ui/core-grid/map-modal/map-modal.component.ts
  libs/safe/src/lib/components/ui/map/interfaces/layer-settings.type.ts
  libs/safe/src/lib/components/ui/map/layer.ts
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-forms.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
  libs/safe/src/lib/models/layer.model.ts
  libs/safe/src/lib/services/map/graphql/queries.ts
  libs/safe/src/lib/services/map/map-layers.service.ts
Labels: enhancement

#1436 fix/OORT-643-resource-type-questions-breaking-schema
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/form-builder/form-builder.component.ts
Labels: bug

#1369 feat/added-intersect-and-getMatrixTitles-custom-functions
  apps/back-office/src/environments/environment.oort.lift.ts
  libs/safe/src/lib/components/widgets/summary-card/parser/utils.ts
  libs/safe/src/lib/utils/custom-functions.ts
Labels: enhancement

#1422 Fix/ab#65411 abc fix change detection errors for UI components
  libs/ui/src/lib/button/button.component.scss
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/lib/select-menu/select-menu.component.html
  libs/ui/src/lib/select-menu/select-menu.component.ts
  libs/ui/src/lib/sidenav/sidenav-container.component.ts
  libs/ui/src/lib/tabs/components/tab/tab.component.ts
  libs/ui/src/lib/tabs/tabs.component.html
  libs/ui/src/lib/tabs/tabs.component.ts
Labels: enhancement, tailwind

#1403 feat/AB#65216_ABC-implement-error-and-disabled-states-to-UI-form-wrapper-directive
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-datasource/context-datasource.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-datasource/context-datasource.component.ts
  libs/safe/src/lib/components/dashboard-filter/dashboard-filter.component.html
  libs/safe/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.html
  libs/safe/src/lib/style/styles.scss
  libs/ui/src/lib/chip/chip-list.directive.ts
  libs/ui/src/lib/chip/chip.component.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.component.stories.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/lib/select-menu/select-menu.component.html
  libs/ui/src/lib/select-menu/select-menu.component.ts
  libs/ui/src/lib/textarea/textarea.component.html
  libs/ui/src/lib/textarea/textarea.component.ts
Labels: enhancement, tailwind

#1389 feat/AB#64176-replace-date-inputs
  apps/back-office/src/app/app.module.ts
  apps/back-office/src/app/dashboard/pages/applications/applications.module.ts
  apps/back-office/src/app/dashboard/pages/applications/components/filter/filter.component.html
  apps/back-office/src/app/dashboard/pages/forms/components/filter/filter.component.html
  apps/back-office/src/app/dashboard/pages/forms/forms.module.ts
  apps/back-office/src/app/dashboard/pages/resources/filter/filter.component.html
  apps/back-office/src/app/dashboard/pages/resources/resources.module.ts
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/filter/filter-row/filter-row.component.html
  libs/safe/src/lib/components/filter/filter.module.ts
  libs/safe/src/lib/components/query-builder/date-filter-editor/date-filter-editor.component.html
  libs/safe/src/lib/components/query-builder/query-builder.module.ts
  libs/safe/src/lib/components/record-history/record-history.component.html
  libs/safe/src/lib/components/record-history/record-history.component.ts
  libs/safe/src/lib/components/record-history/record-history.module.ts
  libs/safe/src/lib/components/role-summary/role-resources-filter/role-resources-filter.component.html
  libs/safe/src/lib/components/role-summary/role-resources/role-resources.module.ts
  libs/ui/src/index.ts
  libs/ui/src/lib/date/date-picker.directive.ts
  libs/ui/src/lib/date/date-picker/date-picker.component.html
  libs/ui/src/lib/date/date-picker/date-picker.component.stories.ts
  libs/ui/src/lib/date/date-picker/date-picker.component.ts
  libs/ui/src/lib/date/date-picker/date-picker.module.ts
  libs/ui/src/lib/date/date-range/date-range.component.html
  libs/ui/src/lib/date/date-range/date-range.component.stories.ts
  libs/ui/src/lib/date/date-range/date-range.component.ts
  libs/ui/src/lib/date/date-range/date-range.module.ts
  libs/ui/src/lib/date/date-wrapper.directive.ts
  libs/ui/src/lib/date/date.module.ts
  libs/ui/src/lib/date/date.scss
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/style/styles.scss
Labels: enhancement, tailwind

#1390 Refactor/ab#64173 abc replace autocomplete component
  apps/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.html
  apps/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.ts
  libs/safe/src/lib/components/query-builder/query-builder.component.html
  libs/safe/src/lib/components/query-builder/query-builder.module.ts
  libs/safe/src/lib/components/ui/aggregation-builder/forms-dropdown/forms-dropdown.component.html
  libs/safe/src/lib/components/ui/aggregation-builder/forms-dropdown/forms-dropdown.module.ts
  libs/safe/src/lib/components/ui/tagbox/tagbox.component.html
  libs/safe/src/lib/components/ui/tagbox/tagbox.component.ts
  libs/safe/src/lib/components/ui/tagbox/tagbox.module.ts
  libs/safe/src/lib/components/users/components/add-user/add-user.component.html
  libs/safe/src/lib/components/users/components/add-user/add-user.module.ts
  libs/ui/src/lib/autocomplete/autocomplete.component.html
  libs/ui/src/lib/autocomplete/autocomplete.component.stories.ts
  libs/ui/src/lib/autocomplete/autocomplete.component.ts
  libs/ui/src/lib/autocomplete/autocomplete.directive.ts
  libs/ui/src/lib/autocomplete/autocomplete.module.ts
  libs/ui/src/lib/autocomplete/components/option.component.html
  libs/ui/src/lib/autocomplete/components/option.component.scss
  libs/ui/src/lib/autocomplete/components/option.component.spec.ts
  libs/ui/src/lib/autocomplete/components/option.component.ts
  libs/ui/src/lib/autocomplete/components/option.module.ts
  libs/ui/src/lib/date/date-range/date-range.component.stories.ts
  libs/ui/src/lib/date/date.module.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.component.stories.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/lib/option/option.component.html
  libs/ui/src/lib/ui.module.ts
Labels: enhancement, tailwind

#1439 fix/OORT-644-date-picker-question-enabled-condition
  libs/safe/src/lib/survey/widgets/text-widget.ts
Labels: bug

#1455 fix/OORT-648-load-workflow-page-from-URL
  apps/back-office/src/app/application/pages/workflow/workflow.component.ts
  apps/front-office/src/app/dashboard/pages/workflow/workflow.component.ts
Labels: bug

#1459 Fix/ab#66293 issues role page
  libs/safe/src/lib/components/role-summary/role-channels/role-channels.component.html
  libs/safe/src/lib/components/role-summary/role-details/role-details.component.html
  libs/safe/src/lib/components/role-summary/role-resources/resource-access-filters/resource-access-filters.component.html
  libs/safe/src/lib/components/role-summary/role-resources/resource-fields/resource-fields.component.html
  libs/safe/src/lib/components/role-summary/role-resources/role-resources.component.html
Labels: bug

#1462 fix/AB#66301-display-of-select-label
  libs/ui/src/lib/select-menu/components/select-option.component.ts
Labels: bug

#1467 fix/AB#66621-query-builder-tailwind
  libs/safe/src/lib/components/query-builder/query-builder.component.html
  libs/safe/src/lib/components/query-builder/tab-fields/tab-fields.component.html
  libs/safe/src/lib/components/ui/core-grid/export/export.component.html
  libs/ui/src/lib/radio/radio-group.directive.ts
  libs/ui/src/lib/radio/radio.component.html
  libs/ui/src/lib/radio/radio.component.ts
Labels: bug

#1473 #66659 ABC - Improve front-end lint
  libs/safe/src/lib/components/applications-summary/applications-summary.stories.ts
  libs/safe/src/lib/components/applications-summary/components/add-application/add-application.stories.ts
  libs/safe/src/lib/components/applications-summary/components/application-summary/application-summary.stories.ts
  libs/safe/src/lib/components/content-choice/content-choice.stories.ts
  libs/safe/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/safe/src/lib/components/mapping/mapping-modal/mapping-modal.stories.ts
  libs/safe/src/lib/components/mapping/mapping.stories.ts
  libs/safe/src/lib/components/palette-control/palette-control.stories.ts
  libs/safe/src/lib/components/record-summary/record-summary.stories.ts
  libs/safe/src/lib/components/ui/aggregation-builder/forms-dropdown/forms-dropdown.stories.ts
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/add-field-stage/add-field-stage.stories.ts
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/expressions/expressions.stories.ts
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/group-stage/group-stage.stories.ts
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/pipeline.stories.ts
  libs/safe/src/lib/components/ui/aggregation-builder/series-mapping/series-mapping.stories.ts
  libs/safe/src/lib/components/ui/badge/badge.stories.ts
  libs/safe/src/lib/components/ui/charts/bar-chart/bar-chart.stories.ts
  libs/safe/src/lib/components/ui/charts/line-chart/line-chart.stories.ts
  libs/safe/src/lib/components/ui/charts/pie-donut-chart/pie-donut-chart.stories.ts
  libs/safe/src/lib/components/ui/core-grid/grid/grid.stories.ts
  libs/safe/src/lib/components/ui/empty/empty.stories.ts
  libs/safe/src/lib/components/ui/tagbox/tagbox.stories.ts
  libs/safe/src/lib/components/widget-choice/widget-choice.stories.ts
  libs/safe/src/lib/components/widget-grid/widget-grid.stories.ts
  libs/safe/src/lib/components/workflow-stepper/components/add-step/add-step.stories.ts
  libs/safe/src/lib/components/workflow-stepper/components/step/step.stories.ts
  libs/safe/src/lib/components/workflow-stepper/workflow-stepper.stories.ts
  libs/safe/src/lib/services/api-proxy/api-proxy.service.ts
  libs/safe/src/lib/services/context/context.service.ts
  libs/ui/src/lib/sidenav/sidenav-container.component.ts
  package.json
Labels: enhancement

#1474 fix/AB#66732-distribution-list-incorrect-validation
  libs/safe/src/lib/components/distribution-lists/components/edit-distribution-list-modal/edit-distribution-list-modal.component.html
  libs/safe/src/lib/components/distribution-lists/components/edit-distribution-list-modal/edit-distribution-list-modal.component.ts
  libs/safe/src/lib/components/email-preview/email-preview.component.html
  libs/safe/src/lib/components/email-preview/email-preview.component.ts
  libs/safe/src/lib/survey/widgets/dropdown-widget.ts
  libs/ui/src/lib/error-message/error-message.directive.ts
Labels: bug

#1485 fix/AB#66940-side-menu-on-app-preview
  apps/back-office/src/app/app-preview/app-preview.component.html
  apps/back-office/src/app/app-preview/app-preview.component.ts
Labels: bug

#1491 fix/AB#66994-search-map-layer-datasource
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-datasource/graphql/queries.ts
  libs/safe/src/lib/components/widgets/map-settings/graphql/queries.ts
Labels: bug

#1486 Fix/ab#66580 position filter changing moving pages
  libs/safe/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/safe/src/lib/services/context/context.service.ts
Labels: bug

#1496 bugfix/select-menu-list-component-padding-with-search-element-above
  libs/safe/src/lib/components/widgets/map-settings/map-properties/webmap-select/webmap-select.component.html
  libs/ui/src/lib/graphql-select/graphql-select.component.html
  libs/ui/src/lib/select-menu/select-menu.component.ts
Labels: bug, tailwind

#1497 bugfix/2.0.x-select-menu-list-component-padding-with-search-element-above
  libs/ui/src/lib/graphql-select/graphql-select.component.html
  libs/ui/src/lib/select-menu/select-menu.component.ts
Labels: bug, tailwind

#1495 #66953 - ABC - Show delete & move buttons on left of page when navigation is on top
  libs/safe/src/lib/components/navbar/navbar.component.html
  libs/safe/src/lib/components/navbar/navbar.component.scss
Labels: enhancement

#1501 fix/creating-cached-records
  libs/safe/src/lib/components/form-modal/form-modal.component.ts
  libs/safe/src/lib/components/form/form.component.ts
  libs/safe/src/lib/components/resource-modal/resource-modal.component.ts
  libs/safe/src/lib/services/form-helper/form-helper.service.ts
Labels: bug

#1494 fix/AB#66937-grid-button-actions-tabs
  libs/safe/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.component.html
  libs/ui/src/lib/tabs/tabs.component.ts
Labels: bug

#1510 fix-2.0.x/AB#2367383 Incorrect 'activate-filtering' text
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
Labels: fix

#1509 feat/AB#67382_ABC-if-no-header-value-for-summary-card-dont-display-it
  libs/safe/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.html
  libs/safe/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.ts
Labels: enhancement

#1511 bugfix/AB#67384_ABC-unable-click-on-save-on-form-answer-in-some-cases
  libs/safe/src/lib/style/survey.scss
Labels: bug

#1506 bugfix/AB#66900_ABC-unable-to-drag-the-scroll-bar-to-the-bottom-on-expression-list
  libs/safe/src/lib/components/editor-control/editor-control.component.ts
  libs/safe/src/lib/services/editor/editor.service.ts
Labels: bug, enhancement

#1472 feat/AB#66444_dashboard-button-actions
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action/edit-button-action.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action/edit-button-action.component.scss
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action/edit-button-action.component.spec.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action/edit-button-action.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.module.ts
  apps/back-office/src/app/dashboard/pages/dashboard/graphql/queries.ts
  apps/front-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/front-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/dashboard/pages/dashboard/graphql/queries.ts
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/models/dashboard.model.ts
  libs/safe/src/lib/services/dashboard/dashboard.service.ts
  libs/safe/src/lib/services/dashboard/graphql/mutations.ts
Labels: enhancement

#1515 Feat/ab#67381 list pages inserting link tinymce
  libs/safe/src/lib/components/widgets/editor-settings/editor-settings.component.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/text-editor-tab/text-editor-tab.component.ts
  libs/safe/src/lib/services/data-template/data-template.service.ts
Labels: enhancement

#1517 Fix 2.1.x/ab#66860 db scrollbar missing on popups
  libs/safe/src/lib/components/ui/map/map-popup/map-popup.component.html
Labels: bug

#1520 bugfix/multiple-change-touch-fn-register-within-same-control-instance
  libs/safe/src/lib/components/navbar/navbar.component.html
  libs/ui/src/lib/checkbox/checkbox.component.ts
  libs/ui/src/lib/chip/chip-list.directive.ts
  libs/ui/src/lib/select-menu/select-menu.component.ts
  libs/ui/src/lib/slider/slider.component.ts
  libs/ui/src/lib/toggle/toggle.component.ts
Labels: bug

#1519 bugfix/AB#66622_DB-with-heat-map-styling-on-map-widget-cluster-should-not-display-on-legend-of-map
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-forms.ts
  libs/safe/src/lib/services/map/map-layers.service.ts
Labels: bug

#1525 feat/AB#67615_ABC-add-tooltip-to-fullscreen-visibility-feature-for-pages
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/front-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/front-office/src/app/dashboard/pages/dashboard/dashboard.module.ts
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
Labels: enhancement

#1529 bugfix/AB#67622_ABC-tooltips-not-appearing-when-dashboard-in-fullscreen-mode
  libs/ui/src/lib/tooltip/tooltip.directive.ts
Labels: bug

#1530 bugfix/AB#67468_ABC-cannot-always-change-date
  libs/ui/src/lib/date/date-picker/date-picker.component.html
  libs/ui/src/lib/date/date-picker/date-picker.component.ts
  libs/ui/src/lib/date/date-range/date-range.component.html
  libs/ui/src/lib/date/date-range/date-range.component.ts
  libs/ui/src/lib/date/date-wrapper.directive.ts
Labels: bug

#1526 fix/AB#67640-select-records-resource-question
  libs/safe/src/lib/components/search-resource-grid-modal/search-resource-grid-modal.component.html
  libs/safe/src/lib/survey/widgets/dropdown-widget.ts
Labels: bug

#1537 bugfix/AB#67532_ABC-unable-to-create-aggregation
  libs/safe/src/lib/components/ui/aggregation-builder/aggregation-builder.component.html
  libs/safe/src/lib/components/ui/tagbox/tagbox.component.html
  libs/safe/src/lib/components/ui/tagbox/tagbox.component.ts
Labels: bug

#1531 Moved searchbar to header
  libs/safe/src/lib/components/widgets/summary-card/summary-card.component.html
Labels: enhancement

#1532 bugfix/AB#67625_ABC-when-clicking-on-map-the-view-moves-to-center-on-it
  libs/safe/src/lib/components/ui/map/map-layers/layers-menu-basemap/layers-menu-basemap.component.spec.ts
  libs/safe/src/lib/components/ui/map/map-layers/layers-menu-item/layers-menu-item.component.spec.ts
  libs/safe/src/lib/components/ui/map/map-layers/map-layers.component.spec.ts
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/map-sidenav-controls.component.html
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/map-sidenav-controls.component.scss
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/map-sidenav-controls.component.spec.ts
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/map-sidenav-controls.component.ts
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu-basemap/sidenav-controls-menu-basemap.component.html
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu-basemap/sidenav-controls-menu-basemap.component.scss
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu-basemap/sidenav-controls-menu-basemap.component.spec.ts
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu-basemap/sidenav-controls-menu-basemap.component.ts
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu-item/sidenav-controls-menu-item.component.html
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu-item/sidenav-controls-menu-item.component.scss
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu-item/sidenav-controls-menu-item.component.spec.ts
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu-item/sidenav-controls-menu-item.component.ts
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu/sidenav-controls-menu.component.html
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu/sidenav-controls-menu.component.scss
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu/sidenav-controls-menu.component.spec.ts
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu/sidenav-controls-menu.component.ts
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-popup/layer-popup.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-forms.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.html
  libs/safe/src/lib/services/map/map-controls.service.ts
Labels: bug

#1527 fix/AB#66291_layer-toggle-on-zoom
  libs/safe/src/lib/components/ui/map/layer.ts
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu-item/sidenav-controls-menu-item.component.ts
Labels: bug

#1542 bugfix/AB#67532_ABC-unable-to-create-aggregation
  libs/safe/src/lib/components/ui/tagbox/tagbox.component.ts
  libs/ui/src/lib/autocomplete/autocomplete.directive.ts
Labels: bug

#1538 feat/AB#67731-paginator-navigation-by-page-number
  libs/safe/src/lib/components/widgets/summary-card/summary-card.component.html
  libs/ui/src/lib/paginator/paginator.component.html
  libs/ui/src/lib/paginator/paginator.component.ts
Labels: enhancement

#1547 fix/AB#67842-current-zoom-not-appearing
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-properties/layer-properties.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-properties/layer-properties.component.ts
Labels: bug

#1534 bugfix/AB#63712_DB-extra-location-pointer-is-displaying-on-geo-location-field-on-updating-gelocation-value
  libs/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
Labels: bug

#1548 fix/AB#67844-disable-layers-control-when-editing-layer
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
Labels: bug

#1516 Feat/ab#67438 ability use pages placeholder action buttons
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action/edit-button-action.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action/edit-button-action.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.module.ts
  libs/safe/src/index.ts
  libs/safe/src/lib/components/button-action/button-action-type.ts
  libs/safe/src/lib/components/button-action/button-action.component.html
  libs/safe/src/lib/components/button-action/button-action.component.scss
  libs/safe/src/lib/components/button-action/button-action.component.spec.ts
  libs/safe/src/lib/components/button-action/button-action.component.ts
  libs/safe/src/lib/components/button-action/button-action.module.ts
  libs/safe/src/lib/components/button-action/public-api.ts
  libs/safe/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.ts
  libs/safe/src/lib/components/templates/components/edit-template-modal/edit-template-modal.component.ts
  libs/safe/src/lib/components/widgets/editor-settings/editor-settings.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-popup/fields-element/fields-element.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-popup/layer-popup.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-popup/text-element/text-element.component.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/text-editor-tab/text-editor-tab.component.ts
  libs/safe/src/lib/safe.module.ts
  libs/safe/src/lib/services/data-template/data-template.service.ts
  libs/safe/src/lib/services/editor/editor.service.ts
  libs/safe/src/lib/utils/parser/utils.ts
Labels: enhancement

#1546 Feat/ab#67833 removed auto addition br tag in editor summary card
  libs/safe/src/lib/utils/parser/utils.ts
Labels: enhancement

#1554 fix: email template links + upload from FO
  apps/front-office/src/app/graphql.module.ts
  libs/safe/src/lib/const/tinymce.const.ts
Labels: bug

#1552 Bugfix/ab#67930 db duplicated layers on map change in the map settings
  libs/safe/src/lib/components/ui/map/layer.ts
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
  libs/safe/src/lib/services/map/arcgis.service.ts
Labels: bug, enhancement

#1553 bugfix/AB#67616_ABC-multiple-layers-created-in-legend-on-geofield-change-in-layer
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
Labels: bug

#1395 feat/AB#65122_allow_set_change_labels_geofields
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/geofields-listbox/edit-geofield/edit-geofield.component.html
  libs/safe/src/lib/components/geofields-listbox/edit-geofield/edit-geofield.component.scss
  libs/safe/src/lib/components/geofields-listbox/edit-geofield/edit-geofield.component.spec.ts
  libs/safe/src/lib/components/geofields-listbox/edit-geofield/edit-geofield.component.ts
  libs/safe/src/lib/components/geofields-listbox/geofield.type.ts
  libs/safe/src/lib/components/geofields-listbox/geofields-listbox.component.html
  libs/safe/src/lib/components/geofields-listbox/geofields-listbox.component.ts
  libs/safe/src/lib/components/geospatial-map/geospatial-fields/geospatial-fields.component.html
  libs/safe/src/lib/components/geospatial-map/geospatial-fields/geospatial-fields.component.ts
  libs/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  libs/safe/src/lib/survey/components/geospatial.ts
Labels: enhancement

#1569 Feat/ab#68048 show navitems as links instead of classic buttons
  libs/safe/src/lib/components/navbar/navbar.component.html
Labels: enhancement

#1572 Feat/ab#68112 add missing translations
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action/edit-button-action.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/categories-settings/categories-settings.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/simple-renderer/simple-renderer.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/unique-value-renderer/unique-value-renderer.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  libs/safe/src/lib/services/map/map-controls.service.ts
Labels: enhancement

#1577 DB#68118-Hidden-pages-not-working-with-nav-in-top
  libs/safe/src/lib/components/navbar/navbar.component.html
Labels: fix

#1579 Bugfix/ab#63712 db extra location pointer is displaying on geo location field on updating gelocation value
  libs/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  libs/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/safe/src/lib/components/ui/core-grid/map-modal/map-modal.component.html
  libs/safe/src/lib/components/ui/map/interfaces/map.interface.ts
  libs/safe/src/lib/components/ui/map/layer.ts
Labels: bug

#1583 Fix 2.1.x/db#68160 correct display for geospacial fields records grid
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.ts
Labels: fix

#1549 Fix/ab#67763 saved field to update quick action not available
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
  libs/safe/src/lib/components/widgets/grid/grid.component.ts
  libs/safe/src/lib/survey/global-properties/reference-data.ts
Labels: bug

#1585 fix: tagbox and dropdown question enable/disable status
  libs/safe/src/lib/survey/widgets/dropdown-widget.ts
  libs/safe/src/lib/survey/widgets/tagbox-widget.ts
Labels: bug

#1589 fix: size of tabs title and overflow
  libs/ui/src/lib/tabs/components/tab/tab.component.html
  libs/ui/src/lib/tabs/components/tab/tab.component.scss
  libs/ui/src/lib/tabs/tabs.component.ts
Labels: bug
