Repository ReliefApplications/ems-frontend, pull requests merged in 2023-12, with the labels that each got.

#2115 feat/AB#80396-better-indication-group-stage-is-not-only-about-grouping
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/ui/aggregation-builder/pipeline/group-stage/group-stage.component.html
  libs/shared/src/lib/components/ui/aggregation-builder/pipeline/group-stage/group-stage.component.ts
Labels: enhancement

#2113 fix/AB#80369-display-core-templates-when-adding-new-form
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.html
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.ts
Labels: bug

#2106 Ab#79847 load map layers individually
  libs/shared/src/lib/components/ui/map/layer.ts
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/services/map/map-layers.service.ts
Labels: enhancement, refactor

#2119 fix/AB#80508_reset_default_button_do_not_put_back_sticky_hidden_columns
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
Labels: bug

#2114 Feat/ab#80401 reference data UI improvements
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data-payload-modal/reference-data-payload-modal.component.html
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data-payload-modal/reference-data-payload-modal.component.scss
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data-payload-modal/reference-data-payload-modal.component.spec.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data-payload-modal/reference-data-payload-modal.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.module.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/services/reference-data/reference-data.service.ts
Labels: enhancement

#2121 fix: zoom tooltips' icon position
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
Labels: bug

#2123 feat/AB#80614_change_layer_datasource
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.ts
Labels: enhancement

#2122 bugfix/AB#80650_ABC-reset-default-layout-button-not-appearing-in-fron…
  apps/front-office/project.json
  apps/web-widgets/project.json
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.html
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.html
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/components/widgets/grid/grid.component.html
  libs/shared/src/lib/components/widgets/grid/grid.component.ts
Labels: bug, refactor

#2124 AB#76614 Changing form locale duplicates some questions
  libs/shared/src/lib/survey/widgets/dropdown-widget.ts
  libs/shared/src/lib/survey/widgets/tagbox-widget.ts
  libs/shared/src/lib/survey/widgets/text-widget.ts
Labels: bug

#1993 feat/AB#77902_tinymce_text_editor_for_filter_values_that_allow_expressions
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/query-builder/date-filter-editor/date-filter-editor.component.html
  libs/shared/src/lib/components/query-builder/date-filter-editor/date-filter-editor.component.ts
Labels: enhancement

#2128 feat/AB#80613_edit-refData-fields
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.module.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
Labels: enhancement

#2130 feat/AB#80732_Incorrect-number-of-items-in-page-after-search
  apps/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.ts
  apps/back-office/src/app/dashboard/pages/form-records/form-records.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.html
  apps/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.ts
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.html
Labels: bug

#2127 fix/AB#80703-incorrectly-size-columns-when-hiding-them-in-grid-widget
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
Labels: bug

#2129 Fix/ab#55095 choices by url should be erased automatically if set choices from ref data
  libs/shared/src/lib/survey/global-properties/reference-data.ts
Labels: bug

#2135 fix/AB#80995_when_edit_widget_is_redirected_to_top_page
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
Labels: bug

#2139 add isdoneloading observable to fetch fields only after they are load…
  libs/shared/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/services/query-builder/query-builder.service.ts
Labels: bug

#2050 Search and filter optimisation
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: enhancement, refactor, in code review

#1575 AB#64775_support_for_reference_data
  libs/shared/src/lib/utils/parser/utils.ts
Labels: enhancement

#2150 AB#81421_fix_profile_page_in_front_office
  apps/front-office/src/app/application/application.component.html
  apps/front-office/src/app/application/application.component.ts
  libs/shared/src/lib/services/application/application.service.ts
Labels: bug

#2152 feat/AB#81422_ABC-prevent-the-url-to-be-changed-while-using-the-app-a…
  apps/web-widgets/src/app/widgets/app-widget/app-widget-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/app-widget.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/application.component.html
  apps/web-widgets/src/app/widgets/app-widget/application/application.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/form/form-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/form/form.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/home/home-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/role-summary/role-summary-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/roles/roles-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/share/share-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/share/share.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/user-summary/user-summary-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/workflow/workflow-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/workflow/workflow.component.ts
  apps/web-widgets/src/app/widgets/app-widget/guards/can-deactivate.guard.ts
  apps/web-widgets/src/app/widgets/app-widget/guards/normalize-url.guard.ts
Labels: enhancement, refactor

#2155 feat/AB#81471_allow_to_remove_on_click_refData_resource_in_widgets_settings
  libs/shared/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.html
  libs/shared/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.ts
  libs/shared/src/lib/components/widgets/editor-settings/record-selection-tab/record-selection-tab.component.html
  libs/shared/src/lib/components/widgets/editor-settings/record-selection-tab/record-selection-tab.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/tab-main/tab-main.component.html
  libs/shared/src/lib/components/widgets/grid-settings/tab-main/tab-main.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/tab-main/tab-main.module.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.ts
Labels: enhancement

#2156 AB#81468 ABC - Prevent edition of sorting fields to create UX issues
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
Labels: bug

#2159 AB#81435 : Add option to hide summary cards buttons
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.forms.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.html
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: enhancement

#2158 Ab#81454 add ref data support for layers
  libs/shared/src/i18n/en.json
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.ts
  libs/shared/src/lib/components/widgets/map-settings/graphql/queries.ts
  libs/shared/src/lib/services/map/map-layers.service.ts
Labels: enhancement

#2166 feat/AB#81627-cdr-detecChanges-when-attaching-detaching-elements
  libs/ui/src/lib/sidenav/sidenav.directive.ts
  libs/ui/src/lib/tabs/directives/tab-body-host.directive.ts
  libs/ui/src/lib/tooltip/tooltip.directive.ts
Labels: enhancement

#2160 feat/AB#81521_ABC-trigger-filter-from-text-and-summary-card
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.ts
Labels: enhancement

#2168 Feat/ab#81521 abc add filter configuration for text and summary card
  libs/shared/src/lib/const/tinymce.const.ts
Labels: enhancement

#2154 fix/AB#81441-calc-methods-in-summary-cards-and-text-widgets
  libs/shared/src/lib/utils/parser/utils.ts
Labels: bug

#2170 fix/AB#81650-cannot-save-static-ref-data-valueField-required
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
Labels: bug

#2178 feat/AB#81669-improve-aggregations-tab-in-text-widget
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widgets/common/template-aggregation-modal/template-aggregation-modal.component.html
  libs/shared/src/lib/components/widgets/common/template-aggregations/template-aggregations.component.html
  libs/shared/src/lib/components/widgets/common/template-aggregations/template-aggregations.component.ts
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.component.html
Labels: enhancement

#2173 Feat/ab#81625 add search on top of layers selection
  libs/shared/src/lib/components/widgets/map-settings/add-layer-modal/add-layer-modal.component.html
  libs/shared/src/lib/components/widgets/map-settings/add-layer-modal/add-layer-modal.component.ts
  libs/shared/src/lib/components/widgets/map-settings/add-layer-modal/graphql/queries.ts
  libs/shared/src/lib/services/map/graphql/queries.ts
  libs/shared/src/lib/services/map/map-layers.service.ts
Labels: enhancement

#2177 feat/use_tinymce_min_scripts_for_builds
  .DS_Store
  apps/back-office/project.json
  apps/front-office/project.json
Labels: dependencies

#2179 Feat/ab unbind allocated memory from set timeout
  apps/back-office/src/app/components/custom-style/custom-style.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  libs/shared/src/lib/components/custom-widget-style/custom-widget-style.component.ts
  libs/shared/src/lib/components/dashboard-filter/directives/drawer-positioner/drawer-positioner.directive.ts
  libs/shared/src/lib/components/distribution-lists/components/edit-distribution-list-modal/edit-distribution-list-modal.component.ts
  libs/shared/src/lib/components/email-preview-modal/email-preview-modal.component.ts
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/components/form/form.component.ts
  libs/shared/src/lib/components/roles/components/group-list/group-list.component.ts
  libs/shared/src/lib/components/ui/tagbox/tagbox.component.ts
  libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
  libs/shared/src/lib/components/widgets/common/contextual-filters-settings/contextual-filters-settings.component.ts
  libs/shared/src/lib/components/widgets/tabs-settings/tab-settings/tab-settings.component.ts
  libs/shared/src/lib/services/download/download.service.ts
  libs/shared/src/lib/services/email/email.service.ts
  libs/ui/src/lib/alert/alert.component.ts
  libs/ui/src/lib/autocomplete/autocomplete.directive.ts
  libs/ui/src/lib/breadcrumbs/breadcrumbs.component.ts
  libs/ui/src/lib/chip/chip.component.ts
  libs/ui/src/lib/date/date-picker.directive.ts
  libs/ui/src/lib/date/date-wrapper.directive.ts
  libs/ui/src/lib/menu/directives/menu.directive.ts
  libs/ui/src/lib/sidenav/sidenav-container.component.ts
  libs/ui/src/lib/sidenav/sidenav.directive.ts
  libs/ui/src/lib/snackbar/snackbar.component.ts
  libs/ui/src/lib/tabs/tabs.component.ts
Labels: enhancement

#2176 feat/AB#81670_ABC-button-to-preview-aggregation-data
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data-payload-modal/reference-data-payload-modal.component.spec.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/index.ts
  libs/shared/src/lib/components/aggregation/edit-aggregation-modal/edit-aggregation-modal.component.ts
  libs/shared/src/lib/components/payload-modal/payload-modal.component.html
  libs/shared/src/lib/components/payload-modal/payload-modal.component.scss
  libs/shared/src/lib/components/payload-modal/payload-modal.component.spec.ts
  libs/shared/src/lib/components/payload-modal/payload-modal.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder-forms.ts
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.html
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.module.ts
  libs/shared/src/lib/components/ui/tagbox/tagbox.component.html
  libs/shared/src/lib/components/widgets/common/template-aggregations/template-aggregations.component.html
  libs/shared/src/lib/components/widgets/common/template-aggregations/template-aggregations.component.ts
  libs/shared/src/lib/services/aggregation/aggregation.service.ts
  libs/shared/src/lib/services/aggregation/graphql/queries.ts
  libs/shared/src/lib/shared.module.ts
Labels: enhancement, refactor

#2181 bug/AB#81838_Adding-a-new-page-hides-other-pages-from-application
  libs/ui/src/lib/sidenav/sidenav.directive.ts
  libs/ui/src/lib/tabs/directives/tab-body-host.directive.ts
  libs/ui/src/lib/tooltip/tooltip.directive.ts
Labels: bug

#2182 bugfix/AB#81865_ABC-aggregation-templates-issues
  libs/shared/src/lib/components/widgets/common/template-aggregation-modal/template-aggregation-modal.component.ts
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.component.ts
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.forms.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/utils/parser/utils.ts
Labels: bug, refactor

#2180 refactor/AB#81668_add-mutually-exclusive-validator
  libs/shared/src/lib/components/widgets/chart-settings/chart-forms.ts
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.forms.ts
  libs/shared/src/lib/components/widgets/map-settings/map-forms.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.forms.ts
  libs/shared/src/lib/utils/validators/mutuallyExclusive.validator.ts
Labels: enhancement, refactor

#2163 fix/AB#81560-fields-disappear-when-deselecting-aggregation-edit
  libs/shared/src/lib/components/ui/tagbox/tagbox.component.ts
Labels: bug

#2175 fix/AB#81442_filter-on-refData-aggregations
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  libs/shared/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder-modal.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.ts
  libs/shared/src/lib/models/reference-data.model.ts
  libs/shared/src/lib/services/aggregation-builder/aggregation-builder.service.ts
  libs/shared/src/lib/utils/filter/reference-data-filter.util.ts
  libs/shared/src/lib/utils/parser/utils.ts
Labels: bug, enhancement

#2003 feat/AB#63539_merge-into-beta-improvments-on-context-dashboards
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/graphql/queries.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.ts
  libs/shared/src/lib/components/filter/filter-group/filter-group.component.html
  libs/shared/src/lib/components/filter/filter-group/filter-group.component.ts
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.html
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.ts
  libs/shared/src/lib/components/filter/filter.component.html
  libs/shared/src/lib/components/filter/filter.component.ts
  libs/shared/src/lib/components/filter/filter.module.ts
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/shared/src/lib/components/widget-grid/widget-actions/widget-actions.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/shared/src/lib/models/dashboard.model.ts
  libs/shared/src/lib/services/aggregation/aggregation.service.ts
  libs/shared/src/lib/services/context/context.service.ts
  libs/shared/src/lib/services/grid-layout/grid-layout.service.ts
  libs/shared/src/lib/services/map/map-layers.service.ts
Labels: enhancement

#2187 Ab#81965 change context datasource selection
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-datasource/context-datasource.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-datasource/context-datasource.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widgets/common/template-aggregation-modal/template-aggregation-modal.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
Labels: enhancement

#2186 AB#81834_resources_questions_grid_take_too_much_width'
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/survey/components/resources.ts
Labels: bug

#2189 bugfix/AB#81961_ABC-issue-with-grid-actions-tab-in-summary-card-settings
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
Labels: bug

#2191 AB#82019 Make context filter work for text widget with aggregation
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.forms.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
Labels: enhancement

#2192 Ab#82021 correct tooltip and text overflow for ref data on grid
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
Labels: bug

#2201 feat/create-abstract-class-for-all-widget-settings-form
  libs/shared/src/lib/components/controls/resource-select/resource-select.component.ts
  libs/shared/src/lib/components/widget-grid/edit-widget-modal/edit-widget-modal.component.html
  libs/shared/src/lib/components/widget-grid/edit-widget-modal/edit-widget-modal.component.ts
  libs/shared/src/lib/components/widgets/chart-settings/chart-settings.component.html
  libs/shared/src/lib/components/widgets/chart-settings/chart-settings.component.ts
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.component.html
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.html
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
  libs/shared/src/lib/components/widgets/map-settings/map-settings.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.forms.ts
  libs/shared/src/lib/components/widgets/tabs-settings/tabs-settings.component.html
  libs/shared/src/lib/components/widgets/tabs-settings/tabs-settings.component.ts
  libs/shared/src/lib/models/dashboard.model.ts
  libs/ui/src/lib/graphql-select/graphql-select.component.ts
  libs/ui/src/lib/select-menu/select-menu.component.ts
  libs/ui/src/lib/tabs/components/tab/tab.component.html
  libs/ui/src/lib/tabs/components/tab/tab.component.scss
  libs/ui/src/lib/tabs/components/tab/tab.component.ts
  libs/ui/src/lib/tabs/tabs.component.ts
Labels: bug, refactor

#2202 bugfix/AB#82170_context-filter-update-will-not-work-in-template
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  libs/shared/src/lib/services/context/context.service.ts
Labels: bug

#2193 feat/AB#81960_ABC-in-charts-predefined-filters-when-using-reference-data-wont-work
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  libs/shared/src/lib/components/widgets/chart-settings/graphql/queries.ts
  libs/shared/src/lib/components/widgets/chart-settings/tab-filters/tab-filters.component.ts
  libs/shared/src/lib/utils/reference-data-metadata.util.ts
Labels: enhancement

#2207 bugfix/AB#82215_ABC-infinite-scrolling-not-working-with-summary-cards-and-ref-data
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: bug

#2206 AB#82119 : Fix bug with chart title in preview
  libs/shared/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.ts
Labels: bug

#2204 AB#82025 : Allow to use widget custom css in display of summary card & editor widgets settings
  libs/shared/src/lib/components/widget/widget.component.ts
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.component.html
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  libs/shared/src/lib/services/widget/widget.service.spec.ts
  libs/shared/src/lib/services/widget/widget.service.ts
Labels: enhancement

#2216 AB#82255_fix_file_in_text_and_summary_cards
  libs/shared/src/lib/utils/parser/utils.ts
Labels: bug

#2215 AB#82246_fix_drag_drop_and_open_close_for_unique_values_in_layers
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/unique-value-renderer/unique-value-renderer.component.html
Labels: bug

#2220 bugfix/horizontal-tabs-label-color
  libs/ui/src/lib/tabs/components/tab/tab.component.html
  libs/ui/src/lib/tabs/components/tab/tab.component.scss
Labels: bug

#2219 bugfix/AB#82362_summary-cards-view-not-updated-on-editing-records-from-grid-view
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/shared/src/lib/components/widgets/grid/grid.component.html
  libs/shared/src/lib/components/widgets/grid/grid.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.html
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: bug

#2212 Update kendo packages
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.module.ts
  libs/shared/src/lib/components/ui/core-grid/date-filter-menu/date-filter-menu.component.html
  libs/shared/src/lib/components/ui/core-grid/date-filter-menu/date-filter-menu.module.ts
  libs/shared/src/lib/components/ui/core-grid/filter/filter.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.module.ts
  libs/shared/src/lib/components/ui/core-grid/grid/utils/grid-data-formatter.ts
  libs/shared/src/lib/components/ui/core-grid/row-actions/row-actions.component.html
  libs/shared/src/lib/components/ui/core-grid/row-actions/row-actions.module.ts
  libs/shared/src/lib/components/users/components/invite-users/invite-users.component.html
  libs/shared/src/lib/components/users/components/invite-users/invite-users.module.ts
  libs/shared/src/lib/utils/parser/utils.ts
  libs/styles/src/lib/kendo/theme.scss
  package-lock.json
  package.json
Labels: enhancement, dependencies, in code review

#2221 AB#82395_add_lint_check_for_web_widgetsadd web-widgets check and fix lint
  apps/web-widgets/src/app/app.component.ts
  apps/web-widgets/src/app/utils/shadow-root-extended-host.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/role-summary/role-summary.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/user-summary/user-summary.component.ts
  apps/web-widgets/src/app/widgets/form-widget/components/form.component.ts
  apps/web-widgets/src/app/widgets/form-widget/form-widget.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  package.json
Labels: enhancement

#2224 AB#82403_fix_wrong_cdk_drag_styling
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/unique-value-renderer/unique-value-renderer.component.html
Labels: bug

#2188 feat/AB#81962_ABC-make-sure-the-summary-card-asks-for-layout-or-aggregation-when-resource-selected
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.forms.ts
Labels: enhancement
