Repository ReliefApplications/ems-frontend, pull requests merged in 2023-03, with the labels that each got.

#1155 Finished styling chart legend refactor
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.html
Labels: enhancement

#1179 feat/AB#58724-integrate-ArcGIS-poc (wip)
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/services/map/arcgis.service.ts
  libs/safe/src/typings/leaflet/index.d.ts
  package-lock.json
  package.json
Labels: enhancement

#1183 refactor/AB#58740_improve-map-settings-layout
  libs/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.scss
  libs/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.spec.ts
  libs/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-general/map-general.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.scss
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.scss
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-settings.module.ts
Labels: refactor

#1185 refactor: empty page when no content
  apps/front-office/src/app/dashboard/dashboard.component.html
  apps/front-office/src/app/dashboard/dashboard.component.ts
  apps/front-office/src/app/dashboard/dashboard.module.ts
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
Labels: refactor

#1181 AB#59156-controls-map-settings
  apps/back-office/project.json
  apps/front-office/project.json
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/ui/map/interfaces/map.interface.ts
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-forms.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.component.scss
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.component.spec.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
  libs/safe/src/lib/services/map/map-controls.service.ts
  package-lock.json
Labels: enhancement

#1190 refactor/AB#58738_add_webmap_select_map_settings
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/webmap-select/webmap-select.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-properties/webmap-select/webmap-select.component.scss
  libs/safe/src/lib/components/widgets/map-settings/map-properties/webmap-select/webmap-select.component.spec.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/webmap-select/webmap-select.component.ts
Labels: refactor

#1175 Refactor/oort-605 add new cron expression form field
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.ts
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.module.ts
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.html
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.scss
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.spec.ts
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.ts
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control.component.html
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control.component.ts
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control.module.ts
  libs/safe/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.html
  libs/safe/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.module.ts
  package.json
Labels: refactor

#1192 feat/AB#59422_possibility_hide_grids_line_bar_charts
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/ui/charts/bar-chart/bar-chart.component.ts
  libs/safe/src/lib/components/ui/charts/line-chart/line-chart.component.ts
  libs/safe/src/lib/components/widgets/chart-settings/charts/chart.ts
  libs/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.html
  libs/safe/src/lib/components/widgets/chart/chart.component.ts
Labels: enhancement

#1194 feat/AB#59307_map-datasource-selection
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/ui/map/utils/create-div-icon.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.module.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.scss
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.spec.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.module.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-properties/layer-properties.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-properties/layer-properties.component.ts
  libs/safe/src/lib/components/widgets/map-settings/graphql/queries.ts
  libs/safe/src/lib/components/widgets/map-settings/map-forms.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.ts
Labels: enhancement

#1193 feat/AB#59512_DB_implement_polarChart
  apps/back-office/src/environments/environment.azure.dev.ts
  apps/back-office/src/environments/environment.azure.prod.ts
  apps/back-office/src/environments/environment.azure.uat.ts
  apps/back-office/src/environments/environment.oort.aws.ts
  apps/back-office/src/environments/environment.oort.demo.ts
  apps/back-office/src/environments/environment.oort.dev.ts
  apps/back-office/src/environments/environment.oort.guyane.ts
  apps/back-office/src/environments/environment.oort.lift.ts
  apps/back-office/src/environments/environment.oort.local.ts
  apps/back-office/src/environments/environment.oort.prod.ts
  apps/back-office/src/environments/environment.ts
  apps/front-office/src/environments/environment.oort.lift.ts
  libs/safe/src/lib/components/ui/charts/pie-donut-chart/pie-donut-chart.component.ts
  libs/safe/src/lib/components/widget-grid/floating-options/menu/tile-data/tile-data.component.ts
  libs/safe/src/lib/components/widget-grid/widget-grid.component.ts
  libs/safe/src/lib/components/widgets/chart-settings/constants.ts
  libs/safe/src/lib/components/widgets/chart/chart.component.html
  libs/safe/src/lib/components/widgets/chart/chart.component.ts
  libs/safe/src/lib/directives/fullscreen/fullscreen.directive.ts
  libs/safe/src/lib/directives/fullscreen/fullscreen.module.ts
  libs/safe/src/lib/models/dashboard.model.ts
  libs/safe/src/lib/services/dashboard/dashboard.service.ts
Labels: enhancement

#1195 feat/AB#59301 add fields component in map layer settings
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/editable-text/editable-text.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-fields/layer-fields.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-fields/layer-fields.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-fields/layer-fields.module.ts
  libs/safe/src/lib/style/map.scss
Labels: enhancement

#1199 feat/AB#59514-cluster-settings
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.module.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-cluster/layer-cluster.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-cluster/layer-cluster.component.scss
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-cluster/layer-cluster.component.spec.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-cluster/layer-cluster.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-cluster/layer-cluster.module.ts
  libs/safe/src/lib/components/widgets/map-settings/map-forms.ts
Labels: enhancement

#1211 fix/AB#59926-summary-card-widget-scroll
  libs/safe/src/lib/components/widgets/summary-card/summary-card.component.scss
Labels: bug

#1214 fix/AB#60147-grid-widget-layout-selection-width
  libs/safe/src/lib/components/widgets/grid/grid.component.html
Labels: bug

#1203 feat/AB#59633-styling-difference
  .DS_Store
  apps/back-office/project.json
  apps/back-office/src/app/app.module.ts
  apps/back-office/src/app/application/pages/settings/settings.component.html
  apps/back-office/src/app/application/pages/settings/settings.component.ts
  apps/back-office/src/app/components/custom-style/custom-style.component.html
  apps/back-office/src/app/components/custom-style/custom-style.component.scss
  apps/back-office/src/app/components/custom-style/custom-style.component.spec.ts
  apps/back-office/src/app/components/custom-style/custom-style.component.ts
  apps/back-office/src/app/components/custom-style/graphql/mutations.ts
  apps/back-office/src/app/graphql.module.ts
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/layout/layout.component.ts
  libs/safe/src/lib/components/left-sidenav/left-sidenav.component.ts
  libs/safe/src/lib/services/application/application.service.ts
  libs/safe/src/lib/services/layout/layout.service.ts
  libs/safe/src/lib/survey/init.ts
  libs/safe/src/typings/extract-files/index.d.ts
  package-lock.json
  package.json
Labels: enhancement

#1204 fix/AB#59603_some_charts_legends_are_undefined
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/ui/aggregation-builder/aggregation-builder.component.html
  libs/safe/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  libs/safe/src/lib/components/ui/aggregation-builder/aggregation-builder.module.ts
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.ts
  libs/safe/src/lib/components/ui/aggregation-builder/series-mapping/series-mapping.component.ts
  libs/safe/src/lib/components/ui/tagbox/tagbox.component.html
  libs/safe/src/lib/components/ui/tagbox/tagbox.component.ts
  libs/safe/src/lib/components/ui/tagbox/tagbox.module.ts
  libs/safe/src/lib/components/widgets/chart/chart.component.ts
Labels: fix

#1216 Feat/ab#60139 db view current layer edition changes
  libs/safe/src/lib/components/ui/map/interfaces/layer-settings.type.ts
  libs/safe/src/lib/components/ui/map/layer.ts
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/components/ui/map/test/layer-settings-test.ts
  libs/safe/src/lib/components/widgets/map-settings/add-layer-modal/graphql/queries.ts
  libs/safe/src/lib/components/widgets/map-settings/map-forms.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-properties/layer-properties.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/graphql/queries.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.ts
  libs/safe/src/lib/models/layer.model.ts
  libs/safe/src/lib/services/map/graphql/mutations.ts
  libs/safe/src/lib/services/map/graphql/queries.ts
  libs/safe/src/lib/services/map/map-layers.service.ts
Labels: enhancement
