Repository ReliefApplications/ems-frontend, pull requests merged in 2023-02, with the labels that each got.

#1105 feat/AB#55399_leaflet-measure
  angular.json
  package-lock.json
  package.json
  projects/safe/src/lib/components/widgets/map/map.component.scss
  projects/safe/src/lib/components/widgets/map/map.component.ts
  projects/safe/src/lib/components/widgets/map/measure.const.ts
  projects/safe/src/lib/style/map.scss
  projects/safe/src/lib/style/styles.scss
Labels: enhancement

#1104 feat/AB#52180_search-addresses
  projects/safe/src/lib/components/widgets/map/map.component.ts
Labels: bug, enhancement

#1106 start to integrate clusters
  package-lock.json
  package.json
  projects/safe/src/lib/components/widgets/map/cluster-test.ts
  projects/safe/src/lib/components/widgets/map/heatmap-test.ts
  projects/safe/src/lib/components/widgets/map/map.component.ts
  projects/safe/src/lib/components/widgets/map/util-test.ts
Labels: enhancement

#1108 refactor/AB#55628_add-random-geojson
  projects/safe/src/lib/components/widgets/map/cluster-test.ts
  projects/safe/src/lib/components/widgets/map/generateFeatureCollection.ts
  projects/safe/src/lib/components/widgets/map/map.component.ts
  projects/safe/src/lib/style/map.scss
Labels: enhancement

#1112 feat/AB#55817_fullscreen_leaflet_map
  .storybook/preview-head.html
  angular.json
  package-lock.json
  package.json
  projects/back-office/src/index.html
  projects/front-office/src/index.html
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/edit-layer-modal.component.ts
  projects/safe/src/lib/components/widgets/map/map.component.ts
Labels: enhancement

#1070 fix: add a save error message when display as grid is selected witout…
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/form-builder/form-builder.component.ts
  projects/safe/src/lib/survey/types.ts
Labels: bug

#1026 fix/OORT-515_users_table_improvments
  projects/safe/src/lib/components/users/users.component.html
  projects/safe/src/lib/components/users/users.component.ts
  projects/safe/src/lib/services/application/application.service.ts
  projects/safe/src/lib/services/download/download.service.ts
  projects/safe/src/lib/views/application-users/application-users.component.ts
  projects/safe/src/lib/views/application-users/components/user-list/user-list.component.ts
Labels: enhancement

#1128 refactor/AB#56423_use-leaflet-packages
  angular.json
  package-lock.json
  package.json
  projects/back-office/src/index.html
  projects/front-office/src/index.html
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  projects/safe/src/lib/components/geospatial-map/layer-styling/layer-styling.component.ts
  projects/safe/src/lib/components/ui/map/interfaces/map.interface.ts
  projects/safe/src/lib/components/ui/map/map-legend/map-legend.component.spec.ts
  projects/safe/src/lib/components/ui/map/map.component.ts
  projects/safe/src/lib/components/ui/map/test/feature-collection-test.ts
  projects/safe/src/lib/components/ui/map/test/heatmap-test.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/edit-layer-modal.component.ts
  projects/safe/src/lib/components/widgets/map/map.component.spec.ts
  projects/safe/src/lib/components/widgets/map/map.component.ts
  projects/safe/src/lib/components/widgets/map/map.module.ts
  projects/safe/src/lib/services/maps/map-controls.service.ts
  projects/safe/src/lib/services/maps/map-layers.service.ts
  projects/safe/src/typings/leaflet/index.d.ts
Labels: refactor

#1136 feat/AB#56615_switch-basemaps
  projects/safe/src/lib/components/ui/map/map.component.ts
  projects/safe/src/lib/components/ui/map/test/basemaps-test.ts
Labels: enhancement

#1124 feat/AB#56137_time-dimension-plugin
  .storybook/preview-head.html
  angular.json
  package-lock.json
  package.json
  projects/back-office/src/index.html
  projects/front-office/src/index.html
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/ui/map/interfaces/map.interface.ts
  projects/safe/src/lib/components/ui/map/map.component.ts
  projects/safe/src/lib/components/ui/map/test/timedimension-test.ts
  projects/safe/src/lib/components/widgets/map-settings/map-forms.ts
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.module.ts
  projects/safe/src/lib/services/maps/map-controls.service.ts
Labels: enhancement

#1138 fix/AB#56185_application-users-table
  projects/safe/src/lib/views/application-users/components/user-list/user-list.component.html
Labels: bug

#1143 AB#56738_improve-fullscreen-modal
  projects/safe/src/lib/components/layout/layout.component.scss
  projects/safe/src/lib/style/styles.scss
Labels: enhancement

#1137 refactor/AB#56621_create-layer-class (wip)
  .prettierrc
  angular.json
  package-lock.json
  package.json
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.html
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  projects/safe/src/lib/components/geospatial-map/layer-styling/layer-styling.component.ts
  projects/safe/src/lib/components/ui/icon-picker/icon-picker.component.html
  projects/safe/src/lib/components/ui/icon-picker/icon-picker.component.scss
  projects/safe/src/lib/components/ui/icon-picker/icon-picker.component.spec.ts
  projects/safe/src/lib/components/ui/icon-picker/icon-picker.component.ts
  projects/safe/src/lib/components/ui/icon-picker/icon-picker.module.ts
  projects/safe/src/lib/components/ui/icon-picker/public-api.ts
  projects/safe/src/lib/components/ui/map/const/fa-icons.ts
  projects/safe/src/lib/components/ui/map/interfaces/layer-legend.type.ts
  projects/safe/src/lib/components/ui/map/interfaces/layer-settings.type.ts
  projects/safe/src/lib/components/ui/map/interfaces/map-layers.interface.ts
  projects/safe/src/lib/components/ui/map/layer.ts
  projects/safe/src/lib/components/ui/map/map-legend/map-legend.component.html
  projects/safe/src/lib/components/ui/map/map-legend/map-legend.component.ts
  projects/safe/src/lib/components/ui/map/map.component.ts
  projects/safe/src/lib/components/ui/map/test/cluster-test.ts
  projects/safe/src/lib/components/ui/map/test/feature-collection-test.ts
  projects/safe/src/lib/components/ui/map/test/heatmap-test.ts
  projects/safe/src/lib/components/ui/map/test/layer-settings-test.ts
  projects/safe/src/lib/components/ui/map/utils/create-div-icon.ts
  projects/safe/src/lib/components/ui/map/utils/get-map-features.ts
  projects/safe/src/lib/components/widgets/map-settings/map-forms.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/edit-layer-modal.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/edit-layer-modal.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/edit-layer-modal.module.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/layer-properties/layer-properties.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/layer-properties/layer-properties.component.scss
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/layer-properties/layer-properties.component.spec.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/layer-properties/layer-properties.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/layer-styling/layer-styling.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/layer-styling/layer-styling.component.scss
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/layer-styling/layer-styling.component.spec.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/layer-styling/layer-styling.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.ts
  projects/safe/src/lib/pipes/icon-display/icon-display.module.ts
  projects/safe/src/lib/pipes/icon-display/icon-display.pipe.spec.ts
  projects/safe/src/lib/pipes/icon-display/icon-display.pipe.ts
  projects/safe/src/lib/pipes/icon-display/public-api.ts
  projects/safe/src/lib/safe.module.ts
  projects/safe/src/lib/services/maps/map-controls.service.ts
  projects/safe/src/lib/services/maps/map-layers.service.ts
  projects/safe/src/lib/style/map.scss
  projects/safe/src/lib/style/styles.scss
  projects/safe/src/public-api.ts
Labels: refactor

#1147 feat/AB#56960_improve-heatmap-legend
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/ui/map/interfaces/layer-legend.type.ts
  projects/safe/src/lib/components/ui/map/layer.ts
  projects/safe/src/lib/components/ui/map/map-legend/map-legend.component.html
  projects/safe/src/lib/components/ui/map/map-legend/map-legend.component.ts
Labels: enhancement

#1146 fix/AB#56908_hide-legend-of-hidden-layers
  projects/safe/src/lib/components/ui/map/layer.ts
  projects/safe/src/lib/components/ui/map/map.component.ts
  projects/safe/src/lib/services/maps/map-controls.service.ts
Labels: bug

#1141 SnackBar check started
  package-lock.json
  package.json
  projects/back-office/src/app/application/pages/add-page/add-page.component.ts
  projects/back-office/src/app/application/pages/form/form.component.ts
  projects/back-office/src/app/application/pages/settings/settings.component.ts
  projects/back-office/src/app/application/pages/workflow/workflow.component.ts
  projects/back-office/src/app/components/duplicate-application-modal/duplicate-application-modal.component.ts
  projects/back-office/src/app/components/duplicate-application-modal/graphql/mutations.ts
  projects/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.ts
  projects/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.ts
  projects/back-office/src/app/dashboard/pages/applications/applications.component.ts
  projects/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  projects/back-office/src/app/dashboard/pages/form-builder/form-builder.component.ts
  projects/back-office/src/app/dashboard/pages/form-records/form-records.component.ts
  projects/back-office/src/app/dashboard/pages/forms/forms.component.ts
  projects/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.ts
  projects/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  projects/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.ts
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/forms-tab/forms-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/resource.component.ts
  projects/back-office/src/app/dashboard/pages/resources/resources.component.ts
  projects/front-office/src/app/dashboard/pages/form/form.component.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/form-modal/form-modal.component.ts
  projects/safe/src/lib/components/form/form.component.ts
  projects/safe/src/lib/components/record-modal/record-modal.component.ts
  projects/safe/src/lib/components/roles/components/group-list/group-list.component.ts
  projects/safe/src/lib/components/roles/components/role-list/role-list.component.ts
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/users/users.component.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
  projects/safe/src/lib/services/application-notifications/application-notifications.service.ts
  projects/safe/src/lib/services/application/application.service.ts
  projects/safe/src/lib/services/form-builder/form-builder.service.ts
  projects/safe/src/lib/views/application-users/application-users.component.ts
  projects/safe/src/lib/views/profile/profile.component.ts
Labels: enhancement, help wanted, refactor

#1153 Fix/oort 602 translation of pagination elements
  projects/back-office/src/app/app.module.ts
  projects/front-office/src/app/app.module.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/users/users.component.ts
  projects/safe/src/lib/utils/paginator-translate.ts
Labels: fix
