Repository ReliefApplications/ems-frontend, pull requests merged in 2023-01, with the labels that each got.

#1050 refactor/AB#51566_show-user-groups-in-FO
  projects/safe/src/lib/components/user-summary/user-roles/user-groups/user-groups.component.ts
  projects/safe/src/lib/components/user-summary/user-roles/user-roles.component.html
  projects/safe/src/lib/components/user-summary/user-roles/user-roles.component.ts
Labels: enhancement

#1049 refactor/AB#51548_hide-grid-add-button
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.html
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
  projects/safe/src/lib/components/widgets/grid/graphql/queries.ts
  projects/safe/src/lib/components/widgets/grid/grid.component.html
  projects/safe/src/lib/components/widgets/grid/grid.component.ts
  projects/safe/src/lib/models/resource.model.ts
Labels: enhancement

#1053 refactor/AB#53288_hide-toolbar-actions-FO
  projects/back-office/src/app/application/application.component.html
  projects/safe/src/lib/components/application-toolbar/application-toolbar.component.html
  projects/safe/src/lib/components/application-toolbar/application-toolbar.component.ts
Labels: enhancement

#1055 Refactor/oort 480 auto cancel graphql subscriptions when possible
  projects/back-office/src/app/app-preview/app-preview.component.ts
  projects/back-office/src/app/app-preview/pages/dashboard/dashboard.component.ts
  projects/back-office/src/app/app-preview/pages/form/form.component.ts
  projects/back-office/src/app/app-preview/pages/role-summary/role-summary.component.ts
  projects/back-office/src/app/app-preview/pages/user-summary/user-summary.component.ts
  projects/back-office/src/app/app-preview/pages/users/users.component.ts
  projects/back-office/src/app/app-preview/pages/workflow/workflow.component.ts
  projects/back-office/src/app/app.component.ts
  projects/back-office/src/app/application/application.component.ts
  projects/back-office/src/app/application/pages/add-page/add-page.component.ts
  projects/back-office/src/app/application/pages/channels/channels.component.ts
  projects/back-office/src/app/application/pages/form/form.component.ts
  projects/back-office/src/app/application/pages/position/position.component.ts
  projects/back-office/src/app/application/pages/role-summary/role-summary.component.ts
  projects/back-office/src/app/application/pages/settings/settings.component.ts
  projects/back-office/src/app/application/pages/subscriptions/subscriptions.component.ts
  projects/back-office/src/app/application/pages/user-summary/user-summary.component.ts
  projects/back-office/src/app/application/pages/users/users.component.ts
  projects/back-office/src/app/application/pages/workflow/components/add-step/add-step.component.ts
  projects/back-office/src/app/application/pages/workflow/workflow.component.ts
  projects/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.ts
  projects/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.ts
  projects/back-office/src/app/dashboard/pages/applications/applications.component.ts
  projects/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  projects/back-office/src/app/dashboard/pages/form-records/form-records.component.ts
  projects/back-office/src/app/dashboard/pages/forms/forms.component.ts
  projects/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.ts
  projects/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  projects/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.ts
  projects/front-office/src/app/app.component.ts
  projects/front-office/src/app/dashboard/dashboard.component.ts
  projects/front-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  projects/front-office/src/app/dashboard/pages/form/form.component.ts
  projects/front-office/src/app/dashboard/pages/role-summary/role-summary.component.ts
  projects/front-office/src/app/dashboard/pages/share/share.component.ts
  projects/front-office/src/app/dashboard/pages/user-summary/user-summary.component.ts
  projects/front-office/src/app/dashboard/pages/users/users.component.ts
  projects/front-office/src/app/dashboard/pages/workflow/workflow.component.ts
  projects/safe/src/lib/components/application-toolbar/application-toolbar.component.ts
  projects/safe/src/lib/components/choose-record-modal/choose-record-modal.component.ts
  projects/safe/src/lib/components/layout/layout.component.ts
  projects/safe/src/lib/components/left-sidenav/left-sidenav.component.ts
  projects/safe/src/lib/components/mapping/mapping.component.ts
  projects/safe/src/lib/components/query-builder/tab-layout-preview/tab-layout-preview.component.ts
  projects/safe/src/lib/components/roles/components/role-list/role-list.component.ts
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/utils/unsubscribe/public-api.ts
  projects/safe/src/lib/components/utils/unsubscribe/unsubscribe.component.html
  projects/safe/src/lib/components/utils/unsubscribe/unsubscribe.component.scss
  projects/safe/src/lib/components/utils/unsubscribe/unsubscribe.component.spec.ts
  projects/safe/src/lib/components/utils/unsubscribe/unsubscribe.component.ts
  projects/safe/src/lib/components/utils/unsubscribe/unsubscribe.module.ts
  projects/safe/src/lib/components/widgets/chart/chart.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
  projects/safe/src/lib/components/widgets/map/map.component.ts
  projects/safe/src/lib/pages/application-distribution-lists/application-distribution-lists.component.ts
  projects/safe/src/lib/pages/application-templates/application-templates.component.ts
  projects/safe/src/lib/pages/profile/profile.component.ts
  projects/safe/src/lib/safe.module.ts
  projects/safe/src/public-api.ts
Labels: refactor

#1056 fix: history would not reload if record was updated
  projects/safe/src/lib/components/record-history/record-history.component.ts
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
Labels: bug

#1048 Fix 1.3.x/AB#26880 aggregation with grids
  projects/safe/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.html
  projects/safe/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.scss
  projects/safe/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.ts
  projects/safe/src/lib/components/aggregation/aggregation-grid/aggregation-grid.module.ts
  projects/safe/src/lib/components/query-builder/query-builder-forms.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  projects/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
  projects/safe/src/lib/services/aggregation/aggregation.service.ts
  projects/safe/src/lib/services/aggregation/graphql/queries.ts
  projects/safe/src/lib/services/grid/grid.service.ts
  projects/safe/src/lib/services/query-builder/query-builder.service.ts
Labels: bug, enhancement

#1058 refactor: change unnecessary queryWatch in query, and add safeUnsubsc…
  projects/safe/src/lib/components/access/edit-access/edit-access.component.ts
  projects/safe/src/lib/components/application-dropdown/application-dropdown.component.ts
  projects/safe/src/lib/components/convert-modal/convert-modal.component.ts
  projects/safe/src/lib/components/graphql-select/graphql-select.component.ts
  projects/safe/src/lib/components/record-dropdown/record-dropdown.component.ts
  projects/safe/src/lib/components/reference-data-dropdown/reference-data-dropdown.component.ts
  projects/safe/src/lib/components/resource-dropdown/resource-dropdown.component.ts
  projects/safe/src/lib/components/role-summary/role-channels/role-channels.component.ts
  projects/safe/src/lib/components/role-summary/role-resources/role-resources.component.ts
  projects/safe/src/lib/components/role-summary/role-users/role-users.component.ts
  projects/safe/src/lib/components/roles/components/group-list/group-list.component.ts
  projects/safe/src/lib/components/roles/components/role-list/role-list.component.ts
  projects/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  projects/safe/src/lib/components/user-summary/user-roles/user-app-roles/user-app-roles.component.ts
  projects/safe/src/lib/components/users/components/add-user/add-user.component.ts
  projects/safe/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-general/map-general.component.ts
Labels: refactor

#1060 feat: add empty components in resources tabs
  projects/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.html
  projects/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.module.ts
  projects/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.html
  projects/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.module.ts
  projects/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.html
  projects/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.ts
  projects/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.module.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
Labels: enhancement

#1061 Fix 1.3.x/AB#53528 create graphql type for metadata
  projects/back-office/src/app/app-preview/pages/form/graphql/queries.ts
  projects/back-office/src/app/application/pages/form/graphql/queries.ts
  projects/back-office/src/app/dashboard/pages/form-answer/graphql/queries.ts
  projects/back-office/src/app/dashboard/pages/form-records/form-records.component.ts
  projects/back-office/src/app/dashboard/pages/form-records/graphql/queries.ts
  projects/back-office/src/app/dashboard/pages/resource/graphql/queries.ts
  projects/back-office/src/app/dashboard/pages/update-record/graphql/queries.ts
  projects/front-office/src/app/dashboard/pages/form/graphql/queries.ts
  projects/safe/src/lib/components/aggregation/aggregation-grid/graphql/queries.ts
  projects/safe/src/lib/components/filter/filter-row/filter-row.component.ts
  projects/safe/src/lib/components/filter/filter.const.ts
  projects/safe/src/lib/components/filter/filter.model.ts
  projects/safe/src/lib/components/form-modal/graphql/queries.ts
  projects/safe/src/lib/components/record-modal/graphql/queries.ts
  projects/safe/src/lib/components/role-summary/graphql/fragments.ts
  projects/safe/src/lib/components/role-summary/graphql/mutations.ts
  projects/safe/src/lib/components/role-summary/graphql/queries.ts
  projects/safe/src/lib/components/role-summary/role-resources/resource-access-filters/resource-access-filters.component.ts
  projects/safe/src/lib/models/form.model.ts
  projects/safe/src/lib/models/metadata.model.ts
  projects/safe/src/lib/models/resource.model.ts
  projects/safe/src/lib/services/form-builder/form-builder.service.ts
  projects/safe/src/lib/services/query-builder/graphql/queries.ts
  projects/safe/src/lib/services/query-builder/query-builder.service.ts
  projects/web-widgets/src/app/components/form/graphql/queries.ts
Labels: enhancement, refactor

#1063 Refactor: tailwind updated with colors primary and secondary
  projects/safe/src/lib/components/applications-summary/components/add-application/add-application.component.html
  projects/safe/src/lib/components/workflow-stepper/components/add-step/add-step.component.html
  projects/safe/src/lib/style/styles.scss
  projects/safe/src/lib/style/theme.scss
  projects/safe/src/lib/style/themes/default/_variables.scss
  projects/safe/src/lib/style/themes/oort/_variables.scss
  tailwind.config.js
Labels: refactor

#1067 Refactor 1.3.0/oort 575 unsubscribe value changes
  projects/safe/src/lib/components/aggregation/aggregation-table/aggregation-table.component.ts
  projects/safe/src/lib/components/filter/filter-row/filter-row.component.ts
  projects/safe/src/lib/components/grid-layout/layout-table/layout-table.component.ts
  projects/safe/src/lib/components/query-builder/query-builder.component.ts
  projects/safe/src/lib/components/query-builder/tab-style/query-style-list/query-style-list.component.ts
  projects/safe/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  projects/safe/src/lib/components/ui/aggregation-builder/forms-dropdown/forms-dropdown.component.ts
  projects/safe/src/lib/components/ui/aggregation-builder/pipeline/expressions/expressions.component.ts
  projects/safe/src/lib/components/ui/aggregation-builder/pipeline/group-stage/group-stage.component.ts
  projects/safe/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.ts
  projects/safe/src/lib/components/ui/aggregation-builder/series-mapping/series-mapping.component.ts
  projects/safe/src/lib/components/widgets/chart-settings/tab-display/tab-display.component.ts
  projects/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.ts
Labels: refactor

#1074 add survey.scss to form and form-build
  projects/safe/src/lib/components/form-builder/form-builder.component.scss
  projects/safe/src/lib/components/form/form.component.scss
Labels: refactor

#1076 fix/AB#54369_fix-storybook
  projects/front-office/src/app/dashboard/dashboard-routing.module.ts
  projects/safe/src/lib/components/applications-summary/applications-summary.stories.ts
  projects/safe/src/lib/components/applications-summary/components/application-summary/application-summary.stories.ts
  projects/safe/src/lib/components/record-summary/record-summary.stories.ts
  projects/safe/src/lib/components/ui/core-grid/grid/grid.stories.ts
  projects/safe/src/lib/components/ui/divider/divider.stories.ts
  projects/safe/src/lib/components/widget-choice/widget-choice.stories.ts
  projects/safe/src/lib/components/workflow-stepper/components/step/step.stories.ts
  projects/safe/src/lib/services/reference-data/reference-data.service.ts
  projects/safe/src/lib/style/styles.scss
  projects/safe/src/lib/views/application-users/application-users.component.ts
  projects/safe/src/lib/views/application-users/components/user-list/user-list.component.ts
  stories/variables.scss
Labels: bug

#1073 feat/AB#54143_geospatial-question
  .storybook/preview-head.html
  package-lock.json
  package.json
  projects/back-office/src/index.html
  projects/front-office/src/index.html
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.html
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.scss
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.spec.ts
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  projects/safe/src/lib/components/geospatial-map/geospatial-map.module.ts
  projects/safe/src/lib/components/geospatial-map/geospatial-map.stories.ts
  projects/safe/src/lib/components/geospatial-map/public-api.ts
  projects/safe/src/lib/survey/components/geospatial.ts
  projects/safe/src/lib/survey/init.ts
Labels: enhancement

#1077 AB#29960 roles ressources filters
  projects/safe/src/lib/components/query-builder/query-builder-forms.ts
  projects/safe/src/lib/components/role-summary/role-resources/permissions.types.ts
  projects/safe/src/lib/components/role-summary/role-resources/role-resources.component.ts
Labels: bug

#1080 refactor/AB#54432_icon-langs-geospatial
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  projects/safe/src/lib/survey/components/geospatial.ts
Labels: enhancement

#1082 refactor/AB#51567_table-styling-with-tailwind
  projects/back-office/src/app/application/pages/channels/channels.component.html
  projects/back-office/src/app/application/pages/position/position.component.html
  projects/back-office/src/app/application/pages/subscriptions/subscriptions.component.html
  projects/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.html
  projects/back-office/src/app/dashboard/pages/applications/applications.component.html
  projects/back-office/src/app/dashboard/pages/forms/forms.component.html
  projects/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.html
  projects/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.html
  projects/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.html
  projects/back-office/src/app/dashboard/pages/resource/forms-tab/forms-tab.component.html
  projects/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.html
  projects/back-office/src/app/dashboard/pages/resources/resources.component.html
  projects/safe/src/lib/components/aggregation/aggregation-table/aggregation-table.component.html
  projects/safe/src/lib/components/distribution-lists/distribution-lists.component.html
  projects/safe/src/lib/components/grid-layout/layout-table/layout-table.component.html
  projects/safe/src/lib/components/query-builder/tab-style/query-style-list/query-style-list.component.html
  projects/safe/src/lib/components/role-summary/role-features/role-dashboards/role-dashboards.component.html
  projects/safe/src/lib/components/role-summary/role-features/role-forms/role-forms.component.html
  projects/safe/src/lib/components/role-summary/role-features/role-workflows/role-workflows.component.html
  projects/safe/src/lib/components/role-summary/role-resources/resource-fields/resource-fields.component.html
  projects/safe/src/lib/components/role-summary/role-resources/role-resources.component.html
  projects/safe/src/lib/components/role-summary/role-users/role-users.component.html
  projects/safe/src/lib/components/roles/components/group-list/group-list.component.html
  projects/safe/src/lib/components/roles/components/role-list/role-list.component.html
  projects/safe/src/lib/components/skeleton/skeleton-table/skeleton-table.component.html
  projects/safe/src/lib/components/templates/templates.component.html
  projects/safe/src/lib/components/users/users.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-clorophlets/map-clorophlets.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-online-layers/map-online-layers.component.html
  projects/safe/src/lib/style/styles.scss
  projects/safe/src/lib/views/application-users/components/user-list/user-list.component.html
  projects/safe/src/lib/views/profile/profile.component.html
Labels: refactor

#1069 Fix 1.4.0/oort 576 clean up 1.4
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.html
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.scss
  projects/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.module.ts
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/edit-calculated-field-modal/edit-calculated-field-modal.component.html
  projects/safe/src/lib/components/widget/widget.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/add-card/add-card.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/card-modal.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source-tab.component.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/data-source-tab/data-source.module.ts
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/display-tab/display-tab.component.html
  projects/safe/src/lib/components/widgets/summary-card-settings/card-modal/graphql/queries.ts
  projects/safe/src/lib/components/widgets/summary-card/graphql/queries.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.ts
  projects/safe/src/lib/components/widgets/summary-card/summary-card.component.html
Labels: enhancement, refactor

#1086 feat: add map bounds logger
  projects/safe/src/lib/components/widgets/map/map.component.ts
Labels: enhancement

#1084 add control layers tree
  package-lock.json
  package.json
  projects/safe/src/lib/components/widgets/map/map.component.scss
  projects/safe/src/lib/components/widgets/map/map.component.ts
Labels: enhancement

#1087 feat: add icons to survey custom questions
  projects/safe/src/lib/survey/components/owner.ts
  projects/safe/src/lib/survey/components/resource.ts
  projects/safe/src/lib/survey/components/resources.ts
  projects/safe/src/lib/survey/components/users.ts
  stories/assets/owners.svg
  stories/assets/resource.svg
  stories/assets/resources.svg
  stories/assets/users.svg
Labels: enhancement

#1088 Refactor/oort 584 create editable text component
  projects/back-office/src/app/application/pages/form/form.component.html
  projects/back-office/src/app/application/pages/form/form.component.ts
  projects/back-office/src/app/application/pages/form/form.module.ts
  projects/back-office/src/app/application/pages/workflow/workflow.component.html
  projects/back-office/src/app/application/pages/workflow/workflow.component.ts
  projects/back-office/src/app/application/pages/workflow/workflow.module.ts
  projects/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  projects/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  projects/back-office/src/app/dashboard/pages/dashboard/dashboard.module.ts
  projects/back-office/src/app/dashboard/pages/form-builder/form-builder.component.html
  projects/back-office/src/app/dashboard/pages/form-builder/form-builder.component.ts
  projects/back-office/src/app/dashboard/pages/form-builder/form-builder.module.ts
  projects/safe/src/lib/components/editable-text/editable-text.component.html
  projects/safe/src/lib/components/editable-text/editable-text.component.scss
  projects/safe/src/lib/components/editable-text/editable-text.component.spec.ts
  projects/safe/src/lib/components/editable-text/editable-text.component.ts
  projects/safe/src/lib/components/editable-text/editable-text.module.ts
  projects/safe/src/lib/components/editable-text/public-api.ts
  projects/safe/src/lib/safe.module.ts
  projects/safe/src/public-api.ts
Labels: refactor

#1089 AB#54359 feat: create a left and right clone for each layers
  projects/safe/src/lib/components/widgets/map/geojson-test.ts
  projects/safe/src/lib/components/widgets/map/map.component.ts
Labels: enhancement

#1092 Feat 1.4.0/ab#54503 layers properties
  package-lock.json
  package.json
  projects/safe/src/lib/components/widgets/map-settings/map-forms.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/edit-layer-modal.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/edit-layer-modal.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/edit-layer-modal/edit-layer-modal.module.ts
  projects/safe/src/lib/components/widgets/map-settings/map-layers/map-layers.component.ts
  projects/safe/src/lib/components/widgets/map/map.component.ts
Labels: enhancement

#1093 AB#54822 - updated map properties tab
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.scss
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.ts
  projects/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.module.ts
  projects/safe/src/lib/components/widgets/map-settings/map-settings.component.html
Labels: enhancement

#1090 AB#54507 - GeoJSON styling
  package-lock.json
  package.json
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.html
  projects/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  projects/safe/src/lib/components/geospatial-map/geospatial-map.module.ts
  projects/safe/src/lib/components/geospatial-map/layer-styling/layer-styling.component.html
  projects/safe/src/lib/components/geospatial-map/layer-styling/layer-styling.component.scss
  projects/safe/src/lib/components/geospatial-map/layer-styling/layer-styling.component.spec.ts
  projects/safe/src/lib/components/geospatial-map/layer-styling/layer-styling.component.ts
  projects/safe/src/lib/components/geospatial-map/layer-styling/layer-styling.module.ts
  projects/safe/src/lib/safe.module.ts
  projects/safe/src/public-api.ts
Labels: enhancement

#1098 Fix 1.3.x/AB#54757 metadata optimization
  projects/safe/src/lib/components/role-summary/graphql/fragments.ts
  projects/safe/src/lib/components/role-summary/graphql/mutations.ts
  projects/safe/src/lib/components/role-summary/role-resources/resource-access-filters/resource-access-filters.component.html
  projects/safe/src/lib/components/role-summary/role-resources/resource-access-filters/resource-access-filters.component.ts
  projects/safe/src/lib/components/role-summary/role-resources/resource-fields/resource-fields.component.html
  projects/safe/src/lib/components/role-summary/role-resources/resource-fields/resource-fields.component.ts
  projects/safe/src/lib/components/role-summary/role-resources/role-resources.component.html
  projects/safe/src/lib/components/role-summary/role-resources/role-resources.component.ts
Labels: enhancement

#1101 feat/AB#55059_error-message-permission-guard
  projects/safe/src/i18n/en.json
  projects/safe/src/i18n/fr.json
  projects/safe/src/i18n/test.json
  projects/safe/src/lib/guards/permission.guard.ts
Labels: enhancement
