Repository ReliefApplications/ems-frontend, pull requests merged in 2023-07, with the labels that each got.

#1597 Feat/ab#68112 add missing translations
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/i18n/tinymce/fr_FR.js
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/unique-value-renderer/unique-value-renderer.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/unique-value-renderer/unique-value-renderer.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  libs/safe/src/lib/const/tinymce.const.ts
  libs/safe/src/lib/services/map/map-controls.service.ts
Labels: enhancement

#1598 feat: add survey scss import in form modal
  libs/safe/src/lib/components/form-modal/form-modal.component.scss
Labels: enhancement

#1599 fix/resource-creation-on-search-grid
  libs/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/safe/src/lib/survey/components/resource.ts
  libs/safe/src/lib/survey/components/resources.ts
  libs/safe/src/lib/survey/components/utils.ts
Labels: bug

#1603 Fix/ab#68736 notifications pulljobs not working
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.ts
Labels: bug

#1600 feat/AB#41414_date_operations
  apps/back-office/src/app/graphql.module.ts
  apps/front-office/src/app/graphql.module.ts
  apps/web-widgets/src/app/graphql.module.ts
Labels: bug, enhancement

#1607 improves a bit the cron expression modal
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.ts
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.html
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.scss
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.ts
  libs/safe/src/lib/components/cron-expression-control/cron-expression-control.component.ts
Labels: bug

#1611 feat: add user variables on form
  libs/safe/src/lib/components/form-builder/form-builder.component.ts
  libs/safe/src/lib/services/form-builder/form-builder.service.ts
  libs/safe/src/lib/services/form-helper/form-helper.service.ts
Labels: enhancement

#1612 feat/AB#68929_remove_important_from_tailwind_config
  apps/back-office/src/app/components/custom-style/custom-style.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  libs/safe/src/lib/components/button-action/button-action.component.html
  libs/safe/src/lib/components/dashboard-filter/directives/drawer-positioner/drawer-positioner.directive.ts
  libs/safe/src/lib/components/geofields-listbox/geofields-listbox.component.html
  libs/safe/src/lib/components/layout/layout.component.html
  libs/safe/src/lib/components/layout/layout.component.scss
  libs/safe/src/lib/components/widget-grid/widget-grid.component.html
  libs/safe/src/lib/components/widgets/chart/chart.component.html
  libs/safe/src/lib/components/widgets/common/display-settings/display-settings.component.html
  libs/safe/src/lib/components/widgets/editor/editor.component.html
  libs/safe/src/lib/components/widgets/grid/grid.component.html
  libs/safe/src/lib/components/widgets/map/map.component.html
  libs/safe/src/lib/components/widgets/summary-card/summary-card.component.html
  libs/ui/src/lib/button/button.component.ts
  libs/ui/src/lib/expansion-panel/expansion-panel.component.html
  libs/ui/src/lib/expansion-panel/expansion-panel.component.scss
  libs/ui/src/lib/paginator/paginator.component.html
  libs/ui/src/lib/toggle/toggle.component.scss
  tailwind.config.js
Labels: enhancement

#1615 fix/page-form-edit-name
  apps/back-office/src/app/application/pages/form/form.component.ts
Labels: bug

#1616 fix: files uploaded before addRecord
  libs/safe/src/lib/components/form/form.component.ts
  libs/safe/src/lib/services/form-builder/form-builder.service.ts
  libs/safe/src/lib/services/form-helper/form-helper.service.ts
Labels: bug

#1623 fix/AB#68944-layers-fields-popup
  libs/safe/src/lib/components/ui/map/interfaces/layer-settings.type.ts
  libs/safe/src/lib/components/ui/map/map-popup/map-popup.service.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-fields/layer-fields.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-fields/layer-fields.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-popup/fields-element/fields-element.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-popup/layer-popup.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-popup/text-element/text-element.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/layer-styling.component.ts
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/unique-value-renderer/unique-value-renderer.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-forms.ts
  libs/safe/src/lib/models/layer.model.ts
  libs/safe/src/lib/services/map/graphql/queries.ts
Labels: bug

#1622 Fix/ab#69057 scss not available application custom styling
  apps/back-office/src/app/components/custom-style/custom-style.component.ts
  libs/safe/src/index.ts
  libs/safe/src/lib/services/application/application.service.ts
Labels: bug

#1624 fix: Keeping current map state when filtering layers with dashboard filters
  libs/safe/src/lib/components/ui/map/layer.ts
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/components/widgets/map-settings/add-layer-modal/add-layer-modal.component.html
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.html
Labels: bug

#1631 Fix 2.1.x/db#69267 fields showing when no layout selected fix
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
Labels: fix

#1664 fix/AB#70722-resource-modal-blank-page
  libs/safe/src/lib/services/form/form.service.ts
  libs/safe/src/lib/survey/components/resource.ts
  libs/safe/src/lib/survey/components/resources.ts
  libs/safe/src/lib/survey/components/utils.ts
  libs/safe/src/lib/survey/init.ts
Labels: bug

#1649 #69896 misalignment between input and wrapper form date picker
  libs/safe/src/lib/style/survey.scss
Labels: fix

#1669 fix/workflow-step-never-loads
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
Labels: bug

#1678 Fix/ab#71072 add a loading icon when opening the select questions
  libs/safe/src/lib/components/ui/core-grid/array-filter-menu/array-filter-menu.component.ts
  libs/safe/src/lib/components/ui/core-grid/dropdown-filter-menu/dropdown-filter-menu.component.ts
  libs/safe/src/lib/survey/widgets/dropdown-widget.ts
  libs/safe/src/lib/survey/widgets/tagbox-widget.ts
  libs/safe/src/lib/survey/widgets/utils/common-list-filters.ts
Labels: enhancement
