Repository ReliefApplications/ems-frontend, pull requests merged in 2023-09, with the labels that each got.

#1778 Feat 2.0.x/ab#73566 update GitHub actions for storybook
  .github/workflows/github-pages.yml
  .github/workflows/storybook.yml
Labels: enhancement

#1783 bug/AB#74215_DB-Some-popup-could-send-an-issue-when-trying-to-open-them
  libs/safe/src/lib/components/ui/map/layer.ts
  libs/safe/src/lib/components/ui/map/map-popup/map-popup.service.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
Labels: bug

#1791 AB#2374242 DB - Kendo popups not working in fullscreen
  libs/safe/src/lib/survey/widgets/dropdown-widget.ts
  libs/safe/src/lib/survey/widgets/tagbox-widget.ts
Labels: bug

#1790 refactor/AB#74219_order-ref-data-select
  libs/safe/src/lib/components/reference-data-dropdown/graphql/queries.ts
Labels: enhancement

#1793 AB#68171 - Tabs widget
  apps/back-office/src/app/application/pages/add-page/add-page.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/environments/environment.oort.local.ts
  libs/safe/src/index.ts
  libs/safe/src/lib/components/custom-widget-style/custom-widget-style.component.html
  libs/safe/src/lib/components/custom-widget-style/custom-widget-style.component.scss
  libs/safe/src/lib/components/custom-widget-style/custom-widget-style.component.spec.ts
  libs/safe/src/lib/components/custom-widget-style/custom-widget-style.component.ts
  libs/safe/src/lib/components/widget/widget.component.html
  libs/safe/src/lib/components/widget/widget.module.ts
  libs/safe/src/lib/components/widgets/editor/editor.component.html
  libs/safe/src/lib/components/widgets/tabs-settings/custom-widget-style-modal/custom-widget-style-modal.component.html
  libs/safe/src/lib/components/widgets/tabs-settings/custom-widget-style-modal/custom-widget-style-modal.component.scss
  libs/safe/src/lib/components/widgets/tabs-settings/custom-widget-style-modal/custom-widget-style-modal.component.spec.ts
  libs/safe/src/lib/components/widgets/tabs-settings/custom-widget-style-modal/custom-widget-style-modal.component.ts
  libs/safe/src/lib/components/widgets/tabs-settings/tab-main/tab-main.component.html
  libs/safe/src/lib/components/widgets/tabs-settings/tab-main/tab-main.component.scss
  libs/safe/src/lib/components/widgets/tabs-settings/tab-main/tab-main.component.spec.ts
  libs/safe/src/lib/components/widgets/tabs-settings/tab-main/tab-main.component.ts
  libs/safe/src/lib/components/widgets/tabs-settings/tab-main/tab-main.module.ts
  libs/safe/src/lib/components/widgets/tabs-settings/tab-settings/tab-settings.component.html
  libs/safe/src/lib/components/widgets/tabs-settings/tab-settings/tab-settings.component.scss
  libs/safe/src/lib/components/widgets/tabs-settings/tab-settings/tab-settings.component.spec.ts
  libs/safe/src/lib/components/widgets/tabs-settings/tab-settings/tab-settings.component.ts
  libs/safe/src/lib/components/widgets/tabs-settings/tab-settings/tab-settings.module.ts
  libs/safe/src/lib/components/widgets/tabs-settings/tabs-settings.component.html
  libs/safe/src/lib/components/widgets/tabs-settings/tabs-settings.component.scss
  libs/safe/src/lib/components/widgets/tabs-settings/tabs-settings.component.spec.ts
  libs/safe/src/lib/components/widgets/tabs-settings/tabs-settings.component.ts
  libs/safe/src/lib/components/widgets/tabs-settings/tabs-settings.form.ts
  libs/safe/src/lib/components/widgets/tabs-settings/tabs-settings.module.ts
  libs/safe/src/lib/components/widgets/tabs/tab/tab.component.html
  libs/safe/src/lib/components/widgets/tabs/tab/tab.component.scss
  libs/safe/src/lib/components/widgets/tabs/tab/tab.component.spec.ts
  libs/safe/src/lib/components/widgets/tabs/tab/tab.component.ts
  libs/safe/src/lib/components/widgets/tabs/tab/tab.module.ts
  libs/safe/src/lib/components/widgets/tabs/tabs.component.html
  libs/safe/src/lib/components/widgets/tabs/tabs.component.scss
  libs/safe/src/lib/components/widgets/tabs/tabs.component.spec.ts
  libs/safe/src/lib/components/widgets/tabs/tabs.component.ts
  libs/safe/src/lib/components/widgets/tabs/tabs.module.ts
  libs/safe/src/lib/models/dashboard.model.ts
  libs/safe/src/lib/safe.module.ts
  libs/ui/src/lib/tabs/tabs.component.html
Labels: enhancement

#1787 feat/AB#74239_DB-Improve-layout-of-map-popup
  libs/safe/src/lib/components/ui/map/map-popup/map-popup.component.html
  libs/safe/src/lib/components/ui/map/utils/create-div-icon.ts
  libs/safe/src/lib/style/map.scss
  libs/safe/src/lib/style/styles.scss
Labels: bug, enhancement

#1796 feat/IM-23_add-afterRecordDeselection
  libs/safe/src/lib/services/form-builder/form-builder.service.ts
  libs/safe/src/lib/survey/components/resource.ts
  libs/safe/src/lib/survey/components/resources.ts
  libs/safe/src/lib/survey/components/utils.ts
Labels: enhancement

#1789 OORT-feat/IM-16-verification-of-already-existing-records
  apps/back-office/src/app/app-preview/pages/form/graphql/queries.ts
  apps/back-office/src/app/application/pages/form/graphql/queries.ts
  apps/back-office/src/app/dashboard/pages/form-answer/graphql/queries.ts
  apps/back-office/src/app/dashboard/pages/form-builder/graphql/queries.ts
  apps/web-widgets/src/app/components/form/graphql/queries.ts
  libs/safe/src/lib/components/form-modal/form-modal.component.ts
  libs/safe/src/lib/components/form/form.component.ts
  libs/safe/src/lib/components/record-modal/record-modal.component.ts
  libs/safe/src/lib/services/query-builder/query-builder.service.ts
  libs/safe/src/lib/survey/custom-functions.ts
  libs/safe/src/lib/survey/functions/addDays.ts
  libs/safe/src/lib/survey/functions/addTime.ts
  libs/safe/src/lib/survey/functions/createdAt.ts
  libs/safe/src/lib/survey/functions/createdBy.ts
  libs/safe/src/lib/survey/functions/elementAt.ts
  libs/safe/src/lib/survey/functions/getAidsGiven.ts
  libs/safe/src/lib/survey/functions/getField.ts
  libs/safe/src/lib/survey/functions/getMatrixTitles.ts
  libs/safe/src/lib/survey/functions/getTotalAids.ts
  libs/safe/src/lib/survey/functions/getWorkflowContext.ts
  libs/safe/src/lib/survey/functions/id.ts
  libs/safe/src/lib/survey/functions/index.ts
  libs/safe/src/lib/survey/functions/intersect.ts
  libs/safe/src/lib/survey/functions/length.ts
  libs/safe/src/lib/survey/functions/listColsForRows.ts
  libs/safe/src/lib/survey/functions/listRowsWithColValue.ts
  libs/safe/src/lib/survey/functions/modifiedAt.ts
  libs/safe/src/lib/survey/functions/nl2br.ts
  libs/safe/src/lib/survey/functions/searchEnterpriseName.ts
  libs/safe/src/lib/survey/functions/summarizeAids.ts
  libs/safe/src/lib/survey/functions/weekday.ts
  libs/safe/src/lib/survey/init.ts
  libs/safe/src/lib/survey/types.ts
Labels: enhancement

#1754 OORT-fix/IM-8-date-format-change-by-preference
  libs/safe/src/lib/survey/widgets/text-widget.ts
  libs/safe/src/lib/survey/widgets/utils/date-time-formats.ts
Labels: bug

#1788 OORT-feat/IM-28-replace-grid-actions-menu-if-single-action
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/query-builder/query-builder-forms.ts
  libs/safe/src/lib/components/ui/core-grid/core-grid.component.html
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/safe/src/lib/components/ui/core-grid/models/grid-layout.model.ts
  libs/safe/src/lib/components/ui/core-grid/row-actions/row-actions.component.html
  libs/safe/src/lib/components/ui/core-grid/row-actions/row-actions.component.ts
  libs/safe/src/lib/components/widgets/grid-settings/grid-settings.component.html
  libs/safe/src/lib/components/widgets/grid-settings/grid-settings.component.ts
Labels: enhancement

#1774 OORT-feat/IM-3-custom-function-to-change-pages
  libs/safe/src/lib/services/form-builder/form-builder.service.ts
  libs/safe/src/lib/survey/global-properties/others.ts
Labels: enhancement

#1776 OORT-feat/IM-21-temporary-records-optional
  libs/safe/src/lib/components/form-modal/form-modal.component.ts
  libs/safe/src/lib/components/resource-modal/resource-modal.component.ts
  libs/safe/src/lib/survey/components/resource.ts
  libs/safe/src/lib/survey/components/resources.ts
  libs/safe/src/lib/survey/components/utils.ts
  libs/safe/src/lib/survey/types.ts
Labels: enhancement

#1751 OORT-feat/OORT-671-readOnly-for-add-record
  libs/safe/src/lib/components/form/form.component.ts
Labels: enhancement

#1809 bugfix/date-filter-alignment-in-tab-filter
  libs/safe/src/lib/components/query-builder/date-filter-editor/date-filter-editor.component.html
  libs/safe/src/lib/components/query-builder/date-filter-editor/date-filter-editor.component.scss
Labels: bug

#1771 refactor/AB#61061_update-apollo
  apps/back-office/src/app/components/custom-style/custom-style.component.ts
  apps/back-office/src/app/components/custom-style/graphql/mutations.ts
  apps/back-office/src/app/graphql.module.ts
  apps/front-office/src/app/graphql.module.ts
  apps/web-widgets/src/app/graphql.module.ts
  libs/safe/src/lib/components/form-modal/graphql/mutations.ts
  libs/safe/src/lib/components/form/graphql/mutations.ts
  libs/safe/src/lib/services/auth-interceptor/auth-interceptor.service.ts
  libs/safe/src/lib/services/download/download.service.ts
  libs/safe/src/lib/services/form-helper/form-helper.service.ts
  package-lock.json
  package.json
Labels: enhancement, refactor

#1813 Feat/ab#74575 remove bookmarks from map
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/map-sidenav-controls.component.html
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/map-sidenav-controls.component.ts
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu/sidenav-controls-menu.component.html
  libs/safe/src/lib/components/ui/map/map-sidenav-controls/sidenav-controls-menu/sidenav-controls-menu.component.ts
Labels: enhancement

#1811 feat/AB#74573_hide_page_header_full_screen_button_front_office
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.html
Labels: enhancement

#1750 Feat 2.1.x/db#65456 sorting fields widget option improvements
  libs/safe/src/lib/components/ui/core-grid/core-grid.component.scss
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/safe/src/lib/components/ui/core-grid/grid/grid.constants.ts
  libs/safe/src/lib/components/widgets/common/sorting-settings/sorting-settings.component.html
  libs/safe/src/lib/components/widgets/editor-settings/record-selection-tab/record-selection-tab.component.html
  libs/safe/src/lib/components/widgets/grid/grid.component.html
  libs/safe/src/lib/components/widgets/grid/grid.component.ts
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  libs/safe/src/lib/components/widgets/summary-card/summary-card.component.html
  libs/safe/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/ui/src/lib/paginator/paginator.component.html
  libs/ui/src/lib/paginator/paginator.component.ts
  libs/ui/src/lib/select-menu/select-menu.component.ts
Labels: enhancement

#1818 fixed sorting tab in summary card settings
  libs/safe/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
Labels: bug

#1827 Fix 2.x/ab#74676 db global scrollbar style
  libs/safe/src/lib/style/styles.scss
  libs/ui/src/style/styles.scss
Labels: bug

#1829 fix/AB#71655-filter-applied-only-saved-aggregation-twice
  libs/safe/src/lib/components/filter/filter-row/filter-row.component.ts
Labels: bug

#1815 OORT-fix/IM-3-custom-function-to-change-pages
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/services/form-builder/form-builder.service.ts
Labels: bug

#1821 OORT-fix/IM-45_workflow-context-withm-multiple-grids
  libs/safe/src/lib/components/widgets/grid/grid.component.ts
  libs/safe/src/lib/services/form-builder/form-builder.service.ts
  libs/safe/src/lib/services/form-helper/form-helper.service.ts
  libs/safe/src/lib/services/workflow/workflow.service.ts
Labels: bug

#1834 fix/AB#75065-menu-items-overlapping-firefox
  libs/safe/src/lib/components/navbar/navbar.component.scss
Labels: bug

#1800 feat/OORT-634-send-email-from-dataset-v2
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/safe/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
  libs/safe/src/lib/components/widgets/grid/grid.component.ts
Labels: enhancement

#1843 Feat/ab#74663 open settings when creating new widget
  libs/safe/src/lib/components/widget-grid/widget-grid.component.ts
Labels: enhancement

#1842 Ab#75139 remove dashboard link popup
  apps/back-office/src/app/dashboard/pages/dashboard/components/share-url/share-url.component.css
  apps/back-office/src/app/dashboard/pages/dashboard/components/share-url/share-url.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/share-url/share-url.component.spec.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/share-url/share-url.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.module.ts
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/lib/style/styles.scss
  libs/ui/src/style/styles.scss
Labels: enhancement

#1846 feat/AB#75270_refactor_document_usage
  apps/back-office/src/app/components/custom-style/custom-style.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/web-widgets/src/app/app.component.ts
  apps/web-widgets/src/app/app.module.ts
  apps/web-widgets/src/app/utils/overlay-container.ts
  libs/shared/src/lib/components/custom-widget-style/custom-widget-style.component.ts
  libs/shared/src/lib/components/editor-control/editor-control.component.ts
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/components/ui/core-grid/date-filter-menu/date-filter-menu.component.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/components/ui/map/controls/legend.control.ts
  libs/shared/src/lib/components/ui/map/layer.ts
  libs/shared/src/lib/components/ui/map/map-popup/map-popup.service.ts
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/ui/map/utils/create-div-icon.ts
  libs/shared/src/lib/components/widget/widget.component.ts
  libs/shared/src/lib/components/widgets/chart/chart.component.ts
  libs/shared/src/lib/services/application/application.service.ts
  libs/shared/src/lib/services/download/download.service.ts
  libs/shared/src/lib/services/editor/editor.service.ts
  libs/shared/src/lib/services/form/form.service.ts
  libs/shared/src/lib/services/map/arcgis.service.ts
  libs/shared/src/lib/services/map/map-layers.service.ts
  libs/shared/src/lib/survey/components/resource.ts
  libs/shared/src/lib/survey/components/resources.ts
  libs/shared/src/lib/survey/components/utils.ts
  libs/shared/src/lib/survey/global-properties/tooltip.ts
  libs/shared/src/lib/survey/init.ts
  libs/shared/src/lib/survey/render-global-properties.ts
  libs/shared/src/lib/survey/widgets/comment-widget.ts
  libs/shared/src/lib/survey/widgets/dropdown-widget.ts
  libs/shared/src/lib/survey/widgets/tagbox-widget.ts
  libs/shared/src/lib/survey/widgets/text-widget.ts
  libs/shared/src/lib/utils/parser/utils.ts
  libs/ui/src/lib/graphql-select/graphql-select.component.ts
Labels: enhancement

#1844 Fix - French translation to "edit from"
  apps/back-office/src/app/application/pages/channels/components/edit-channel-modal/edit-channel-modal.component.html
  apps/back-office/src/app/application/pages/form/form.component.html
  apps/back-office/src/app/application/pages/position/components/position-modal/position-modal.component.html
  apps/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.html
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/record-modal/record-modal.component.html
Labels: enhancement

#1831 feat/AB#74114_add_tooltip_to_grid_columns_that_overflow
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/ui/src/lib/tooltip/tooltip.directive.ts
Labels: bug, enhancement

#1762 feat/AB#73441_build_custom_expression_builder
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/application/application.component.ts
  libs/shared/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.html
  libs/shared/src/lib/components/cron-expression-control/cron-expression-control-modal/cron-expression-control-modal.component.ts
  libs/shared/src/lib/components/cron-expression-control/cron-expression-control.component.ts
  libs/shared/src/lib/components/cron-expression-control/cron-expression-control.module.ts
  libs/ui/src/index.ts
  libs/ui/src/lib/cron-editor/cron-editor.component.html
  libs/ui/src/lib/cron-editor/cron-editor.component.scss
  libs/ui/src/lib/cron-editor/cron-editor.component.spec.ts
  libs/ui/src/lib/cron-editor/cron-editor.component.stories.ts
  libs/ui/src/lib/cron-editor/cron-editor.component.ts
  libs/ui/src/lib/cron-editor/cron-editor.module.ts
  libs/ui/src/lib/cron-editor/enum/enums.ts
  libs/ui/src/lib/cron-editor/options/cron.options.ts
  libs/ui/src/lib/cron-editor/time-picker/time-picker.component.html
  libs/ui/src/lib/cron-editor/time-picker/time-picker.component.scss
  libs/ui/src/lib/cron-editor/time-picker/time-picker.component.spec.ts
  libs/ui/src/lib/cron-editor/time-picker/time-picker.component.ts
  libs/ui/src/lib/cron-editor/time-picker/time-picker.module.ts
  libs/ui/src/lib/ui.module.ts
  package.json
Labels: enhancement

#1854 OORT-fix/IM-9_multiple-redirects-on-login
  apps/back-office/src/app/guards/access.guard.ts
  apps/back-office/src/app/guards/auth.guard.ts
  apps/front-office/src/app/app.component.ts
  apps/front-office/src/app/guards/auth.guard.ts
Labels: bug

#1845 Oort feat/im 59 add get number of members custom function
  apps/back-office/src/themes/alimentaide/alimentaide.prod.ts
  apps/front-office/src/themes/alimentaide/alimentaide.prod.ts
  libs/safe/src/lib/survey/functions/getNumberOfMembers.ts
  libs/safe/src/lib/survey/functions/index.ts
Labels: enhancement

#1863 Oort feat/im 69 add possibility to start on last entry of dynamic panel
  libs/safe/src/lib/services/form-builder/form-builder.service.ts
  libs/safe/src/lib/survey/global-properties/others.ts
Labels: enhancement

#1870 Fix typing issue when saving layers
  libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
Labels: bug

#1867 feat/AB#75343_Replace-checkbox-tree-with-kendo-component
  apps/back-office/src/app/app-preview/pages/workflow/workflow.component.ts
  apps/back-office/src/app/application/pages/position-attributes/position-attributes.component.ts
  apps/back-office/src/app/components/custom-style/custom-style.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.ts
  libs/shared/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.ts
  libs/shared/src/lib/components/checkbox-tree/checkbox-tree.component.html
  libs/shared/src/lib/components/checkbox-tree/checkbox-tree.component.scss
  libs/shared/src/lib/components/checkbox-tree/checkbox-tree.component.spec.ts
  libs/shared/src/lib/components/checkbox-tree/checkbox-tree.component.ts
  libs/shared/src/lib/components/checkbox-tree/checkbox-tree.module.ts
  libs/shared/src/lib/components/checkbox-tree/public-api.ts
  libs/shared/src/lib/components/geofields-listbox/edit-geofield/edit-geofield.component.ts
  libs/shared/src/lib/components/query-builder/query-builder.module.ts
  libs/shared/src/lib/components/query-builder/tab-style/query-style/query-style.component.html
  libs/shared/src/lib/components/query-builder/tab-style/query-style/query-style.component.scss
  libs/shared/src/lib/components/query-builder/tab-style/query-style/query-style.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.ts
  libs/shared/src/lib/components/widgets/tabs-settings/tab-settings/tab-settings.component.ts
  libs/shared/src/lib/components/widgets/tabs/tabs.component.ts
  libs/shared/src/lib/style/styles.scss
  libs/styles/src/lib/tailwind/tailwind.scss
  package-lock.json
  package.json
Labels: enhancement

#1864 Oort fix/im 57 translation of date questions
  apps/back-office/src/app/app.module.ts
  apps/front-office/src/app/app.module.ts
  apps/web-widgets/src/app/app.module.ts
  libs/safe/src/lib/components/preferences-modal/preferences-modal.component.ts
Labels: enhancement

#1877 Ab#75576 remove expand option for map widgets
  libs/shared/src/lib/components/widget-grid/floating-options/floating-options.component.html
  libs/shared/src/lib/components/widget-grid/floating-options/floating-options.component.ts
  libs/shared/src/lib/components/widget-grid/widget-grid.component.html
Labels: enhancement

#1505 Feat/ab#67174 abc bin page
  apps/back-office/src/app/application/application-routing.module.ts
  apps/back-office/src/app/application/application.component.ts
  apps/back-office/src/app/application/pages/archive/archive-routing.module.ts
  apps/back-office/src/app/application/pages/archive/archive.component.html
  apps/back-office/src/app/application/pages/archive/archive.component.scss
  apps/back-office/src/app/application/pages/archive/archive.component.ts
  apps/back-office/src/app/application/pages/archive/archive.module.ts
  apps/back-office/src/app/application/pages/archive/graphql/queries.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/index.ts
  libs/shared/src/lib/components/applications-archive/applications-archive.component.html
  libs/shared/src/lib/components/applications-archive/applications-archive.component.scss
  libs/shared/src/lib/components/applications-archive/applications-archive.component.spec.ts
  libs/shared/src/lib/components/applications-archive/applications-archive.component.ts
  libs/shared/src/lib/components/applications-archive/applications-archive.module.ts
  libs/shared/src/lib/components/applications-archive/public-api.ts
  libs/shared/src/lib/models/page.model.ts
  libs/shared/src/lib/services/application/application.service.ts
  libs/shared/src/lib/services/application/graphql/mutations.ts
  libs/shared/src/lib/shared.module.ts
  libs/shared/src/lib/survey/components/resources.ts
Labels: enhancement

#1836 fix/AB#75146_path_is_sometimes_lost_after_authentication
  libs/safe/src/lib/services/auth/auth.service.ts
Labels: bug

#1889 feat/AB#75739_bundle_analyzer_setup
  README.md
  package-lock.json
  package.json
Labels: enhancement

#1881 Oort feat im 64 add a delete translation option
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/survey/functions/removeKeyFromJSON.ts
  libs/shared/src/lib/survey/global-properties/others.ts
Labels: enhancement

#1895 Oort feat/im 75 add application context to be used in surveyjs expressions
  libs/shared/src/lib/services/form-builder/form-builder.service.ts
  libs/shared/src/lib/services/form-helper/form-helper.service.ts
Labels: enhancement

#1887 Oort feat/im 70 add ability to duplicate resource
  apps/back-office/src/app/dashboard/pages/resources/graphql/mutations.ts
  apps/back-office/src/app/dashboard/pages/resources/resources.component.html
  apps/back-office/src/app/dashboard/pages/resources/resources.component.ts
  libs/shared/src/lib/models/resource.model.ts
Labels: enhancement

#1875 Now the form builder empties all customFilters if any other filterBy …
  libs/shared/src/lib/survey/components/resource.ts
  libs/shared/src/lib/survey/components/resources.ts
Labels: bug

#1896 fix/add-empty-state-for-pulljobs-page
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.module.ts
Labels: bug, keep

#1902 feat/AB#75907_Signal-EURO-Unable-to-add-users
  libs/safe/src/lib/components/users/components/add-user/add-user.component.ts
Labels: bug, enhancement, refactor

#1903 fix/AB#75973-infinite-redirection-adding-context-dashboard
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
Labels: bug

#1901 feat/AB#75945_DB-Record-as-selected-is-not-displaying-on-Record-selection-page-of-text-widget
  apps/back-office/src/app/dashboard/pages/form-builder/form-builder.component.ts
  apps/web-widgets/src/app/styles/_ui.scss
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/components/geospatial-map/geospatial-fields/geospatial-fields.component.scss
  libs/shared/src/lib/components/list-filter/list-filter.component.html
  libs/shared/src/lib/components/query-builder/tab-style/query-style/query-style.component.scss
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/shared/src/lib/components/ui/core-grid/popup-editor/popup-editor.component.html
  libs/shared/src/lib/components/ui/core-grid/popup-editor/popup-editor.component.scss
  libs/styles/src/lib/tailwind/tailwind.scss
  libs/ui/src/style/styles.scss
Labels: bug

#1891 Feat/ab#75754 reduce white space backoffice when editing applications
  apps/back-office/src/app/app-preview/app-preview.component.html
  apps/back-office/src/app/application/application.component.html
  apps/back-office/src/app/application/application.module.ts
  apps/back-office/src/app/application/pages/settings/settings.component.html
  apps/back-office/src/app/application/pages/settings/settings.component.ts
  apps/back-office/src/app/application/pages/settings/settings.module.ts
  apps/back-office/src/app/components/application-header/application-header.component.html
  apps/back-office/src/app/components/application-header/application-header.component.scss
  apps/back-office/src/app/components/application-header/application-header.component.spec.ts
  apps/back-office/src/app/components/application-header/application-header.component.ts
  apps/back-office/src/app/components/application-header/application-header.module.ts
  libs/shared/src/index.ts
  libs/shared/src/lib/components/application-toolbar/application-toolbar.component.html
  libs/shared/src/lib/components/application-toolbar/application-toolbar.component.spec.ts
  libs/shared/src/lib/components/application-toolbar/public-api.ts
  libs/shared/src/lib/components/layout/layout.component.html
  libs/shared/src/lib/components/layout/layout.component.ts
  libs/shared/src/lib/components/navbar/navbar.component.scss
Labels: enhancement

#1876 fix/AB#75544_DB-duplicate-layers-are-displaying-on-map-widget
  libs/shared/src/lib/components/ui/map/map.component.ts
Labels: bug

#1905 feat/AB#76016_Change-Status-selector-in-application-settings-to-use-new-shared-component
  apps/back-office/src/app/application/pages/settings/settings.component.html
  apps/back-office/src/app/application/pages/settings/settings.component.ts
  apps/back-office/src/app/application/pages/settings/settings.module.ts
Labels: enhancement, refactor
