Repository ReliefApplications/ems-frontend, pull requests merged in 2023-04, with the labels that each got.

#1235 feat/AB#60921-custom-styling-active-between-pages
  apps/back-office/src/app/application/application-routing.module.ts
  apps/back-office/src/app/application/application.component.ts
  apps/back-office/src/app/application/pages/settings/settings.component.ts
  apps/back-office/src/app/components/custom-style/custom-style.component.ts
  libs/safe/src/lib/services/application/application.service.ts
  libs/safe/src/lib/services/layout/layout.service.ts
Labels: enhancement

#1239 feat/AB#60923-layers-fields
  libs/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  libs/safe/src/lib/components/gradient-picker/gradient-picker-popup/gradient-picker-popup.component.ts
  libs/safe/src/lib/components/gradient-picker/gradient-picker.component.ts
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/components/widgets/map-settings/graphql/queries.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-datasource/layer-datasource.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-datasource/layer-datasource.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-fields/layer-fields.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-fields/layer-fields.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/fields-element/fields-element.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/fields-element/fields-element.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/layer-popup.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/layer-popup.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/text-element/text-element.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/text-element/utils/keys.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.ts
  libs/safe/src/lib/services/map/map-layers.service.ts
Labels: enhancement

#1243 feat/AB#61054-consistent-styling-for-layer-tabs
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/map-layer.component.scss
  libs/safe/src/lib/components/widgets/map-settings/map-settings.component.scss
Labels: enhancement

#1246 refactor/AB#61059_add-editor-control-component
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/editor-control/editor-control.component.html
  libs/safe/src/lib/components/editor-control/editor-control.component.scss
  libs/safe/src/lib/components/editor-control/editor-control.component.spec.ts
  libs/safe/src/lib/components/editor-control/editor-control.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/fields-element/fields-element.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/fields-element/fields-element.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/layer-popup.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/layer-popup.component.ts
  libs/safe/src/lib/components/widgets/map-settings/map-layer/layer-popup/layer-popup.module.ts
  libs/safe/src/lib/const/tinymce.const.ts
  package-lock.json
Labels: enhancement

#1242 fix: inject btn in datepicker & edit safe-button
  libs/safe/src/lib/survey/widgets/text-widget.ts
Labels: fix

#1236 Fix/ab#60965 saved value not appearing geospatial question
  libs/safe/src/lib/components/geospatial-map/geospatial-map.component.html
  libs/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
  libs/safe/src/lib/components/ui/map/map.component.ts
  libs/safe/src/lib/services/map/map-layers.service.ts
Labels: fix

#1250 feat/AB#61106_hide_show_series_categories
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/form/form.component.ts
  libs/safe/src/lib/components/layout/layout.component.ts
  libs/safe/src/lib/components/ui/charts/bar-chart/bar-chart.component.ts
  libs/safe/src/lib/components/ui/charts/line-chart/line-chart.component.ts
  libs/safe/src/lib/components/ui/charts/pie-donut-chart/pie-donut-chart.component.ts
  libs/safe/src/lib/components/widget-grid/floating-options/menu/tile-data/tile-data.component.ts
  libs/safe/src/lib/components/widgets/chart-settings/chart-forms.ts
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/categories-settings/categories-settings.component.html
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/categories-settings/categories-settings.component.ts
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/categories-settings/categories-settings.module.ts
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/series-settings.component.html
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/series-settings.component.ts
  libs/safe/src/lib/components/widgets/chart-settings/series-settings/series-settings.module.ts
  libs/safe/src/lib/services/application/application.service.ts
Labels: enhancement

#1262 fix/AB#61701-edit-label-of-fields
  libs/safe/src/lib/components/query-builder/tab-fields/tab-fields.component.html
Labels: bug

#1276 feat/AB#61954-implement-toggle
  libs/ui/src/index.ts
  libs/ui/src/lib/icon/icon.component.html
  libs/ui/src/lib/icon/icon.component.scss
  libs/ui/src/lib/icon/icon.component.stories.ts
  libs/ui/src/lib/icon/icon.component.ts
  libs/ui/src/lib/shared/category.enum.ts
  libs/ui/src/lib/shared/size.enum.ts
  libs/ui/src/lib/shared/variant.enum.ts
  libs/ui/src/lib/toggle/enums/toggle-type.enum.ts
  libs/ui/src/lib/toggle/interfaces/toggle-icon.interface.ts
  libs/ui/src/lib/toggle/interfaces/toggle-label.interface.ts
  libs/ui/src/lib/toggle/toggle.component.html
  libs/ui/src/lib/toggle/toggle.component.scss
  libs/ui/src/lib/toggle/toggle.component.spec.ts
  libs/ui/src/lib/toggle/toggle.component.stories.ts
  libs/ui/src/lib/toggle/toggle.component.ts
  libs/ui/src/lib/toggle/toggle.module.ts
  libs/ui/src/lib/ui.module.ts
Labels: enhancement

#1274 feat/AB#61942_Implement_avatar_component
  libs/ui/src/index.ts
  libs/ui/src/lib/avatar-group/avatar-group.component.html
  libs/ui/src/lib/avatar-group/avatar-group.component.scss
  libs/ui/src/lib/avatar-group/avatar-group.component.spec.ts
  libs/ui/src/lib/avatar-group/avatar-group.component.stories.ts
  libs/ui/src/lib/avatar-group/avatar-group.component.ts
  libs/ui/src/lib/avatar-group/avatar-group.module.ts
  libs/ui/src/lib/avatar-group/enums/avatar-group-stack.enum.ts
  libs/ui/src/lib/avatar/avatar.component.html
  libs/ui/src/lib/avatar/avatar.component.scss
  libs/ui/src/lib/avatar/avatar.component.stories.ts
  libs/ui/src/lib/avatar/avatar.component.ts
  libs/ui/src/lib/avatar/enums/avatar-shape.enum.ts
  libs/ui/src/lib/avatar/enums/avatar-variant.enum.ts
  libs/ui/src/lib/checkbox/checkbox.component.html
  libs/ui/src/lib/flyout-menu/flyout-menu.component.html
  libs/ui/src/lib/select/select.component.html
  libs/ui/src/lib/ui.module.ts
Labels: enhancement

#1287 Fix/ab#61981 child modal displaying behind parent modal
  apps/back-office/src/app/app.module.ts
  apps/front-office/src/app/app.module.ts
  libs/safe/src/lib/directives/fullscreen/fullscreen.module.ts
Labels: fix

#1245 AB#61071 Contextual Filter
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/dashboard-filter/dashboard-filter.component.html
  libs/safe/src/lib/components/dashboard-filter/dashboard-filter.component.scss
  libs/safe/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/safe/src/lib/components/dashboard-filter/dashboard-filter.module.ts
  libs/safe/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder.component.html
  libs/safe/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder.component.scss
  libs/safe/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder.component.spec.ts
  libs/safe/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder.component.ts
  libs/safe/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder.module.ts
  libs/safe/src/lib/components/dashboard-filter/graphql/mutations.ts
  libs/safe/src/lib/components/form-modal/form-modal.component.ts
  libs/safe/src/lib/components/form/form.component.ts
  libs/safe/src/lib/components/record-modal/record-modal.component.ts
  libs/safe/src/lib/models/application.model.ts
  libs/safe/src/lib/services/application/graphql/queries.ts
  libs/safe/src/lib/services/form-helper/form-helper.service.ts
  libs/safe/src/lib/services/form/form.service.ts
  libs/safe/src/lib/survey/init.ts
Labels: enhancement

#1290 fix/AB#62403_sub-to-geospatial-form
  libs/safe/src/lib/components/geospatial-map/geospatial-map.component.html
  libs/safe/src/lib/components/geospatial-map/geospatial-map.component.ts
Labels: bug
