Repository ReliefApplications/ems-frontend, pull requests merged in 2023-08, with the labels that each got.

#1638 feat/map-modal-title
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/ui/core-grid/map-modal/map-modal.component.html
  libs/safe/src/lib/components/ui/core-grid/map-modal/map-modal.component.ts
Labels: enhancement

#1650 #69895 map search control hidden by fullscreen control
  libs/safe/src/lib/components/ui/map/map.component.scss
  libs/safe/src/lib/components/ui/map/map.component.ts
Labels: fix

#1666 Fix/ab#70863 abc breadcrumb going outside of bounds
  libs/ui/src/lib/breadcrumbs/breadcrumbs.component.html
  libs/ui/src/lib/breadcrumbs/breadcrumbs.component.scss
  libs/ui/src/lib/breadcrumbs/breadcrumbs.component.ts
  libs/ui/src/lib/breadcrumbs/interfaces/breadcrumb.interface.ts
Labels: bug

#1680 fix/AB#71072_clean_up_filter_logic
  libs/safe/src/lib/survey/widgets/dropdown-widget.ts
  libs/safe/src/lib/survey/widgets/tagbox-widget.ts
  libs/safe/src/lib/survey/widgets/utils/common-list-filters.ts
Labels: refactor

#1683 Bug/ab#67008 force scroll to top in dashboard
  libs/ui/src/lib/sidenav/sidenav-container.component.html
  libs/ui/src/lib/sidenav/sidenav-container.component.ts
Labels: fix

#1693 fix/AB#71542-incorrect-save-option-text-field-grid
  libs/safe/src/lib/components/ui/core-grid/expanded-comment/expanded-comment.component.html
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
Labels: bug

#1642 Ab#69366 long texts in selects truncation does not work well
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  libs/ui/src/lib/select-menu/select-menu.component.scss
Labels: bug

#1663 Fix 2.0.x/ab#59984 buggy validation icons inline edition
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/safe/src/lib/components/ui/core-grid/errors-modal/errors-modal.component.html
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/safe/src/lib/components/widgets/grid/grid.component.ts
Labels: bug

#1640 Fix: Pagination on choose record modal for attach to record button
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/choose-record-modal/choose-record-modal.component.html
  libs/safe/src/lib/components/choose-record-modal/choose-record-modal.component.ts
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/safe/src/lib/services/query-builder/query-builder.service.ts
  libs/ui/src/lib/graphql-select/graphql-select.component.html
  libs/ui/src/lib/graphql-select/graphql-select.component.ts
Labels: enhancement

#1687 Fix 2.1.x/db#67743 zoom and pan settings not applied in arc gis
  libs/safe/src/lib/services/map/arcgis.service.ts
Labels: fix

#1692 Fix 2.1.x/db#70931 style getting passed in link url
  libs/safe/src/lib/utils/parser/utils.ts
Labels: fix

#1647 fix/resources-field-permission-roles-page
  libs/safe/src/lib/components/role-summary/role-resources/resource-fields/resource-fields.component.html
  libs/safe/src/lib/components/role-summary/role-resources/resource-fields/resource-fields.component.ts
  libs/safe/src/lib/components/role-summary/role-resources/role-resources.component.html
  libs/safe/src/lib/components/role-summary/role-resources/role-resources.component.ts
Labels: bug

#1630 fix/AB#69266_drag_drop_styling_missing
  libs/safe/src/lib/components/navbar/navbar.component.html
  libs/safe/src/lib/style/styles.scss
Labels: bug

#1701 fix/AB#71766-history-overflow-hidden
  libs/ui/src/lib/sidenav/sidenav-container.component.html
  libs/ui/src/lib/sidenav/sidenav-container.component.ts
Labels: bug

#1700 Feat 2.0.x/abc#71765 select no available choices option
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/ui/src/lib/select-menu/select-menu.component.html
  libs/ui/src/lib/select-menu/select-menu.module.ts
Labels: enhancement

#1581 Feat/ab#28941 allow to have page with single widget
  apps/back-office/src/app/application/pages/add-page/add-page.component.html
  apps/back-office/src/app/application/pages/add-page/add-page.component.ts
  apps/back-office/src/app/application/pages/add-page/add-page.module.ts
  apps/back-office/src/environments/environment.ts
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/index.ts
  libs/safe/src/lib/safe.module.ts
  libs/safe/src/lib/services/application/application.service.ts
  libs/safe/src/lib/services/application/graphql/mutations.ts
Labels: enhancement

#1709 fix/AB#71542_field-value-null-when-closing-expand-modal
  libs/safe/src/lib/components/ui/core-grid/expanded-comment/expanded-comment.component.html
  libs/ui/src/lib/tooltip/tooltip.directive.ts
Labels: bug

#1711 fix/AB#71898-issues-detected-by-sentry
  apps/back-office/src/app/application/pages/add-page/add-page.component.ts
  apps/back-office/src/app/application/pages/workflow/components/add-step/add-step.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/form-builder/form-builder.component.ts
  apps/back-office/src/app/dashboard/pages/forms/forms.component.ts
  apps/back-office/src/app/dashboard/pages/resources/resources.component.ts
  apps/front-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  libs/safe/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.ts
  libs/safe/src/lib/components/application-dropdown/application-dropdown.component.ts
  libs/safe/src/lib/components/form-modal/form-modal.component.ts
  libs/safe/src/lib/components/record-dropdown/record-dropdown.component.ts
  libs/safe/src/lib/components/record-history/record-history.component.ts
  libs/safe/src/lib/components/reference-data-dropdown/reference-data-dropdown.component.ts
  libs/safe/src/lib/components/role-summary/role-resources/role-resources.component.ts
  libs/safe/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  libs/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/safe/src/lib/components/widgets/editor/editor.component.ts
  libs/safe/src/lib/services/application/application.service.ts
  libs/safe/src/lib/services/breadcrumb/breadcrumb.service.ts
  libs/safe/src/lib/survey/components/resources.ts
  libs/ui/src/lib/graphql-select/graphql-select.component.ts
  package-lock.json
  package.json
Labels: bug

#1716 Ab#71757 fix service tests
  apps/back-office/src/app/services/preview.service.spec.ts
  libs/safe/src/lib/services/aggregation-builder/aggregation-builder.service.spec.ts
  libs/safe/src/lib/services/aggregation/aggregation.service.spec.ts
  libs/safe/src/lib/services/api-proxy/api-proxy.service.spec.ts
  libs/safe/src/lib/services/application-notifications/application-notifications.service.spec.ts
  libs/safe/src/lib/services/application/application.service.spec.ts
  libs/safe/src/lib/services/arc-gis.service.spec.ts
  libs/safe/src/lib/services/auth-interceptor/auth-interceptor.service.spec.ts
  libs/safe/src/lib/services/auth/auth.service.spec.ts
  libs/safe/src/lib/services/breadcrumb/breadcrumb.service.spec.ts
  libs/safe/src/lib/services/confirm/confirm.service.spec.ts
  libs/safe/src/lib/services/context/context.service.spec.ts
  libs/safe/src/lib/services/dashboard/dashboard.service.spec.ts
  libs/safe/src/lib/services/data-template/data-template.service.spec.ts
  libs/safe/src/lib/services/date-translate/date-translate.service.spec.ts
  libs/safe/src/lib/services/dom/dom.service.spec.ts
  libs/safe/src/lib/services/download/download.service.spec.ts
  libs/safe/src/lib/services/editor/editor.service.spec.ts
  libs/safe/src/lib/services/email/email.service.spec.ts
  libs/safe/src/lib/services/form-builder/form-builder.service.spec.ts
  libs/safe/src/lib/services/form/form.service.spec.ts
  libs/safe/src/lib/services/grid-layout/grid-layout.service.spec.ts
  libs/safe/src/lib/services/grid/grid.service.spec.ts
  libs/safe/src/lib/services/layout/layout.service.spec.ts
  libs/safe/src/lib/services/notification/notification.service.spec.ts
  libs/safe/src/lib/services/query-builder/query-builder.service.spec.ts
  libs/safe/src/lib/services/reference-data/reference-data.service.spec.ts
  libs/safe/src/lib/services/rest/rest.service.spec.ts
  libs/safe/src/lib/services/workflow/workflow.service.spec.ts
  libs/safe/tsconfig.spec.json
Labels: bug

#1719 bugfix/AB#72067_ABC-cannot-expand-accordion
  libs/ui/src/lib/expansion-panel/expansion-panel.component.scss
Labels: bug

#1720 Bugfix/ab#71758 back office fix guards tests
  apps/back-office/.eslintrc.json
  apps/back-office/src/app/guards/access.guard.spec.ts
  apps/back-office/src/app/guards/auth.guard.spec.ts
  apps/back-office/src/app/guards/can-deactivate.guard.spec.ts
  apps/back-office/src/app/guards/mock-class.test.ts
  libs/ui/src/index.ts
Labels: enhancement

#1725 Ab#71751 front office fixcomponentstests
  apps/front-office/src/app/app.component.spec.ts
  apps/front-office/src/app/dashboard/pages/roles/roles.component.spec.ts
  apps/front-office/src/app/dashboard/pages/share/share.component.spec.ts
  apps/front-office/src/app/dashboard/pages/workflow/workflow.component.spec.ts
  apps/front-office/src/app/guards/access.guard.spec.ts
Labels: enhancement

#1726 Ab#71745 UI lib fix other tests
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.spec.ts
Labels: enhancement

#1644 fix/app-preview
  apps/back-office/src/app/app-preview/app-preview.component.ts
  apps/back-office/src/app/application/application.component.ts
  libs/safe/src/lib/components/navbar/navbar.component.scss
Labels: bug

#1727 Fix 2.0.x/abc#72416 no available choices alert erases whole select popup content
  apps/back-office/src/app/components/custom-style/custom-style.component.scss
  libs/safe/src/lib/components/ui/aggregation-builder/forms-dropdown/forms-dropdown.component.html
  libs/safe/src/lib/style/styles.scss
  libs/safe/src/lib/style/survey.scss
  libs/ui/src/lib/select-menu/select-menu.component.html
  libs/ui/src/style/styles.scss
  libs/ui/src/style/survey.scss
Labels: bug

#1724 Fix/ab#72105 incorrect pagination on resources
  apps/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.ts
  apps/back-office/src/app/dashboard/pages/api-configurations/graphql/mutations.ts
  apps/back-office/src/app/dashboard/pages/applications/applications.component.ts
  apps/back-office/src/app/dashboard/pages/forms/forms.component.ts
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.ts
  apps/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.ts
  apps/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.ts
  apps/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.ts
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.ts
  apps/back-office/src/app/dashboard/pages/resources/resources.component.ts
  libs/safe/src/lib/components/role-summary/role-resources/role-resources.component.ts
  libs/safe/src/lib/components/role-summary/role-users/role-users.component.ts
  libs/safe/src/lib/components/widgets/summary-card/summary-card.component.html
  libs/safe/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/safe/src/lib/views/application-users/components/user-list/user-list.component.ts
  libs/ui/src/lib/paginator/paginator.component.html
  libs/ui/src/lib/paginator/paginator.component.ts
Labels: bug

#1733 refactor: improves graphql filtering by handing change detection to s…
  libs/safe/src/lib/survey/global-properties/choicesByUrl.ts
  libs/safe/src/lib/survey/global-properties/others.ts
Labels: enhancement

#1739 fix/AB#72835-search-doesn’t-update-new-page-form
  apps/back-office/src/app/application/pages/add-page/graphql/queries.ts
  apps/back-office/src/app/application/pages/workflow/graphql/queries.ts
Labels: bug

#1550 AB#65023 - Add draft option to editRecord mutation
  libs/safe/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/safe/src/lib/components/ui/core-grid/graphql/mutations.ts
Labels: enhancement

#1732 fix/AB#72696_redirect_not_working_opening_dashboard_context
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
Labels: bug

#1704 Ability to filter users question by role
  libs/safe/src/lib/survey/components/users.ts
  libs/safe/src/lib/survey/graphql/queries.ts
Labels: enhancement

#1712 feat/OORT-657_workflow-context
  libs/safe/src/lib/components/widgets/grid/grid.component.ts
  libs/safe/src/lib/services/form-builder/form-builder.service.ts
  libs/safe/src/lib/services/form-helper/form-helper.service.ts
  libs/safe/src/lib/services/workflow/workflow.service.ts
  libs/safe/src/lib/utils/custom-functions.ts
Labels: enhancement

#1722 fix/OORT-662-grid-search-resource-questions
  libs/safe/src/lib/services/grid/grid.service.ts
Labels: bug

#1740 feat/OORT-665_validate-questions-in-real-time
  libs/safe/src/lib/services/form-builder/form-builder.service.ts
  libs/safe/src/lib/survey/global-properties/others.ts
Labels: enhancement

#1748 id as survey variable
  libs/safe/src/lib/services/form-builder/form-builder.service.ts
  libs/safe/src/lib/services/form-helper/form-helper.service.ts
  libs/safe/src/lib/survey/components/utils.ts
Labels: enhancement

#1746 feat/OORT-667_next-on-form-submit
  apps/back-office/src/app/application/pages/form/form.component.ts
  apps/back-office/src/app/application/pages/workflow/components/add-step/add-step.component.html
  apps/back-office/src/app/application/pages/workflow/workflow.component.ts
  libs/safe/src/lib/models/workflow.model.ts
  libs/safe/src/lib/services/workflow/graphql/queries.ts
  libs/safe/src/lib/services/workflow/workflow.service.ts
Labels: enhancement

#1747 refactor: another approach for organizing the custom functions
  libs/safe/src/lib/components/form-modal/form-modal.component.ts
  libs/safe/src/lib/components/form/form.component.ts
  libs/safe/src/lib/components/record-modal/record-modal.component.ts
  libs/safe/src/lib/survey/custom-functions.ts
  libs/safe/src/lib/survey/functions/addDays.ts
  libs/safe/src/lib/survey/functions/elementAt.ts
  libs/safe/src/lib/survey/functions/getAidsGiven.ts
  libs/safe/src/lib/survey/functions/getField.ts
  libs/safe/src/lib/survey/functions/getMatrixTitles.ts
  libs/safe/src/lib/survey/functions/getTotalAids.ts
  libs/safe/src/lib/survey/functions/getWorkflowContext.ts
  libs/safe/src/lib/survey/functions/index.ts
  libs/safe/src/lib/survey/functions/intersect.ts
  libs/safe/src/lib/survey/functions/length.ts
  libs/safe/src/lib/survey/functions/listColsForRows.ts
  libs/safe/src/lib/survey/functions/listRowsWithColValue.ts
  libs/safe/src/lib/survey/functions/nextYear.ts
  libs/safe/src/lib/survey/functions/nl2br.ts
  libs/safe/src/lib/survey/functions/weekday.ts
  libs/safe/src/lib/survey/init.ts
  libs/safe/src/lib/utils/custom-functions.ts
Labels: enhancement

#1755 bug/AB#67742_DB---Applied-Basemap-occasionally-won't-appear-on-search
  libs/safe/src/lib/components/ui/map/layer.ts
  libs/safe/src/lib/components/widgets/map-settings/map-properties/webmap-select/webmap-select.component.html
  libs/safe/src/lib/components/widgets/map-settings/map-properties/webmap-select/webmap-select.component.ts
  libs/safe/src/lib/services/map/arcgis.service.ts
  libs/ui/src/lib/select-menu/select-menu.component.ts
Labels: bug

#1665 Fix/ab#69615 last modified displaying wrong data
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.module.ts
  libs/safe/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.component.html
  libs/safe/src/lib/components/widgets/grid/grid.component.ts
Labels: bug, keep

#1760 Feat 2.0.x/ab#73217 UI table elements max width
  apps/back-office/src/app/application/pages/channels/channels.component.html
  apps/back-office/src/app/application/pages/subscriptions/subscriptions.component.html
  apps/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.html
  apps/back-office/src/app/dashboard/pages/applications/applications.component.html
  apps/back-office/src/app/dashboard/pages/forms/forms.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.html
  apps/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.html
  apps/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/forms-tab/forms-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.html
  apps/back-office/src/app/dashboard/pages/resources/resources.component.html
  libs/safe/src/lib/components/aggregation/aggregation-table/aggregation-table.component.html
  libs/safe/src/lib/components/grid-layout/layout-table/layout-table.component.html
  libs/safe/src/lib/components/mapping/mapping.component.html
  libs/safe/src/lib/components/notifications/notifications.component.html
  libs/safe/src/lib/components/query-builder/tab-style/query-style-list/query-style-list.component.html
  libs/safe/src/lib/components/roles/components/group-list/group-list.component.html
  libs/safe/src/lib/components/roles/components/role-list/role-list.component.html
  libs/safe/src/lib/components/templates/templates.component.html
  libs/safe/src/lib/components/users/users.component.html
  libs/safe/src/lib/style/styles.scss
  libs/safe/src/lib/views/application-users/components/user-list/user-list.component.html
  libs/safe/src/lib/views/profile/profile.component.html
  libs/ui/src/lib/table/cell.directive.ts
  tailwind.config.js
Labels: enhancement

#1757 feat/AB#73268_few_ui_changes
  apps/back-office/src/app/application/pages/settings/settings.component.html
  apps/back-office/src/app/application/pages/subscriptions/components/subscription-modal/subscription-modal.component.html
  apps/back-office/src/app/components/add-form-modal/add-form-modal.component.html
  apps/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.html
  apps/back-office/src/app/dashboard/pages/api-configurations/api-configurations.component.html
  apps/back-office/src/app/dashboard/pages/applications/components/filter/filter.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-datasource/context-datasource.component.html
  apps/back-office/src/app/dashboard/pages/forms/components/filter/filter.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  apps/back-office/src/app/dashboard/pages/resources/filter/filter.component.html
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/lib/components/filter/filter-group/filter-group.component.html
  libs/safe/src/lib/components/filter/filter-group/filter-group.component.scss
  libs/safe/src/lib/components/filter/filter-row/filter-row.component.html
  libs/safe/src/lib/components/filter/filter-row/filter-row.component.scss
  libs/safe/src/lib/components/query-builder/query-builder.component.html
  libs/safe/src/lib/components/query-builder/tab-style/query-style/query-style.component.html
  libs/safe/src/lib/components/role-summary/role-resources-filter/role-resources-filter.component.html
  libs/safe/src/lib/components/ui/aggregation-builder/aggregation-builder.component.html
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/add-field-stage/add-field-stage.component.html
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/expressions/expressions.component.html
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/field-dropdown/field-dropdown.component.html
  libs/safe/src/lib/components/ui/aggregation-builder/pipeline/group-stage/group-stage.component.html
  libs/safe/src/lib/components/users/users.component.html
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/safe/src/lib/components/widgets/grid-settings/button-config/button-config.component.scss
  libs/safe/src/lib/components/widgets/summary-card-settings/display-tab/display-tab.component.scss
  libs/ui/src/lib/date/date-picker.directive.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/lib/graphql-select/graphql-select.component.html
  libs/ui/src/lib/graphql-select/graphql-select.component.ts
  libs/ui/src/lib/select-menu/components/select-option.component.html
  libs/ui/src/lib/select-menu/select-menu.component.html
  libs/ui/src/lib/select-menu/select-menu.component.ts
Labels: enhancement

#1765 fix/AB#73582_tagbox_filters_grid_return_empty_result
  libs/safe/src/lib/components/ui/core-grid/array-filter/array-filter.component.ts
Labels: bug

#1741 REBASE - Fix 2.0.x/ab#69129 filters not working
  libs/safe/src/lib/components/ui/core-grid/grid/grid.component.ts
Labels: bug

#1758 Fix/update query values missing if next value is empty array
  apps/back-office/src/app/utils/update-queries.ts
  libs/safe/src/lib/utils/update-queries.ts
  libs/ui/src/lib/graphql-select/utils/update-queries.ts
Labels: bug, keep

#1656 Feat 2.0.x/ab#69370 improve loading data of resource questions
  libs/safe/src/lib/components/test-service-dropdown/graphql/queries.ts
  libs/safe/src/lib/components/test-service-dropdown/test-service-dropdown.component.html
  libs/safe/src/lib/components/test-service-dropdown/test-service-dropdown.component.scss
  libs/safe/src/lib/components/test-service-dropdown/test-service-dropdown.component.spec.ts
  libs/safe/src/lib/components/test-service-dropdown/test-service-dropdown.component.ts
  libs/safe/src/lib/survey/components/resource.ts
  libs/safe/src/lib/survey/components/resources.ts
Labels: enhancement

#1770 Feat 2.0.x/ab#73566 abc update storybook + improvements
  libs/ui/project.json
  libs/ui/src/lib/button/button.component.stories.ts
  libs/ui/src/lib/icon/icon.component.stories.ts
  libs/ui/src/lib/icon/icon.list.ts
  libs/ui/src/style/storybook.scss
  package-lock.json
  package.json
Labels: enhancement

#1773 Feat 2.0.x/ab#73995 improve display of menus
  apps/back-office/src/app/application/pages/position/position.component.html
  apps/back-office/src/app/application/pages/position/position.module.ts
  apps/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.module.ts
  apps/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.module.ts
  apps/back-office/src/app/dashboard/pages/resource/forms-tab/forms-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/forms-tab/forms-tab.module.ts
  apps/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.module.ts
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/records-tab/records-tab.module.ts
  libs/safe/src/lib/components/aggregation/aggregation-table/aggregation-table.component.html
  libs/safe/src/lib/components/aggregation/aggregation-table/aggregation-table.module.ts
  libs/safe/src/lib/components/grid-layout/layout-table/layout-table.component.html
  libs/safe/src/lib/components/grid-layout/layout-table/layout-table.module.ts
  libs/safe/src/lib/components/mapping/mapping.component.html
  libs/safe/src/lib/components/mapping/mapping.module.ts
  libs/safe/src/lib/components/query-builder/query-builder.module.ts
  libs/safe/src/lib/components/query-builder/tab-style/query-style-list/query-style-list.component.html
Labels: enhancement

#1772 refactor: use jsonpath for querying choices path
  libs/safe/src/lib/survey/global-properties/choicesByUrl.ts
Labels: enhancement

#1777 Fix/ab#73582 tagbox filters not working
  libs/safe/src/lib/components/ui/core-grid/array-filter/array-filter.component.ts
Labels: bug
