Repository ReliefApplications/ems-frontend, pull requests merged in 2023-11, with the labels that each got.

#2031 fix/HIT-138-corrupted-file-grid-details
  libs/shared/src/lib/components/record-modal/record-modal.component.ts
  libs/shared/src/lib/services/form-builder/form-builder.service.ts
Labels: bug

#1992 Feat/hit 117 create custom function to format date
  libs/shared/src/lib/survey/functions/formatDate.ts
  libs/shared/src/lib/survey/functions/index.ts
Labels: enhancement

#2011 feat/AB#77501_An-empty-success-message-displayed-for-couple-of-seconds-on-saving-the-survey-on-SIT-&-UAT-environments
  apps/back-office/src/app/dashboard/pages/form-builder/form-builder.component.ts
  libs/safe/src/i18n/en.json
  libs/safe/src/i18n/fr.json
  libs/safe/src/i18n/test.json
  libs/safe/src/index.ts
  libs/safe/src/lib/components/status-modal/public-api.ts
  libs/safe/src/lib/components/status-modal/status-modal.component.html
  libs/safe/src/lib/components/status-modal/status-modal.component.scss
  libs/safe/src/lib/components/status-modal/status-modal.component.spec.ts
  libs/safe/src/lib/components/status-modal/status-modal.component.ts
  libs/safe/src/lib/services/download/download.service.ts
  libs/ui/src/index.ts
  libs/ui/src/lib/snackbar/snackbar.component.ts
  libs/ui/src/lib/snackbar/snackbar.service.ts
  libs/ui/tsconfig.lib.json
Labels: bug, enhancement

#2036 feat/AB#78337_Regression-Added-field-is-not-getting-removed-on-click-of-remove-icon(X)-on-history-section-of-record
  libs/safe/src/lib/components/record-history/record-history.component.html
  libs/safe/src/lib/components/record-history/record-history.module.ts
Labels: bug

#2038 feat/AB#78445_Regression-date-values-are-able-to-remove-on-view-details-page-of-record-on-grid
  libs/safe/src/lib/survey/widgets/text-widget.ts
Labels: bug

#2039 added placeholder and cross icon
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.component.html
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.component.ts
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.module.ts
Labels: enhancement

#2010 feat/HIT-134_Change-NextStepOnSave-Logic
  apps/back-office/src/app/app-preview/pages/form/form.component.ts
  apps/back-office/src/app/app-preview/pages/form/graphql/queries.ts
  apps/back-office/src/app/app-preview/pages/workflow/workflow.component.ts
  apps/back-office/src/app/application/pages/form/form.component.ts
  apps/back-office/src/app/application/pages/form/graphql/queries.ts
  apps/back-office/src/app/application/pages/workflow/workflow.component.ts
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.html
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
  apps/front-office/src/app/application/pages/form/form.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/models/step.model.ts
  libs/shared/src/lib/models/workflow.model.ts
  libs/shared/src/lib/services/workflow/graphql/mutations.ts
  libs/shared/src/lib/services/workflow/graphql/queries.ts
  libs/shared/src/lib/services/workflow/workflow.service.ts
Labels: enhancement

#2042 fix/HIT-116-be-able-to-change-default-language-of-form
  libs/shared/src/lib/components/form-actions/form-actions.component.ts
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/services/form-builder/form-builder.service.ts
  libs/shared/src/lib/survey/global-properties/others.ts
Labels: bug

#1999 AB#74821 authorization code possibility for api config
  apps/back-office/src/app/dashboard/pages/reference-data/graphql/queries.ts
  apps/back-office/src/environments/environment.azure.dev.ts
  apps/back-office/src/environments/environment.azure.prod.ts
  apps/back-office/src/environments/environment.azure.sit.ts
  apps/back-office/src/environments/environment.azure.uat.ts
  apps/front-office/src/environments/environment.azure.dev.ts
  apps/front-office/src/environments/environment.azure.prod.ts
  apps/front-office/src/environments/environment.azure.sit.ts
  apps/front-office/src/environments/environment.azure.uat.ts
  libs/shared/src/lib/models/api-configuration.model.ts
  libs/shared/src/lib/services/api-proxy/api-proxy.service.ts
  libs/shared/src/lib/services/auth-interceptor/auth-interceptor.service.ts
  libs/shared/src/lib/services/auth/auth.service.ts
  libs/shared/src/lib/services/reference-data/graphql/queries.ts
  libs/shared/src/lib/services/reference-data/reference-data.service.ts
Labels: enhancement

#2054 Ab#78899 fix resources readonly
  libs/shared/src/lib/survey/components/resources.ts
Labels: bug

#2057 fix/AB#78828_auto-size-of-grid-columns
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/utils/rxjs/resize-observable.util.ts
Labels: bug, enhancement

#2030 AB#74319 : Save records as draft
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/draft-record-list-modal/draft-record-list-modal.component.html
  libs/shared/src/lib/components/draft-record-list-modal/draft-record-list-modal.component.scss
  libs/shared/src/lib/components/draft-record-list-modal/draft-record-list-modal.component.spec.ts
  libs/shared/src/lib/components/draft-record-list-modal/draft-record-list-modal.component.ts
  libs/shared/src/lib/components/draft-record-list-modal/graphql/queries.ts
  libs/shared/src/lib/components/draft-record-modal/draft-record-modal.component.html
  libs/shared/src/lib/components/draft-record-modal/draft-record-modal.component.scss
  libs/shared/src/lib/components/draft-record-modal/draft-record-modal.component.spec.ts
  libs/shared/src/lib/components/draft-record-modal/draft-record-modal.component.ts
  libs/shared/src/lib/components/draft-record/draft-record.component.html
  libs/shared/src/lib/components/draft-record/draft-record.component.scss
  libs/shared/src/lib/components/draft-record/draft-record.component.spec.ts
  libs/shared/src/lib/components/draft-record/draft-record.component.ts
  libs/shared/src/lib/components/form-modal/form-modal.component.html
  libs/shared/src/lib/components/form-modal/form-modal.component.ts
  libs/shared/src/lib/components/form/form.component.html
  libs/shared/src/lib/components/form/form.component.ts
  libs/shared/src/lib/components/form/form.module.ts
  libs/shared/src/lib/components/form/graphql/mutations.ts
  libs/shared/src/lib/components/record-summary/record-summary.component.ts
  libs/shared/src/lib/components/resource-modal/resource-modal.component.ts
  libs/shared/src/lib/models/draft-record.model.ts
  libs/shared/src/lib/models/record.model.ts
  libs/shared/src/lib/services/form-helper/form-helper.service.ts
  libs/shared/src/lib/services/form-helper/graphql/mutations.ts
  libs/shared/src/lib/survey/components/utils.ts
  libs/shared/src/lib/survey/types.ts
Labels: enhancement

#2029 Fix/ab#78168 allow other fields be passed as query parameter
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/components/widgets/common/tab-actions/graphql/queries.ts
  libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.html
  libs/shared/src/lib/components/widgets/common/tab-actions/tab-actions.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.html
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: bug

#2060 feat/AB#78914_predefined-filters-on-charts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
  libs/shared/src/lib/components/widgets/chart-settings/chart-forms.ts
  libs/shared/src/lib/components/widgets/chart-settings/chart-settings.component.html
  libs/shared/src/lib/components/widgets/chart-settings/chart-settings.component.ts
  libs/shared/src/lib/components/widgets/chart-settings/chart-settings.module.ts
  libs/shared/src/lib/components/widgets/chart-settings/graphql/queries.ts
  libs/shared/src/lib/components/widgets/chart-settings/tab-filters/tab-filters.component.html
  libs/shared/src/lib/components/widgets/chart-settings/tab-filters/tab-filters.component.scss
  libs/shared/src/lib/components/widgets/chart-settings/tab-filters/tab-filters.component.spec.ts
  libs/shared/src/lib/components/widgets/chart-settings/tab-filters/tab-filters.component.ts
  libs/shared/src/lib/components/widgets/chart/chart.component.html
  libs/shared/src/lib/components/widgets/chart/chart.component.ts
  libs/shared/src/lib/components/widgets/chart/chart.module.ts
Labels: enhancement

#2058 AB#78912 - ID appearing instead of the name
  libs/shared/src/lib/components/aggregation/edit-aggregation-modal/edit-aggregation-modal.component.html
  libs/shared/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.html
  libs/shared/src/lib/components/widgets/editor-settings/record-selection-tab/record-selection-tab.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
Labels: bug

#2051 feat/HIT-161_Option-to-omit-question-from-fields
  libs/shared/src/lib/survey/global-properties/others.ts
Labels: enhancement

#2069 Ab#78991 wrong size in details and actions grid columns
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.scss
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
Labels: bug

#2079 feat/AB#79261_always_show_boolean_to_hide_show_menu_in_applications
  apps/back-office/src/app/application/pages/settings/settings.component.html
  apps/back-office/src/app/application/pages/settings/settings.component.ts
Labels: enhancement

#2075 feat/AB#75971_Select-the-region-and-country-automatically-based-on-user's-org-path
  apps/back-office/src/environments/environment.azure.dev.ts
  apps/back-office/src/environments/environment.azure.prod.ts
  apps/back-office/src/environments/environment.azure.sit.ts
  apps/back-office/src/environments/environment.azure.uat.ts
  apps/back-office/src/environments/environment.type.ts
  apps/front-office/src/environments/environment.azure.dev.ts
  apps/front-office/src/environments/environment.azure.prod.ts
  apps/front-office/src/environments/environment.azure.sit.ts
  apps/front-office/src/environments/environment.azure.uat.ts
  apps/front-office/src/environments/environment.type.ts
  libs/safe/src/lib/models/user.model.ts
  libs/safe/src/lib/services/auth/graphql/queries.ts
  libs/safe/src/lib/services/form-helper/form-helper.service.ts
Labels: enhancement

#2077 fix/AB#79225_filter_builder_not_working_correctly_in_aggregation
  libs/shared/src/lib/components/aggregation/aggregation-grid/aggregation-grid.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.html
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.ts
  libs/shared/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.ts
Labels: bug

#2076 Ab#79165 abc new json tab survey builder
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder-modal.component.ts
  libs/shared/src/lib/components/form-builder/custom-json-editor/custom-json-editor.component.html
  libs/shared/src/lib/components/form-builder/custom-json-editor/custom-json-editor.component.scss
  libs/shared/src/lib/components/form-builder/custom-json-editor/custom-json-editor.component.ts
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/components/form-builder/form-builder.module.ts
Labels: bug

#2082 refactor/AB#79452_rename-card-display-tab-to-card-display
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/lib/components/widgets/summary-card-settings/display-tab/display-tab.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.html
Labels: refactor

#2080 AB#79065
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widget/widget.component.html
  libs/shared/src/lib/components/widget/widget.component.ts
  libs/shared/src/lib/components/widget/widget.module.ts
  libs/shared/src/lib/components/widgets/common/display-settings/display-settings.component.html
  libs/shared/src/lib/components/widgets/common/display-settings/display-settings.component.ts
  libs/shared/src/lib/components/widgets/common/display-settings/extendWidgetForm.ts
Labels: enhancement

#2055 feat/#AB#78673_Add-more-options-to-dashboard
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.html
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/graphql/queries.ts
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.html
  apps/front-office/src/app/application/pages/dashboard/graphql/queries.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
  libs/shared/src/lib/components/widget/widget.component.ts
  libs/shared/src/lib/models/dashboard.model.ts
  libs/shared/src/lib/services/dashboard/dashboard.service.ts
  libs/shared/src/lib/services/dashboard/graphql/mutations.ts
Labels: enhancement

#2086 fix/AB#79453_widgets-wrong-scroll
  libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
Labels: bug

#2084 AB#79579 ABC Remove auth settings on authcode api conf
  apps/back-office/src/app/dashboard/pages/api-configuration/api-configuration.component.html
Labels: bug

#2087 Fix/ab#79454 wrong calculation grid columns
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
Labels: bug

#2091 AB#79743: Improve UI of display settings in chart widgets
  libs/shared/src/lib/components/widgets/chart-settings/series-settings/series-settings.component.html
Labels: enhancement

#2097 AB#79775: reordering tabs in tabWidget
  libs/shared/src/lib/components/widgets/tabs-settings/tab-main/tab-main.component.ts
  libs/ui/src/lib/tabs/tabs.component.ts
Labels: bug

#633 OORT-145 - scheduler
  package-lock.json
  projects/safe/src/lib/components/widgets/scheduler/scheduler.component.html
  projects/safe/src/lib/components/widgets/scheduler/scheduler.component.scss
  projects/safe/src/lib/components/widgets/scheduler/scheduler.component.ts
Labels: keep

#2078 AB#79260 Dashboard filter options
  apps/back-office/src/app/app-preview/pages/dashboard/graphql/queries.ts
  apps/back-office/src/app/components/dashboard-filter-settings/dashboard-filter-settings.component.html
  apps/back-office/src/app/components/dashboard-filter-settings/dashboard-filter-settings.component.scss
  apps/back-office/src/app/components/dashboard-filter-settings/dashboard-filter-settings.component.spec.ts
  apps/back-office/src/app/components/dashboard-filter-settings/dashboard-filter-settings.component.ts
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.html
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/graphql/mutations.ts
  apps/back-office/src/app/dashboard/pages/dashboard/graphql/queries.ts
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.html
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/application/pages/dashboard/graphql/queries.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.html
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/shared/src/lib/components/dashboard-filter/filter-settings-modal/filter-settings-modal.component.html
  libs/shared/src/lib/components/dashboard-filter/filter-settings-modal/filter-settings-modal.component.spec.ts
  libs/shared/src/lib/components/dashboard-filter/filter-settings-modal/filter-settings-modal.component.ts
  libs/shared/src/lib/components/dashboard-filter/graphql/mutations.ts
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.html
  libs/shared/src/lib/components/widgets/common/contextual-filters-settings/contextual-filters-settings.component.html
  libs/shared/src/lib/models/application.model.ts
  libs/shared/src/lib/models/dashboard.model.ts
  libs/shared/src/lib/services/application/graphql/queries.ts
  libs/shared/src/lib/services/context/context.service.ts
  libs/shared/src/lib/services/context/graphql/mutations.ts
Labels: enhancement

#2103 AB#80163 ABC - List fields fix width in grid widgets
  libs/shared/src/lib/components/query-builder/query-builder.component.html
Labels: enhancement

#2108 Add background color in ui-cell directive
  libs/ui/src/lib/table/cell.directive.ts
Labels: enhancement

#2112 feat/AB#80363_use-resource-select-and-reference-data-select-in-surveyjs
  libs/shared/src/lib/survey/components/reference-data-dropdown/reference-data-dropdown.component.html
  libs/shared/src/lib/survey/components/reference-data-dropdown/reference-data-dropdown.component.ts
  libs/shared/src/lib/survey/components/reference-data-dropdown/reference-data-dropdown.module.ts
  libs/shared/src/lib/survey/components/resource-dropdown/resource-dropdown.component.html
  libs/shared/src/lib/survey/components/resource-dropdown/resource-dropdown.component.ts
  libs/shared/src/lib/survey/components/resource-dropdown/resource-dropdown.module.ts
Labels: refactor
