Repository ReliefApplications/ems-frontend, pull requests merged in 2024-05, with the labels that each got.

#2510 Feat/add creation snackbar reference data
  apps/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.ts
Labels: enhancement

#2502 fix/AB#91748_Summary-cards-should-display-the-text-field-not-the-value
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/shared/src/lib/utils/parser/utils.ts
Labels: bug

#2527 Ab#92826 possibility to filter from record
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard.component.ts
Labels: enhancement

#2525 AB#92196 - admin0 using CDN in front
  apps/back-office/src/environments/environment.azure.dev.ts
  apps/back-office/src/environments/environment.type.ts
  apps/front-office/src/environments/environment.azure.dev.ts
  apps/front-office/src/environments/environment.type.ts
  apps/web-widgets/src/environments/environment.azure.dev.ts
  apps/web-widgets/src/environments/environment.type.ts
  libs/shared/src/lib/services/map/map-polygons.service.ts
  libs/shared/src/lib/utils/cache-with-expiry.ts
Labels: enhancement, refactor, beta

#2539 feat/AB#93130_Allow-query-params-to-be-used-for-REST-widgets-using-reference-data
  apps/back-office/src/environments/environment.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.html
  libs/shared/src/lib/components/widgets/chart-settings/tab-main/tab-main.module.ts
  libs/shared/src/lib/components/widgets/chart/chart.component.ts
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.spec.ts
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
  libs/shared/src/lib/components/widgets/common/query-params-mapping/query-params-mapping.component.html
  libs/shared/src/lib/components/widgets/common/query-params-mapping/query-params-mapping.component.scss
  libs/shared/src/lib/components/widgets/common/query-params-mapping/query-params-mapping.component.spec.ts
  libs/shared/src/lib/components/widgets/common/query-params-mapping/query-params-mapping.component.ts
  libs/shared/src/lib/components/widgets/common/query-params-mapping/reference-data-variables-mapping.component.ts
  libs/shared/src/lib/components/widgets/common/template-aggregation-modal/template-aggregation-modal.component.html
  libs/shared/src/lib/components/widgets/common/template-aggregation-modal/template-aggregation-modal.component.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.module.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/shared/src/lib/services/aggregation/aggregation.service.ts
  libs/shared/src/lib/services/aggregation/graphql/queries.ts
  libs/shared/src/lib/services/map/map-layers.service.ts
  libs/shared/src/lib/services/reference-data/reference-data.service.ts
  libs/shared/src/lib/services/widget/widget.service.ts
  libs/shared/src/lib/survey/components/code-editor/code-editor.component.html
  libs/shared/src/lib/survey/components/code-editor/code-editor.component.ts
Labels: enhancement

#2544 Feat/AB#93294 : First part of "Improve UI filter dropdown / tagbox in dashboard filter"
  libs/shared/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder-modal.component.ts
  libs/shared/src/lib/survey/global-properties/popup-width.ts
  libs/shared/src/lib/survey/init.ts
  libs/shared/src/lib/survey/widgets/dropdown-widget.ts
  libs/shared/src/lib/survey/widgets/tagbox-widget.ts
Labels: enhancement

#2549 fix/AB#92208_search_in_question_type_resources_opening_incorrect_modal
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
Labels: bug

#2557 AB#2393799 ABC - Add close button below modal to see attached records on a grid
  libs/shared/src/lib/components/search-resource-grid-modal/search-resource-grid-modal.component.html
Labels: enhancement

#2556 AB#83348 ABC - On some layout loadings, the scroll is by default not all on the left
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
Labels: bug

#2518 AB#91959 - Auth code aggregations directly querying distant API
  apps/front-office/src/app/graphql.module.ts
  apps/web-widgets/src/app/graphql.module.ts
  libs/shared/src/lib/components/widgets/chart/chart.component.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/services/reference-data/reference-data.service.ts
  libs/shared/src/lib/utils/reference-data/data-transformer.util.ts
  libs/shared/src/lib/utils/reference-data/filter.util.ts
Labels: enhancement, beta

#2582 Ab#94322 : Indicate filter loading in layout
  libs/shared/src/lib/components/query-builder/query-builder.module.ts
  libs/shared/src/lib/components/query-builder/tab-filter/tab-filter.component.html
  libs/shared/src/lib/components/query-builder/tab-filter/tab-filter.component.ts
Labels: enhancement

#2580 AB#94323 false value not appearing on filter
  libs/ui/src/lib/select-menu/select-menu.component.ts
Labels: bug

#2577 Ab#94155 wrong app id would produce infinite loading
  apps/back-office/src/app/guards/can-deactivate.guard.ts
  apps/front-office/src/app/application/application.component.ts
  apps/front-office/src/app/guards/can-deactivate.guard.ts
  libs/shared/src/lib/services/application/application.service.ts
Labels: bug, enhancement
