Repository ReliefApplications/ems-frontend, pull requests merged in 2024-01, with the labels that each got.

#2117 AB#80203_remove_graphql_from_export_functions
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
Labels: enhancement

#2238 bugfix/AB#82795_ABC-summary-cards-using-reference-data-seems-to-send-twice-a-reference-data-query
  libs/shared/src/lib/components/controls/reference-data-select/reference-data-select.component.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/components/widgets/editor/graphql/queries.ts
  libs/shared/src/lib/components/widgets/summary-card/graphql/queries.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/shared/src/lib/services/reference-data/reference-data.service.ts
Labels: enhancement, refactor

#2236 feat/AB#82794_Change-delete-icon-to-be-red-and-drag-drop-to-be-grey
  libs/shared/src/lib/components/navbar/navbar.component.html
  libs/shared/src/lib/components/navbar/navbar.component.ts
  libs/shared/src/lib/components/role-summary/role-auto-assignment/role-auto-assignment.component.html
  libs/shared/src/lib/components/templates/templates.component.html
  libs/shared/src/lib/components/widgets/common/sorting-settings/sorting-settings.component.html
Labels: enhancement

#2242 bugfix/AB#79543_fix_ui_library_tests
  libs/ui/src/lib/cron-editor/cron-editor.component.spec.ts
  libs/ui/src/lib/cron-editor/time-picker/time-picker.component.spec.ts
  libs/ui/src/lib/dialog/dialog-close.directive.spec.ts
  libs/ui/src/lib/dialog/dialog.component.spec.ts
  libs/ui/src/lib/graphql-select/graphql-select.component.spec.ts
  libs/ui/src/lib/snackbar/snackbar.component.spec.ts
  libs/ui/src/lib/spinner/spinner.component.spec.ts
  libs/ui/src/lib/textarea/textarea.component.spec.ts
Labels: bug

#2231 bugfix/AB#82677_ABC-popup-is-not-opening-when-clicking-available-grid-fields-on-question-of-type-resources
  libs/shared/src/index.ts
  libs/shared/src/lib/components/config-display-grid-fields-modal/config-display-grid-fields-modal.component.css
  libs/shared/src/lib/survey/components/resource-available-fields/config-display-grid-fields-modal/config-display-grid-fields-modal.component.html
  libs/shared/src/lib/survey/components/resource-available-fields/config-display-grid-fields-modal/config-display-grid-fields-modal.component.spec.ts
  libs/shared/src/lib/survey/components/resource-available-fields/config-display-grid-fields-modal/config-display-grid-fields-modal.component.ts
  libs/shared/src/lib/survey/components/resource-available-fields/config-display-grid-fields-modal/public-api.ts
  libs/shared/src/lib/survey/components/resource-available-fields/resource-available-fields.component.ts
Labels: bug

#2230 feat/AB#82647-time-format-in-filter
  libs/shared/src/lib/components/ui/core-grid/date-filter-menu/date-filter-menu.component.html
  libs/shared/src/lib/components/ui/core-grid/date-filter-menu/date-filter-menu.component.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
Labels: enhancement

#2228 AB#82416_modern_filter_closes_sidebar_and_prevents_its_opening
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.html
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.module.ts
  libs/shared/src/lib/components/dashboard-filter/directives/modern-drawer-positioner/modern-drawer-positioner.directive.spec.ts
  libs/shared/src/lib/components/dashboard-filter/directives/modern-drawer-positioner/modern-drawer-positioner.directive.ts
  libs/shared/src/lib/components/dashboard-filter/directives/modern-drawer-positioner/modern-drawer-positioner.module.ts
  libs/ui/src/lib/sidenav/sidenav-container.component.ts
Labels: bug

#2246 fix/AB#82869-value-not-appearing-in-layer-popup-when-zero
  libs/shared/src/lib/components/ui/map/map-popup/map-popup.component.ts
Labels: bug

#2249 feat/AB#72599_improve_history_section_of_record
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/record-history/record-history.component.html
  libs/shared/src/lib/components/record-history/record-history.component.ts
Labels: enhancement

#2248 fix/AB#82901-form-number-questions-dont-accept-0-as-answer
  libs/shared/src/lib/services/form-helper/form-helper.service.ts
Labels: bug

#2247 bugfix/AB#82861_ABC-editing-fields-on-resources-question-not-reflecting-in-form-builder
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.html
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/components/ui/core-grid/models/grid-settings.model.ts
  libs/shared/src/lib/survey/components/resource.ts
  libs/shared/src/lib/survey/components/resources.ts
  libs/shared/src/lib/survey/components/utils.ts
Labels: bug, refactor

#2250 bugfix/AB#82908_fix-all-dialog-display-inside-survey-form-builder
  libs/shared/src/lib/survey/components/geofields-listbox/geofields-listbox.component.ts
  libs/shared/src/lib/survey/components/resource.ts
  libs/shared/src/lib/survey/components/resources.ts
  libs/shared/src/lib/survey/components/utils.ts
Labels: bug

#2252 refactor/AB#82670_serverside-introspection
  libs/shared/src/lib/components/ui/core-grid/graphql/queries.ts
  libs/shared/src/lib/components/widgets/grid/graphql/queries.ts
  libs/shared/src/lib/models/metadata.model.ts
  libs/shared/src/lib/services/query-builder/graphql/queries.ts
  libs/shared/src/lib/services/query-builder/query-builder.service.ts
Labels: refactor

#2261 feat/AB#83059-useless-queries-graphql-fields-in-widget-queries
  libs/shared/src/lib/components/controls/reference-data-select/reference-data-select.component.ts
  libs/shared/src/lib/components/controls/resource-select/resource-select.component.ts
  libs/shared/src/lib/components/widgets/chart/chart.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.html
  libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/graphql/queries.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.html
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.component.html
  libs/shared/src/lib/components/widgets/grid-settings/tab-buttons/tab-buttons.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/graphql/queries.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
  libs/ui/src/lib/graphql-select/graphql-select.component.ts
  libs/ui/src/lib/select-menu/select-menu.component.ts
Labels: enhancement, refactor

#2239 feat/AB#80271_filter_not_shared_between_pages
  libs/shared/src/lib/survey/global-properties/reference-data.ts
Labels: enhancement

#2266 AB#83137 - Remove download option from the map widget.
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-controls/map-controls.component.html
Labels: enhancement

#2263 Feat/ab#83099 allow dashboard filter to have default values
  libs/shared/src/lib/services/context/context.service.ts
Labels: enhancement

#2225 fix/AB#82405_incorrect_text_in_unique_value_renderer
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/unique-value-renderer/unique-value-renderer.component.html
Labels: bug

#2229 bugfix/AB#82624_tab-widgets-inner-widgets-order-is-not-applied-when-tab-widget-shrinks-to-a-certain-width
  libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.html
Labels: bug

#2217 Bugfix/ab#82256 summary card and text widgets checkbox inconclusive
  libs/shared/src/lib/utils/parser/utils.ts
Labels: bug

#2268 feat/AB#83205_add_possibility_to_remove_selected_reference_data_in_form_questions
  libs/shared/src/lib/survey/components/reference-data-dropdown/reference-data-dropdown.component.html
  libs/shared/src/lib/survey/components/reference-data-dropdown/reference-data-dropdown.component.ts
  libs/shared/src/lib/survey/components/reference-data-dropdown/reference-data-dropdown.module.ts
Labels: enhancement

#2273 AB#83184 - Reference data not appearing in form builder.
  libs/shared/src/lib/survey/components/reference-data-dropdown/reference-data-dropdown.component.ts
Labels: bug

#2278 feat/AB#83237_use_regex_when_using_reference_data_and_dashboard_filter
  libs/shared/src/lib/utils/filter/reference-data-filter.util.ts
Labels: enhancement

#2271 AB#82974 : Highlight aggregate card when selected
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
Labels: enhancement

#2281 Feat/ab#83306 : Reflect changes to filter using aggregate cards
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
Labels: enhancement

#2285 fix/AB#83339-'or'-logic-with-no-filter-value-prevents-data-loading
  libs/shared/src/lib/utils/filter/reference-data-filter.util.ts
Labels: bug

#2283 Ab#83334 change dashboard filter styling
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.scss
Labels: bug

#2288 Feat/ab#83099 load dashboard filter default value expression
  libs/shared/src/lib/services/context/context.service.ts
Labels: enhancement

#2289 Feat/ab#83311 : Add ability to view history as table
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/record-history/record-history.component.html
  libs/shared/src/lib/components/record-history/record-history.component.scss
  libs/shared/src/lib/components/record-history/record-history.component.ts
  libs/shared/src/lib/components/record-history/record-history.module.ts
Labels: enhancement

#2292 feat/AB#83384-fit-zoom-on-country-when-passed-to-map
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/ui/map/interfaces/map.interface.ts
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/widgets/map-settings/map-forms.ts
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-properties.component.ts
  libs/shared/src/lib/components/widgets/map-settings/map-settings.component.ts
  libs/shared/src/lib/services/context/context.service.ts
  libs/shared/src/lib/services/map/map-polygons.service.ts
  package-lock.json
Labels: enhancement

#2294 Feat/ab#83099 load dashboard filter default value expression fix
  libs/shared/src/lib/services/context/context.service.ts
Labels: bug

#2275 feat/AB#83067_paginated-refData
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/graphql/mutations.ts
  apps/back-office/src/app/dashboard/pages/reference-data/graphql/queries.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.form.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.module.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.html
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.scss
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.spec.ts
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
  libs/shared/src/lib/components/widgets/editor-settings/record-selection-tab/record-selection-tab.component.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/graphql/queries.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.ts
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.forms.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.html
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/shared/src/lib/models/reference-data.model.ts
  libs/shared/src/lib/services/context/context.service.ts
  libs/shared/src/lib/services/reference-data/graphql/queries.ts
  libs/shared/src/lib/services/reference-data/reference-data.service.ts
  libs/shared/src/lib/survey/widgets/dropdown-widget.ts
  libs/ui/src/lib/form-wrapper/form-wrapper.directive.ts
  libs/ui/src/lib/paginator/paginator.component.html
  libs/ui/src/lib/paginator/paginator.component.ts
Labels: enhancement, refactor

#2296 feat/AB#83716-default-zoom-after-removing-country-zoom
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/shared/src/lib/services/context/context.service.ts
Labels: enhancement

#2300 Feat/ab#83311 change history table column value
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/record-history/record-history.component.html
  libs/shared/src/lib/components/record-history/record-history.component.ts
Labels: enhancement

#2301 Ab#83728 add graphql variables support for aggregations inside text widget
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
  libs/shared/src/lib/components/widgets/common/template-aggregation-modal/graphql/queries.ts
  libs/shared/src/lib/components/widgets/common/template-aggregation-modal/template-aggregation-modal.component.html
  libs/shared/src/lib/components/widgets/common/template-aggregation-modal/template-aggregation-modal.component.ts
  libs/shared/src/lib/components/widgets/editor-settings/editor-settings.forms.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/services/aggregation/aggregation.service.ts
  libs/shared/src/lib/services/aggregation/graphql/queries.ts
Labels: enhancement

#2304 Feat/ab#83873 increase history width
  libs/shared/src/lib/components/record-history/record-history.component.html
  libs/shared/src/lib/components/record-modal/record-modal.component.ts
Labels: enhancement

#2297 feat/AB#83726-be-able-to-pass-graphql-variables-in-map-layers
  libs/shared/src/lib/components/ui/map/interfaces/layer-settings.type.ts
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.module.ts
  libs/shared/src/lib/components/widgets/map-settings/graphql/queries.ts
  libs/shared/src/lib/components/widgets/map-settings/map-forms.ts
  libs/shared/src/lib/models/layer.model.ts
  libs/shared/src/lib/services/map/graphql/queries.ts
  libs/shared/src/lib/services/map/map-layers.service.ts
Labels: enhancement

#2307 Fix/ab#83236 translation issue in component settings
  apps/back-office/src/app/components/dashboard-filter-settings/dashboard-filter-settings.component.html
Labels: bug

#2310 AB#84015 -Remove dashboard property from context service
  apps/back-office/src/app/components/dashboard-filter-settings/dashboard-filter-settings.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.html
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard.component.html
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/shared/src/lib/services/context/context.service.ts
Labels: refactor

#2226 feat/AB#82193-addFields-aggregation-reference-data
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.html
  libs/shared/src/lib/components/ui/aggregation-builder/aggregation-builder.component.ts
  libs/shared/src/lib/components/ui/aggregation-builder/pipeline/pipeline.component.ts
Labels: enhancement

#2313 feat/AB#84016_prevent_graphql_variable_mapping_inject_variables_whenever_open_the_settings
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.html
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
Labels: enhancement

#2280 AB#83231 - Users question is editable even if readonly mode
  libs/shared/src/lib/survey/components/users.ts
Labels: bug

#2311 Feat/ab#84013 min height for dashboard and tabs widget
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.html
  apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/widget-grid/widget-grid.component.html
  libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
  libs/shared/src/lib/components/widgets/tabs-settings/tab-grid-settings-modal/tab-grid-settings-modal.component.html
  libs/shared/src/lib/components/widgets/tabs-settings/tab-grid-settings-modal/tab-grid-settings-modal.component.ts
  libs/shared/src/lib/components/widgets/tabs-settings/tabs-settings.form.ts
Labels: enhancement

#2314 feat/AB#83312_make_the_width_history_view_resizeable
  apps/back-office/src/app/dashboard/pages/form-records/form-records.component.ts
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/shared/src/lib/components/form/form.component.ts
  libs/shared/src/lib/components/record-history-modal/record-history-modal.component.html
  libs/shared/src/lib/components/record-history/record-history.component.html
  libs/shared/src/lib/components/record-history/record-history.component.ts
  libs/shared/src/lib/components/record-history/record-history.module.ts
  libs/shared/src/lib/components/record-modal/record-modal.component.html
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
  libs/ui/src/lib/dialog/dialog.component.html
  libs/ui/src/lib/dialog/dialog.component.ts
  libs/ui/src/lib/dialog/dialog.module.ts
  package-lock.json
  package.json
Labels: enhancement

#2315 fix/AB#84058-replaceFilter-method-contextService-casts-objects-to-strings
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
  libs/shared/src/lib/services/context/context.service.ts
  libs/shared/src/lib/services/reference-data/reference-data.service.ts
Labels: bug

#2321 AB#83334_change_modern_filter_styling
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.html
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.scss
Labels: enhancement

#2319 feat/AB#83917_refactor_layers_query_in_map_edition
  libs/shared/src/lib/components/widgets/map-settings/map-layers/map-layers.component.ts
  libs/shared/src/lib/services/map/map-layers.service.ts
Labels: enhancement, refactor

#2323 fix/AB#84247_when_change_refData_graphql_pagination_need_select_offset_and_pageSizeVariables
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
Labels: bug

#2317 Feat/AB#83931 : Allow editor filters to also reset other filters on click
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/const/tinymce.const.ts
  libs/shared/src/lib/survey/widgets/text-widget.ts
Labels: enhancement

#2324 AB#84099 - Pagination for reference data loads new data when changing page
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: bug

#2326 AB#84253_filter_not_reloading_when_several_widgets
  libs/shared/src/lib/services/context/context.service.ts
Labels: bug

#2330 feat/AB#84288-prevent-interpreting-values-when-using-data-as-expressions
  libs/shared/src/lib/utils/parser/utils.ts
Labels: enhancement

#2339 fix/AB#84405-Incorrect-display-graphql-variables-mapping
  libs/shared/src/lib/components/widgets/chart-settings/tab-main/tab-main.component.html
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.html
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
  libs/shared/src/lib/components/widgets/common/template-aggregation-modal/template-aggregation-modal.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
Labels: bug

#2336 Ab#84408 prevent loading previous value for minimum height
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
Labels: bug

#2334 AB#84254 : Fix context filters with summary cards
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: bug

#2338 Fix/ab#form configuration bug when using old ref data
  libs/shared/src/lib/survey/global-properties/reference-data.ts
Labels: bug

#2340 feat/AB#83873_increase_history_width
  libs/shared/src/lib/components/form-modal/form-modal.component.ts
Labels: bug, enhancement

#2342 AB#84326 : Fix duplication of summary cards when using filters
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
Labels: bug

#2325 fix/AB#83183_default-value-modal-with-choices-from-ref-data
  libs/shared/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder-modal.component.ts
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/shared/src/lib/survey/global-properties/reference-data.ts
  libs/shared/src/lib/survey/widgets/dropdown-widget.ts
Labels: bug

#2343 feat/AB#84481_allow_user_vertically_resize_code_editor_in_reference_data
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.html
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.component.ts
  apps/back-office/src/app/dashboard/pages/reference-data/reference-data.module.ts
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.html
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
  libs/shared/src/lib/components/widgets/common/template-aggregation-modal/template-aggregation-modal.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-datasource/layer-datasource.component.html
  libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-general/summary-card-general.component.html
Labels: enhancement

#2345 fix/AB#84582 missing trad for question clear icon
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
Labels: bug

#2346 Feat/ab#84617 allow custom styling sidenav resizing
  apps/back-office/src/app/components/custom-style/custom-style.component.html
  apps/back-office/src/app/components/custom-style/custom-style.component.ts
  libs/shared/src/lib/components/custom-widget-style/custom-widget-style.component.html
  libs/shared/src/lib/components/custom-widget-style/custom-widget-style.component.ts
  libs/shared/src/lib/components/record-history/record-history.component.ts
Labels: enhancement

#2351 Fix/ab#84761 changing aggregation reset graphql variables
  libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
Labels: bug

#2295 Ab#83681 support for context in front office without templates
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/graphql/queries.ts
  apps/back-office/src/environments/environment.ts
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/application/pages/dashboard/graphql/queries.ts
  apps/front-office/src/environments/environment.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/graphql/queries.ts
  libs/shared/src/lib/models/dashboard.model.ts
  libs/shared/src/lib/services/context/context.service.ts
  libs/shared/src/lib/services/dashboard/dashboard.service.ts
  libs/shared/src/lib/services/dashboard/graphql/mutations.ts
Labels: bug, enhancement
