Repository ReliefApplications/ems-frontend, pull requests merged in 2024-04, with the labels that each got.

#2464 Feat/ab#88998 keep heatmap scale while zooming
  libs/shared/src/lib/components/ui/map/utils/leaflet-heatmap.js
Labels: enhancement

#2494 AB#91488 - refactor CS queries used by summary cards widgets, in order to save s…
  libs/shared/src/lib/services/reference-data/graphql/queries.ts
  libs/shared/src/lib/services/reference-data/reference-data.service.ts
Labels: enhancement, refactor, beta

#2498 AB#91553 - fix issue with search term on action buttons of dashboard #91553
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-actions-modal/edit-button-actions-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-actions-modal/edit-button-actions-modal.component.ts
Labels: bug, next
