Repository ReliefApplications/ems-frontend, pull requests merged in 2024-10, with the labels that each got.

#2639 Feat/ab#104252 eis map widget layers should always appear based on the order admins configured them
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/ui/core-grid/map-modal/map-modal.component.ts
  libs/shared/src/lib/components/ui/map/layer.ts
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
  libs/shared/src/lib/components/widgets/map-settings/map-layers/map-layers.component.html
  libs/shared/src/lib/components/widgets/map-settings/map-layers/map-layers.component.ts
  libs/shared/src/lib/components/widgets/map-settings/map-layers/map-layers.module.ts
  libs/shared/src/lib/models/layer.model.ts
  libs/shared/src/lib/services/map/map-layers.service.ts
Labels: enhancement, beta

#2642 fix/AB#104241_EIS-use-correct-header-when-opening-html-question-in-modal-from-grid
  libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
Labels: bug

#2647 fix/AB#104349_ABC-make-sure-pages-with-visible-set-to-false-are-hidden-in-front-office
  apps/back-office/src/app/app-preview/app-preview.component.ts
  apps/back-office/src/app/application/application.component.html
  apps/back-office/src/app/application/application.component.ts
  apps/front-office/src/app/application/application.component.ts
  libs/shared/src/lib/components/navbar/navbar.component.html
  libs/shared/src/lib/components/navbar/navbar.component.ts
  libs/shared/src/lib/components/ui/map/layer.ts
Labels: bug, beta

#2648 feat/AB#104296_EIS-add-date-field-calc-method-for-html-widgets
  apps/back-office/src/app/app.component.ts
  apps/back-office/src/app/app.module.ts
  apps/front-office/src/app/app.component.ts
  apps/front-office/src/app/app.module.ts
  apps/front-office/src/environments/environment.ts
  libs/shared/src/index.ts
  libs/shared/src/lib/components/query-builder/tab-fields/tab-fields.component.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.module.ts
  libs/shared/src/lib/components/ui/core-grid/grid/utils/grid-data-formatter.ts
  libs/shared/src/lib/models/grid.model.ts
  libs/shared/src/lib/services/data-template/data-template.service.ts
  libs/shared/src/lib/services/grid-data-formatter/grid-data-formatter.helper.ts
  libs/shared/src/lib/services/grid-data-formatter/grid-data-formatter.service.spec.ts
  libs/shared/src/lib/services/grid-data-formatter/grid-data-formatter.service.ts
  libs/shared/src/lib/services/html-parser/html-parser-helper.ts
  libs/shared/src/lib/services/html-parser/html-parser.service.spec.ts
  libs/shared/src/lib/services/html-parser/html-parser.service.ts
  libs/shared/src/lib/utils/parser/calcFunctions.ts
  libs/shared/src/lib/utils/parser/utils.ts
Labels: enhancement, refactor, beta

#2643 Feat/ab#104243 eis allow html questions to display as html in grids
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.module.ts
  libs/shared/src/lib/pipes/strip-html/strip-html.pipe.spec.ts
  libs/shared/src/lib/pipes/strip-html/strip-html.pipe.ts
  libs/shared/src/lib/shared.module.ts
Labels: enhancement, beta

#2649 bug/AB#104381_EIS-remove-selected-rows-on-actions
  libs/shared/src/lib/components/widgets/grid/grid.component.ts
Labels: bug

#2656 feat/AB#104485_EIS-determine-best-way-to-configure-heatmap
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.ts
  libs/shared/src/lib/components/ui/map/interfaces/layer-settings.type.ts
  libs/shared/src/lib/components/ui/map/layer.ts
  libs/shared/src/lib/components/widget-grid/edit-widget-modal/edit-widget-modal.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/class-break-renderer/class-break-renderer.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/class-break-renderer/class-break-renderer.component.scss
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/class-break-renderer/class-break-renderer.component.spec.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/class-break-renderer/class-break-renderer.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/layer-styling.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/layer-styling.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/layer-styling.module.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/unique-value-renderer/unique-value-renderer.component.html
  libs/shared/src/lib/components/widgets/map-settings/map-forms.ts
  libs/shared/src/lib/models/layer.model.ts
  libs/shared/src/lib/services/map/graphql/queries.ts
Labels: enhancement, beta

#2650 feat/AB#104427_EIS-Use-of-custom-filter-in-resources-grid-field
  libs/shared/src/lib/survey/components/resource-custom-filters/resource-custom-filters.component.ts
  libs/shared/src/lib/survey/components/resource.ts
  libs/shared/src/lib/survey/components/resources.ts
  libs/shared/src/lib/survey/components/utils.ts
Labels: enhancement, beta

#2651 feat/AB#104447_EIS-configure-file-types-max-size-and-number-of-files
  apps/back-office/src/app/app.component.ts
  apps/front-office/src/app/app.component.ts
  apps/web-widgets/src/app/app.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/index.ts
  libs/shared/src/lib/components/form-builder/form-builder.component.ts
  libs/shared/src/lib/components/form-modal/form-modal.component.ts
  libs/shared/src/lib/components/form/form.component.ts
  libs/shared/src/lib/services/document-management/document-management.service.ts
  libs/shared/src/lib/services/form-builder/form-builder.service.ts
  libs/shared/src/lib/services/form-helper/form-helper.service.ts
  libs/shared/src/lib/survey/components/accepted-value-types-text/accepted-value-types-text.component.spec.ts
  libs/shared/src/lib/survey/components/accepted-value-types-text/accepted-value-types-text.component.ts
  libs/shared/src/lib/survey/components/accepted-value-types-text/accepted-value-types-text.model.ts
  libs/shared/src/lib/survey/components/accepted-value-types-text/public-api.ts
  libs/shared/src/lib/survey/components/utils/components.enum.ts
  libs/shared/src/lib/survey/creator.ts
  libs/shared/src/lib/survey/global-properties/others.ts
  libs/shared/src/lib/survey/localization.ts
Labels: enhancement

#2658 bug/AB#104570_EIS-More-testing-of-application-shortcut
  libs/shared/src/lib/services/auth/auth.service.ts
Labels: bug, beta

#2652 feat/AB#104463_EIS-document-properties-logic
  apps/back-office/src/app/app.component.ts
  apps/front-office/src/app/app.component.ts
  apps/web-widgets/src/app/app.component.ts
  libs/shared/src/index.ts
  libs/shared/src/lib/services/document-management/document-management.service.ts
  libs/shared/src/lib/services/form-builder/form-builder.service.ts
  libs/shared/src/lib/services/form-helper/form-helper.service.ts
  libs/shared/src/lib/survey/components/cs-docs-properties-dropdown/cs-docs-properties-dropdown.component.html
  libs/shared/src/lib/survey/components/cs-docs-properties-dropdown/cs-docs-properties-dropdown.component.scss
  libs/shared/src/lib/survey/components/cs-docs-properties-dropdown/cs-docs-properties-dropdown.component.ts
  libs/shared/src/lib/survey/components/cs-docs-properties-dropdown/cs-docs-properties-dropdown.model.ts
  libs/shared/src/lib/survey/components/cs-docs-properties-dropdown/cs-docs-properties-dropdown.module.ts
  libs/shared/src/lib/survey/components/cs-docs-properties-dropdown/public-api.ts
  libs/shared/src/lib/survey/components/resource-dropdown/resource-dropdown.component.ts
  libs/shared/src/lib/survey/components/users-dropdown/users-dropdown.component.ts
  libs/shared/src/lib/survey/components/utils/components.enum.ts
  libs/shared/src/lib/survey/global-properties/cs-api-docs.ts
  libs/shared/src/lib/survey/init.ts
  libs/shared/src/lib/survey/types.ts
  libs/shared/src/lib/survey/widgets/file-widget.ts
Labels: enhancement

#2657 feat/AB#104476_EIS-Start-custom-action-buttons-redesign
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
Labels: enhancement, beta

#2663 feat/AB#104720_EIS-implement-add-record-action-of-dashboard-buttons
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-selector/context-selector.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/graphql/queries.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-actions-modal/edit-button-actions-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/environments/environment.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/button-action/button-action-type.ts
  libs/shared/src/lib/components/button-action/button-action.component.ts
  libs/shared/src/lib/components/button-action/graphql/mutations.ts
  libs/shared/src/lib/components/button-action/graphql/queries.ts
  libs/shared/src/lib/components/form-modal/form-modal.component.ts
  libs/shared/src/lib/models/page.model.ts
  libs/shared/src/lib/services/confirm/confirm.service.ts
  libs/ui/src/lib/select-menu/select-menu.component.ts
Labels: enhancement, changes

#2666 bugfix/AB#104811_EIS-Incorrect-generated-urls-in-front-office
  libs/shared/src/lib/services/data-template/data-template.service.ts
Labels: beta

#2660 AB#104621 EIS-Make-custom-action-functional
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/button-action/button-action-type.ts
  libs/shared/src/lib/components/button-action/button-action.component.ts
  libs/shared/src/lib/services/dashboard/dashboard.service.ts
Labels: enhancement, beta

#2661 feat/AB#104719_EIS-implement-email-actions-of-dashboard-buttons
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-actions-modal/edit-button-actions-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  libs/shared/src/index.ts
  libs/shared/src/lib/components/button-action/button-action-type.ts
  libs/shared/src/lib/components/button-action/button-action.component.ts
  libs/shared/src/lib/components/email/email.service.ts
  libs/shared/src/lib/components/email/public-api.ts
  libs/shared/src/lib/models/email-notifications.model.ts
  libs/shared/src/lib/services/dashboard/dashboard.service.ts
Labels: enhancement, changes

#2659 feat/AB#104622_EIS-selectionof-occurrence-in-properties-of-doc-upload
  libs/doc-management/src/lib/components/document-upload/document-upload.component.ts
  libs/shared/src/lib/services/document-management/document-management.service.ts
  libs/shared/src/lib/services/document-management/graphql/queries.ts
  libs/shared/src/lib/survey/components/cs-docs-properties-dropdown/cs-docs-properties-dropdown.component.html
  libs/shared/src/lib/survey/components/cs-docs-properties-dropdown/cs-docs-properties-dropdown.component.ts
  libs/shared/src/lib/survey/global-properties/cs-api-docs.ts
  libs/shared/src/lib/survey/init.ts
  libs/shared/src/lib/survey/widgets/file-widget.ts
Labels: enhancement, beta
