Repository ReliefApplications/ems-frontend, pull requests merged in 2024-06, with the labels that each got.

#2595 feat/AB#94899 - Add searchbar to fields in sorting and filtering in widget settings
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.html
  libs/shared/src/lib/components/query-builder/tab-sort/tab-sort.component.html
  libs/shared/src/lib/components/widgets/common/sorting-settings/sorting-settings.component.html
Labels: enhancement

#2563 AB#16252 - Email Notifications Phase 1 Fixes
  apps/back-office/src/app/app-preview/app-preview.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.html
  libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.ts
  libs/shared/src/lib/components/email/components/email-template/email-template.component.html
  libs/shared/src/lib/components/email/components/email-template/email-template.component.scss
  libs/shared/src/lib/components/email/components/email-template/email-template.component.ts
  libs/shared/src/lib/components/email/components/ems-template/ems-template.component.html
  libs/shared/src/lib/components/email/components/ems-template/ems-template.component.ts
  libs/shared/src/lib/components/email/constant.ts
  libs/shared/src/lib/components/email/email.component.html
  libs/shared/src/lib/components/email/email.component.ts
  libs/shared/src/lib/components/email/email.service.ts
  libs/shared/src/lib/components/email/filter/filter.constant.ts
  libs/shared/src/lib/components/email/graphql/queries.ts
  libs/shared/src/lib/components/email/steps/create-dataset/create-dataset.component.html
  libs/shared/src/lib/components/email/steps/create-dataset/create-dataset.component.ts
  libs/shared/src/lib/components/email/steps/create-notification/create-notification.component.ts
  libs/shared/src/lib/components/email/steps/layout/layout.component.ts
  libs/shared/src/lib/components/email/steps/preview/preview.component.html
  libs/shared/src/lib/components/email/steps/preview/preview.component.scss
  libs/shared/src/lib/components/email/steps/preview/preview.component.ts
  libs/shared/src/lib/components/email/steps/select-distribution/select-distribution.component.html
  libs/shared/src/lib/components/email/steps/select-distribution/select-distribution.component.ts
  libs/shared/src/lib/components/role-summary/role-summary.component.ts
  libs/shared/src/lib/services/auth/auth.service.ts
  libs/shared/src/lib/services/query-builder/query-builder.service.ts
  libs/ui/src/lib/snackbar/snackbar.service.ts
Labels: enhancement, dependencies

#2596 Bug/ab#83434 Using disabled with formcontrol on ui-select-menu
  libs/shared/src/lib/components/templates/components/edit-template-modal/edit-template-modal.component.html
  libs/shared/src/lib/components/templates/components/edit-template-modal/edit-template-modal.component.ts
  libs/shared/src/lib/components/widgets/map-settings/map-properties/map-properties.component.html
Labels: bug

#2597 bug/AB#95169 - Redirection to resource page now works properly upon its creation
  apps/back-office/src/app/dashboard/pages/resources/graphql/mutations.ts
  apps/back-office/src/app/dashboard/pages/resources/resources.component.ts
Labels: bug

#2599 Bug/ab#95183 - Sidenav collapsing on form builder firefox
  libs/ui/src/lib/sidenav/sidenav-container.component.html
Labels: bug

#2611 AB#90518 Email Notifications Number Fix
  libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.ts
  libs/shared/src/lib/components/email/components/email-template/email-template.component.ts
  libs/shared/src/lib/components/email/components/ems-template/ems-template.component.ts
  libs/shared/src/lib/components/email/email.component.ts
  libs/shared/src/lib/components/email/email.service.ts
  libs/shared/src/lib/components/email/filter/filter.constant.ts
Labels: enhancement, dependencies

#2608 feat/AB#95450 - Added snackbars on missing places
  apps/back-office/src/app/dashboard/pages/forms/forms.component.ts
  apps/back-office/src/app/dashboard/pages/reference-datas/reference-datas.component.ts
  apps/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.ts
  apps/back-office/src/app/dashboard/pages/resource/calculated-fields-tab/calculated-fields-tab.component.ts
  apps/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.ts
  apps/back-office/src/app/dashboard/pages/resources/resources.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/lib/components/aggregation/add-aggregation-modal/add-aggregation-modal.component.ts
  libs/shared/src/lib/components/grid-layout/add-layout-modal/add-layout-modal.component.ts
Labels: enhancement

#2601 Ab#94531 change templates logic
  apps/back-office/src/app/application/pages/channels/channels.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-selector/context-selector.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-selector/context-selector.component.scss
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-selector/context-selector.component.spec.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/context-selector/context-selector.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-context-modal/edit-context-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-context-modal/edit-context-modal.component.scss
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-context-modal/edit-context-modal.component.spec.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-context-modal/edit-context-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-context-modal/graphql/queries.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/manage-templates-modal/manage-templates-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/manage-templates-modal/manage-templates-modal.component.scss
  apps/back-office/src/app/dashboard/pages/dashboard/components/manage-templates-modal/manage-templates-modal.component.spec.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/manage-templates-modal/manage-templates-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.module.ts
  apps/back-office/src/app/dashboard/pages/dashboard/graphql/mutations.ts
  apps/back-office/src/app/dashboard/pages/dashboard/graphql/queries.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/notifications/components/edit-notification-modal/edit-notification-modal.component.ts
  libs/shared/src/lib/components/templates/templates.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/button-config/button-config.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
  libs/shared/src/lib/models/application.model.ts
  libs/shared/src/lib/models/dashboard.model.ts
  libs/shared/src/lib/models/template.model.ts
  libs/shared/src/lib/services/application/application.service.ts
  libs/shared/src/lib/services/application/graphql/mutations.ts
  libs/shared/src/lib/services/context/context.service.ts
  libs/ui/src/lib/menu/menu.component.html
  libs/ui/src/lib/menu/menu.component.ts
  libs/ui/src/lib/select-menu/select-menu.component.ts
Labels: enhancement, beta
