Repository ReliefApplications/ems-frontend, pull requests merged in 2024-12, with the labels that each got.

#2717 feat/AB#106561_EIS-user-activity-improve-filtering-and-pagination
  libs/shared/src/lib/components/activity-log/activity-log.component.html
  libs/shared/src/lib/components/activity-log/activity-log.component.scss
  libs/shared/src/lib/components/activity-log/activity-log.component.ts
  libs/shared/src/lib/components/activity-log/activity-log.module.ts
  libs/shared/src/lib/components/activity-log/graphql/queries.ts
  libs/shared/src/lib/models/activity-log.model.ts
Labels: enhancement

#2728 Ab#106123 Email Notifications - Warning message if the records are more than 50 in Step 2 issue resolved
  libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.html
  libs/shared/src/lib/components/email/components/email-template/email-template.component.html
Labels: bug, changes

#2730 AB EN minor UI bug fixes and linting
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.html
  libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.ts
  libs/shared/src/lib/components/email/components/email-template/email-template.component.html
  libs/shared/src/lib/components/email/components/email-template/email-template.component.ts
Labels: bug

#2729 Ab#106123 en dl edit issue preview improvement
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/email/components/email-template/email-template.component.html
  libs/shared/src/lib/components/email/components/email-template/email-template.component.ts
  libs/shared/src/lib/components/email/components/ems-template/ems-template.component.ts
  libs/shared/src/lib/components/email/email.service.ts
  libs/shared/src/lib/components/email/graphql/queries.ts
  libs/shared/src/lib/components/email/steps/select-distribution/select-distribution.component.html
  libs/shared/src/lib/components/email/steps/select-distribution/select-distribution.component.ts
Labels: enhancement

#2731 feat/AB#107501_EIS-user-activity-track-page-title
  .husky/pre-commit
  apps/back-office/src/app/application/application-routing.module.ts
  apps/back-office/src/app/application/pages/form/form.component.ts
  apps/back-office/src/app/application/pages/workflow/workflow-routing.module.ts
  apps/back-office/src/app/dashboard/dashboard-routing.module.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/application/application-routing.module.ts
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/application/pages/form/form.component.ts
  apps/front-office/src/app/application/pages/workflow/workflow-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/application/application-routing.module.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/form/form.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/workflow/workflow-routing.module.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/activity-log/activity-log-group-by-page/activity-log-group-by-page.component.html
  libs/shared/src/lib/components/activity-log/activity-log-group-by-page/activity-log-group-by-page.component.ts
  libs/shared/src/lib/components/activity-log/activity-log-list/activity-log-list.component.html
  libs/shared/src/lib/components/activity-log/activity-log-list/activity-log-list.component.ts
  libs/shared/src/lib/components/activity-log/activity-log.component.html
  libs/shared/src/lib/components/activity-log/activity-log.module.ts
  libs/shared/src/lib/components/layout/layout.component.html
  libs/shared/src/lib/services/breadcrumb/breadcrumb.service.ts
  libs/shared/src/lib/services/logger/logger.service.ts
Labels: enhancement

#2736 feat/AB#106560_EIS-improve-activity-log-navigation
  libs/shared/src/lib/services/application/application.service.ts
  libs/shared/src/lib/services/logger/logger.service.ts
Labels: bug

#2737 AB#107605_UserActivityTranslation
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/activity-log/activity-log-group-by-page/activity-log-group-by-page.component.html
  libs/shared/src/lib/components/activity-log/activity-log-group-by-user/activity-log-group-by-user.component.html
  libs/shared/src/lib/components/activity-log/activity-log-list/activity-log-list.component.html
  libs/shared/src/lib/components/activity-log/activity-log.component.html
Labels: alpha

#2738 fix/logger-service-trigger-on-web-element
  apps/web-widgets/src/app/widgets/app-widget/app-widget.component.ts
  libs/shared/src/lib/services/logger/logger.service.ts
Labels: bug, alpha
