Repository ReliefApplications/ems-frontend, pull requests merged in 2024-11, with the labels that each got.

#2670 feat/AB#104883_EIS-add-send-notification-custom-action-buttons
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/index.ts
  libs/shared/src/lib/components/button-action/button-action-type.ts
  libs/shared/src/lib/components/button-action/button-action.component.ts
  libs/shared/src/lib/components/button-action/graphql/queries.ts
  libs/shared/src/lib/components/email/email.service.ts
  libs/shared/src/lib/components/query-builder/public-api.ts
  libs/shared/src/lib/components/templates/components/preview-template-modal/preview-template-modal.component.ts
  libs/shared/src/lib/models/email-notifications.model.ts
  libs/shared/src/lib/services/email/email.service.ts
Labels: enhancement

#2674 Feat/ab#105315 eis allow mapping between resources fields custom action button
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.ts
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.html
  apps/back-office/src/app/dashboard/pages/pull-jobs/components/edit-pull-job-modal/edit-pull-job-modal.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/index.ts
  libs/shared/src/lib/components/button-action/button-action-type.ts
  libs/shared/src/lib/components/button-action/button-action.component.ts
  libs/shared/src/lib/components/email/components/email-template/email-template.component.ts
  libs/shared/src/lib/components/field-mapper/field-mapper.component.html
  libs/shared/src/lib/components/field-mapper/field-mapper.component.scss
  libs/shared/src/lib/components/field-mapper/field-mapper.component.spec.ts
  libs/shared/src/lib/components/field-mapper/field-mapper.component.ts
  libs/shared/src/lib/components/field-mapper/public-api.ts
Labels: refactor

#2675 AB#104882 eis add auto reload of dashboard when using actions that add or edit data
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.html
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard.component.html
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/button-action/button-action-type.ts
  libs/shared/src/lib/components/button-action/button-action.component.ts
Labels: enhancement

#2678 feat/AB#105486_EIS-add-search-bar-in-field-selection-of-mapping-component
  libs/shared/src/lib/components/field-mapper/field-mapper.component.html
Labels: enhancement

#2684 fix/AB#105484_EIS-custom-filtering-for-resources-question-not-working-when-value-is-prepopulated-in-the-form
  libs/shared/src/lib/components/form-modal/form-modal.component.ts
Labels: bug, beta

#2685 feat/AB#105619_EIS-allow-to-auto-select-first-option-of-resource-field-when-using-dynamic-filter
  libs/shared/src/lib/components/search-resource-grid-modal/search-resource-grid-modal.component.ts
  libs/shared/src/lib/survey/components/resource.ts
  libs/shared/src/lib/survey/components/resources.ts
  libs/shared/src/lib/survey/components/utils.ts
Labels: beta

#2688 feat/AB105665_EIS-add-search-bar-and-sort-fields-by-name-in-dashboard-context-setup-popup
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-context-modal/edit-context-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-context-modal/edit-context-modal.component.ts
Labels: beta

#2686 feat/AB#105610_EIS-allow-some-style-attributes-of-html-questions-to-appear-in-grids
  libs/shared/src/lib/components/controls/icon-picker/icon-picker.module.ts
  libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
  libs/shared/src/lib/components/ui/core-grid/grid/grid.module.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/class-break-renderer/class-break-renderer.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/unique-value-renderer/unique-value-renderer.component.ts
  libs/shared/src/lib/pipes/sanitize-html/sanitize-html.module.ts
  libs/shared/src/lib/pipes/sanitize-html/sanitize-html.pipe.ts
  libs/shared/src/lib/pipes/strip-html/strip-html.pipe.ts
  libs/shared/src/lib/pipes/strip-html/strip-html.stories.ts
Labels: beta

#2695 fix/AB#105859_EIS-navigation-to-specific-workflow-tab-doesnt-refresh-stepper
  apps/back-office/src/app/app-preview/pages/workflow/workflow.component.ts
  apps/back-office/src/app/application/pages/workflow/workflow.component.ts
  apps/front-office/src/app/application/pages/workflow/workflow.component.ts
Labels: bug, alpha

#2694 feat/AB#105843_EIS-nested-record-document-upload
  libs/shared/src/lib/components/form-modal/form-modal.component.ts
  libs/shared/src/lib/components/form/form.component.ts
  libs/shared/src/lib/components/resource-modal/resource-modal.component.ts
  libs/shared/src/lib/services/form-builder/form-builder.service.ts
  libs/shared/src/lib/services/form-helper/form-helper.service.ts
Labels: bug

#2701 feat/AB#105911_improve-dropdown-display-to-automatically-open-on-click
  libs/shared/src/lib/survey/widgets/dropdown-widget.ts
  libs/shared/src/lib/survey/widgets/tagbox-widget.ts
Labels: enhancement

#2703 feat/AB#105911_improve-dropdown-display-to-automatically-open-on-click-improvement
  libs/shared/src/lib/survey/widgets/dropdown-widget.ts
Labels: enhancement

#2709 fix/AB#106239_EIS-file-download-not-working-during-edition-of-record-with-attached-file
  libs/shared/src/lib/components/form-modal/form-modal.component.ts
  libs/shared/src/lib/components/form/form.component.ts
Labels: bug, alpha
