Repository ReliefApplications/ems-frontend, pull requests merged in 2024-03, with the labels that each got.

#2424 bugfix/AB#86936_ABC-sometimes-it-becomes-impossible-to-click-the-layers-button-in-the-dashboard
  apps/web-widgets/src/app/app.module.ts
  apps/web-widgets/src/app/utils/overlay-container.ts
Labels: bug

#2425 bugfix/AB#87069_SUI-map-unable-close-full-screen-of-map-on-click-of-expand-icon-on-map-widget
  apps/back-office/project.json
  apps/front-office/project.json
  apps/web-widgets/src/app/widgets/app-widget/app-widget.component.scss
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/services/map/map-controls.service.ts
  libs/styles/src/lib/shared/shared.scss
  package-lock.json
  package.json
Labels: bug, refactor

#2429 bugfix/AB#87222_ABC-dependency-error-due-to-dashboard-automation-service
  libs/shared/src/lib/components/ui/map/layer.ts
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.ts
Labels: bug

#2435 Ab#87614 classic style available for datepicker
  libs/shared/src/lib/components/dashboard-filter/filter-builder-modal/filter-builder-modal.component.ts
  libs/shared/src/lib/survey/components/utils/create-picker-instance.ts
  libs/shared/src/lib/survey/widgets/text-widget.ts
Labels: enhancement

#2437 Feat/ab#87683 abc allow heatmap layers to use intensity field
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/controls/gradient-picker/gradient-picker.component.html
  libs/shared/src/lib/components/controls/gradient-picker/gradient-picker.component.ts
  libs/shared/src/lib/components/controls/gradient-picker/gradient-picker.module.ts
  libs/shared/src/lib/components/ui/map/layer.ts
  libs/shared/src/lib/components/ui/map/utils/leaflet-heatmap.js
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/heatmap-renderer/heatmap-renderer.component.html
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/heatmap-renderer/heatmap-renderer.component.ts
  libs/shared/src/lib/components/widgets/map-settings/edit-layer-modal/layer-styling/layer-styling.component.html
  libs/shared/src/lib/components/widgets/map-settings/map-forms.ts
  package-lock.json
  package.json
Labels: enhancement, dependencies

#2439 feat/AB#87702_ABC-allow-opacity-to-work-with-heatmap-layer
  libs/shared/src/lib/components/ui/map/layer.ts
  libs/shared/src/lib/components/ui/map/utils/leaflet-heatmap.js
Labels: enhancement

#2441 bugfix/AB#87744_fix-section-load-when-user-on-any-advanced-settings-subtabs
  apps/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/aggregations-tab/aggregations-tab.module.ts
  apps/back-office/src/app/dashboard/pages/resource/components/data-presentation-list/data-presentation-list.component.html
  apps/back-office/src/app/dashboard/pages/resource/components/data-presentation-list/data-presentation-list.component.ts
  apps/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.component.html
  apps/back-office/src/app/dashboard/pages/resource/layouts-tab/layouts-tab.module.ts
  libs/shared/src/lib/components/navbar/navbar.component.ts
  libs/shared/src/lib/components/ui/map/layer.ts
Labels: bug

#2442 feat/AB#87702_ABC-allow-opacity-to-work-with-heatmap-layer-add-interface
  libs/shared/src/lib/components/ui/map/layer.ts
  libs/shared/src/lib/models/layer.model.ts
Labels: enhancement

#2445 feat/AB#87701_ABC-deactivate-cross-page-filtering-so-each-page-handles-its-own-filter
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/shared/src/lib/components/layout/layout.component.ts
  libs/shared/src/lib/services/context/context.service.ts
Labels: enhancement

#2452 bugfix/AB#88157_SUI-clicking-in-a-point-of-an-expanded-cluster-should-open-the-country-based-on-the-latitude-longitude-of-the-point
  libs/shared/src/lib/components/ui/map/layer.ts
Labels: bug

#2453 bugfix/AB#88170_ABC-onDownloadFile-from-forms-not-being-called-when-the-form-is-readonly
  libs/shared/src/lib/components/record-modal/record-modal.component.ts
Labels: bug

#2451 bugfix/AB#88132_on-drag-and-drop-tooltips-are-not-correctly-removed-from-the-dom
  libs/shared/src/lib/components/applications-summary/applications-summary.component.scss
  libs/shared/src/lib/components/dashboard-filter/dashboard-filter.component.ts
  libs/ui/src/lib/sidenav/sidenav-container.component.ts
  libs/ui/src/lib/tooltip/tooltip.directive.ts
Labels: bug

#2449 refactor/duplicated-widget-methods
  libs/shared/src/lib/components/widgets/chart/chart.component.ts
  libs/shared/src/lib/components/widgets/common/widget-automation/edit-automation-component/edit-automation-component.component.ts
  libs/shared/src/lib/components/widgets/editor/editor.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card.component.ts
  libs/shared/src/lib/services/map/map-layers.service.ts
  libs/shared/src/lib/services/widget/widget.service.ts
Labels: refactor

#2450 Ab#88033 add styling for automation
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/index.ts
  libs/shared/src/lib/components/ui/map/map.component.ts
  libs/shared/src/lib/components/widgets/common/tab-widget-automations/tab-widget-automations.component.html
  libs/shared/src/lib/components/widgets/common/widget-automation/automation-component-selector/automation-component-selector.component.html
  libs/shared/src/lib/components/widgets/common/widget-automation/automation-component-selector/automation-component-selector.component.ts
  libs/shared/src/lib/components/widgets/common/widget-automation/edit-automation-component/edit-automation-component.component.html
  libs/shared/src/lib/components/widgets/common/widget-automation/edit-automation-component/edit-automation-component.component.ts
  libs/shared/src/lib/components/widgets/common/widget-automation/widget-automation.component.html
  libs/shared/src/lib/components/widgets/common/widget-automation/widget-automation.component.ts
  libs/shared/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.ts
  libs/shared/src/lib/forms/automation.forms.ts
  libs/shared/src/lib/models/automation.model.ts
  libs/shared/src/lib/services/dashboard-automation/dashboard-automation.service.ts
  libs/shared/src/lib/services/widget/widget.service.ts
Labels: enhancement

#2461 Ab#88816 role based display for action buttons
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.scss
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.spec.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-action-modal/edit-button-action-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-actions-modal/edit-button-actions-modal.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-actions-modal/edit-button-actions-modal.component.scss
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-actions-modal/edit-button-actions-modal.component.spec.ts
  apps/back-office/src/app/dashboard/pages/dashboard/components/edit-button-actions-modal/edit-button-actions-modal.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/button-action/button-action-type.ts
  libs/shared/src/lib/components/button-action/button-action.component.html
  libs/shared/src/lib/components/button-action/button-action.component.ts
  libs/shared/src/lib/models/dashboard.model.ts
  libs/ui/src/lib/tooltip/tooltip.stories.ts
Labels: changes

#2455 Feat/ab#86603 ABC SA Attach to record action proceed after record saved
  libs/shared/src/lib/components/form-modal/form-modal.component.ts
  libs/shared/src/lib/components/widgets/grid/grid.component.ts
Labels: changes
