Repository ReliefApplications/ems-frontend, pull requests merged in 2025-01, with the labels that each got.

#2727 AB#107245 use utf-8 decoding in email preview component
  libs/shared/src/lib/components/email/steps/preview/preview.component.ts
Labels: bug, alpha

#2739 AB#107578 Quick action feature -> certain fields are displayed as data incorrectly
  libs/shared/src/lib/components/action-button/action-button.component.ts
  libs/shared/src/lib/components/email/steps/layout/layout.component.ts
  libs/shared/src/lib/components/email/steps/preview/preview.component.ts
  libs/shared/src/lib/components/templates/components/preview-template-modal/preview-template-modal.component.ts
  libs/shared/src/lib/components/widgets/grid/grid.component.ts
  libs/shared/src/lib/services/email/email.service.ts
Labels: bug, changes, alpha

#2744 feat/AB#108396_EIS-better-track-user-navigation
  apps/back-office/src/app/application/pages/form/form.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
  apps/back-office/src/app/dashboard/pages/dashboard/graphql/queries.ts
  apps/front-office/src/app/application/pages/dashboard/dashboard.component.ts
  apps/front-office/src/app/application/pages/dashboard/graphql/queries.ts
  apps/front-office/src/app/application/pages/form/form.component.ts
  apps/front-office/src/app/application/pages/form/graphql/queries.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/dashboard.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/dashboard/graphql/queries.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/form/form.component.ts
  apps/web-widgets/src/app/widgets/app-widget/application/pages/form/graphql/queries.ts
  libs/shared/src/lib/services/breadcrumb/breadcrumb.service.ts
  libs/shared/src/lib/services/logger/logger.service.ts
Labels: alpha

#2735 AB#107541 - Email Notifications ES651 Distribution change to incorporate common services
  libs/shared/src/i18n/en.json
  libs/shared/src/i18n/fr.json
  libs/shared/src/i18n/test.json
  libs/shared/src/lib/components/action-button/action-button.component.ts
  libs/shared/src/lib/components/email/components/custom-templates/custom-template.component.ts
  libs/shared/src/lib/components/email/components/email-template/email-template.component.html
  libs/shared/src/lib/components/email/components/email-template/email-template.component.ts
  libs/shared/src/lib/components/email/components/ems-template/ems-template.component.ts
  libs/shared/src/lib/components/email/constant.ts
  libs/shared/src/lib/components/email/email.component.ts
  libs/shared/src/lib/components/email/email.module.ts
  libs/shared/src/lib/components/email/email.service.ts
  libs/shared/src/lib/components/email/graphql/queries.ts
  libs/shared/src/lib/components/email/steps/layout/layout.component.ts
  libs/shared/src/lib/components/email/steps/preview/preview.component.html
  libs/shared/src/lib/components/email/steps/preview/preview.component.ts
  libs/shared/src/lib/components/email/steps/select-distribution/select-distribution.component.html
  libs/shared/src/lib/components/email/steps/select-distribution/select-distribution.component.scss
  libs/shared/src/lib/components/email/steps/select-distribution/select-distribution.component.ts
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.html
  libs/shared/src/lib/components/filter/filter-row/filter-row.component.ts
  libs/shared/src/lib/components/filter/filter.module.ts
  libs/shared/src/lib/components/query-builder/tab-filter/tab-filter.component.ts
  libs/shared/src/lib/components/templates/components/preview-template-modal/preview-template-modal.component.ts
  libs/shared/src/lib/components/widgets/grid-settings/grid-settings.component.ts
  libs/shared/src/lib/components/widgets/grid/grid.component.ts
  libs/shared/src/lib/services/common-services/common-services.service.spec.ts
  libs/shared/src/lib/services/common-services/common-services.service.ts
  libs/shared/src/lib/services/email/email.service.ts
  libs/shared/src/lib/services/query-builder/query-builder.service.ts
Labels: enhancement
